infix using "C:\HT7A\EXPORT\EXPORTEDFILES\HTCS7AFLSP.dct"

label variable facil    "Facility identification"
label variable q32line_01 "Line number"
label variable q32line_02 "Line number"
label variable q32line_03 "Line number"
label variable q32line_04 "Line number"
label variable q32line_05 "Line number"
label variable q32line_06 "Line number"
label variable q32line_07 "Line number"
label variable q32line_08 "Line number"
label variable q32line_09 "Line number"
label variable q32line_10 "Line number"
label variable q32line_11 "Line number"
label variable q32line_12 "Line number"
label variable q32line_13 "Line number"
label variable q32line_14 "Line number"
label variable q32line_15 "Line number"
label variable q32line_16 "Line number"
label variable q32line_17 "Line number"
label variable q32line_18 "Line number"
label variable q32line_19 "Line number"
label variable q32line_20 "Line number"
label variable q32line_21 "Line number"
label variable q32line_22 "Line number"
label variable q32line_23 "Line number"
label variable q32line_24 "Line number"
label variable q32line_25 "Line number"
label variable q32line_26 "Line number"
label variable q32line_27 "Line number"
label variable q32line_28 "Line number"
label variable q32line_29 "Line number"
label variable q32line_30 "Line number"
label variable q32line_31 "Line number"
label variable q32line_32 "Line number"
label variable q32line_33 "Line number"
label variable q32line_34 "Line number"
label variable q32line_35 "Line number"
label variable q32line_36 "Line number"
label variable q32line_37 "Line number"
label variable q32line_38 "Line number"
label variable q32line_39 "Line number"
label variable q32line_40 "Line number"
label variable q32line_41 "Line number"
label variable q32line_42 "Line number"
label variable q32line_43 "Line number"
label variable q32line_44 "Line number"
label variable q32line_45 "Line number"
label variable q32line_46 "Line number"
label variable q32line_47 "Line number"
label variable q32line_48 "Line number"
label variable q32line_49 "Line number"
label variable q32line_50 "Line number"
label variable q32line_51 "Line number"
label variable q32line_52 "Line number"
label variable q32line_53 "Line number"
label variable q32line_54 "Line number"
label variable q32line_55 "Line number"
label variable q32line_56 "Line number"
label variable q32line_57 "Line number"
label variable q32line_58 "Line number"
label variable q32line_59 "Line number"
label variable q32line_60 "Line number"
label variable q32line_61 "Line number"
label variable q32line_62 "Line number"
label variable q32line_63 "Line number"
label variable q32line_64 "Line number"
label variable q32line_65 "Line number"
label variable q32line_66 "Line number"
label variable q32line_67 "Line number"
label variable q32line_68 "Line number"
label variable q32line_69 "Line number"
label variable q32line_70 "Line number"
label variable q32line_71 "Line number"
label variable q32line_72 "Line number"
label variable q32line_73 "Line number"
label variable q32line_74 "Line number"
label variable q32line_75 "Line number"
label variable q32line_76 "Line number"
label variable q32line_77 "Line number"
label variable q32line_78 "Line number"
label variable q32line_79 "Line number"
label variable q32line_80 "Line number"
label variable q32line_81 "Line number"
label variable q32line_82 "Line number"
label variable q32line_83 "Line number"
label variable q32line_84 "Line number"
label variable q32line_85 "Line number"
label variable q32line_86 "Line number"
label variable q32line_87 "Line number"
label variable q32line_88 "Line number"
label variable q32line_89 "Line number"
label variable q32line_90 "Line number"
label variable q32line_91 "Line number"
label variable q32line_92 "Line number"
label variable q32line_93 "Line number"
label variable q32line_94 "Line number"
label variable q32line_95 "Line number"
label variable q32line_96 "Line number"
label variable q32line_97 "Line number"
label variable q32line_98 "Line number"
label variable q32line_99 "Line number"
label variable q3203_01 "Sex"
label variable q3203_02 "Sex"
label variable q3203_03 "Sex"
label variable q3203_04 "Sex"
label variable q3203_05 "Sex"
label variable q3203_06 "Sex"
label variable q3203_07 "Sex"
label variable q3203_08 "Sex"
label variable q3203_09 "Sex"
label variable q3203_10 "Sex"
label variable q3203_11 "Sex"
label variable q3203_12 "Sex"
label variable q3203_13 "Sex"
label variable q3203_14 "Sex"
label variable q3203_15 "Sex"
label variable q3203_16 "Sex"
label variable q3203_17 "Sex"
label variable q3203_18 "Sex"
label variable q3203_19 "Sex"
label variable q3203_20 "Sex"
label variable q3203_21 "Sex"
label variable q3203_22 "Sex"
label variable q3203_23 "Sex"
label variable q3203_24 "Sex"
label variable q3203_25 "Sex"
label variable q3203_26 "Sex"
label variable q3203_27 "Sex"
label variable q3203_28 "Sex"
label variable q3203_29 "Sex"
label variable q3203_30 "Sex"
label variable q3203_31 "Sex"
label variable q3203_32 "Sex"
label variable q3203_33 "Sex"
label variable q3203_34 "Sex"
label variable q3203_35 "Sex"
label variable q3203_36 "Sex"
label variable q3203_37 "Sex"
label variable q3203_38 "Sex"
label variable q3203_39 "Sex"
label variable q3203_40 "Sex"
label variable q3203_41 "Sex"
label variable q3203_42 "Sex"
label variable q3203_43 "Sex"
label variable q3203_44 "Sex"
label variable q3203_45 "Sex"
label variable q3203_46 "Sex"
label variable q3203_47 "Sex"
label variable q3203_48 "Sex"
label variable q3203_49 "Sex"
label variable q3203_50 "Sex"
label variable q3203_51 "Sex"
label variable q3203_52 "Sex"
label variable q3203_53 "Sex"
label variable q3203_54 "Sex"
label variable q3203_55 "Sex"
label variable q3203_56 "Sex"
label variable q3203_57 "Sex"
label variable q3203_58 "Sex"
label variable q3203_59 "Sex"
label variable q3203_60 "Sex"
label variable q3203_61 "Sex"
label variable q3203_62 "Sex"
label variable q3203_63 "Sex"
label variable q3203_64 "Sex"
label variable q3203_65 "Sex"
label variable q3203_66 "Sex"
label variable q3203_67 "Sex"
label variable q3203_68 "Sex"
label variable q3203_69 "Sex"
label variable q3203_70 "Sex"
label variable q3203_71 "Sex"
label variable q3203_72 "Sex"
label variable q3203_73 "Sex"
label variable q3203_74 "Sex"
label variable q3203_75 "Sex"
label variable q3203_76 "Sex"
label variable q3203_77 "Sex"
label variable q3203_78 "Sex"
label variable q3203_79 "Sex"
label variable q3203_80 "Sex"
label variable q3203_81 "Sex"
label variable q3203_82 "Sex"
label variable q3203_83 "Sex"
label variable q3203_84 "Sex"
label variable q3203_85 "Sex"
label variable q3203_86 "Sex"
label variable q3203_87 "Sex"
label variable q3203_88 "Sex"
label variable q3203_89 "Sex"
label variable q3203_90 "Sex"
label variable q3203_91 "Sex"
label variable q3203_92 "Sex"
label variable q3203_93 "Sex"
label variable q3203_94 "Sex"
label variable q3203_95 "Sex"
label variable q3203_96 "Sex"
label variable q3203_97 "Sex"
label variable q3203_98 "Sex"
label variable q3203_99 "Sex"
label variable q3204_01 "Education level"
label variable q3204_02 "Education level"
label variable q3204_03 "Education level"
label variable q3204_04 "Education level"
label variable q3204_05 "Education level"
label variable q3204_06 "Education level"
label variable q3204_07 "Education level"
label variable q3204_08 "Education level"
label variable q3204_09 "Education level"
label variable q3204_10 "Education level"
label variable q3204_11 "Education level"
label variable q3204_12 "Education level"
label variable q3204_13 "Education level"
label variable q3204_14 "Education level"
label variable q3204_15 "Education level"
label variable q3204_16 "Education level"
label variable q3204_17 "Education level"
label variable q3204_18 "Education level"
label variable q3204_19 "Education level"
label variable q3204_20 "Education level"
label variable q3204_21 "Education level"
label variable q3204_22 "Education level"
label variable q3204_23 "Education level"
label variable q3204_24 "Education level"
label variable q3204_25 "Education level"
label variable q3204_26 "Education level"
label variable q3204_27 "Education level"
label variable q3204_28 "Education level"
label variable q3204_29 "Education level"
label variable q3204_30 "Education level"
label variable q3204_31 "Education level"
label variable q3204_32 "Education level"
label variable q3204_33 "Education level"
label variable q3204_34 "Education level"
label variable q3204_35 "Education level"
label variable q3204_36 "Education level"
label variable q3204_37 "Education level"
label variable q3204_38 "Education level"
label variable q3204_39 "Education level"
label variable q3204_40 "Education level"
label variable q3204_41 "Education level"
label variable q3204_42 "Education level"
label variable q3204_43 "Education level"
label variable q3204_44 "Education level"
label variable q3204_45 "Education level"
label variable q3204_46 "Education level"
label variable q3204_47 "Education level"
label variable q3204_48 "Education level"
label variable q3204_49 "Education level"
label variable q3204_50 "Education level"
label variable q3204_51 "Education level"
label variable q3204_52 "Education level"
label variable q3204_53 "Education level"
label variable q3204_54 "Education level"
label variable q3204_55 "Education level"
label variable q3204_56 "Education level"
label variable q3204_57 "Education level"
label variable q3204_58 "Education level"
label variable q3204_59 "Education level"
label variable q3204_60 "Education level"
label variable q3204_61 "Education level"
label variable q3204_62 "Education level"
label variable q3204_63 "Education level"
label variable q3204_64 "Education level"
label variable q3204_65 "Education level"
label variable q3204_66 "Education level"
label variable q3204_67 "Education level"
label variable q3204_68 "Education level"
label variable q3204_69 "Education level"
label variable q3204_70 "Education level"
label variable q3204_71 "Education level"
label variable q3204_72 "Education level"
label variable q3204_73 "Education level"
label variable q3204_74 "Education level"
label variable q3204_75 "Education level"
label variable q3204_76 "Education level"
label variable q3204_77 "Education level"
label variable q3204_78 "Education level"
label variable q3204_79 "Education level"
label variable q3204_80 "Education level"
label variable q3204_81 "Education level"
label variable q3204_82 "Education level"
label variable q3204_83 "Education level"
label variable q3204_84 "Education level"
label variable q3204_85 "Education level"
label variable q3204_86 "Education level"
label variable q3204_87 "Education level"
label variable q3204_88 "Education level"
label variable q3204_89 "Education level"
label variable q3204_90 "Education level"
label variable q3204_91 "Education level"
label variable q3204_92 "Education level"
label variable q3204_93 "Education level"
label variable q3204_94 "Education level"
label variable q3204_95 "Education level"
label variable q3204_96 "Education level"
label variable q3204_97 "Education level"
label variable q3204_98 "Education level"
label variable q3204_99 "Education level"
label variable q3205_01 "Agent type"
label variable q3205_02 "Agent type"
label variable q3205_03 "Agent type"
label variable q3205_04 "Agent type"
label variable q3205_05 "Agent type"
label variable q3205_06 "Agent type"
label variable q3205_07 "Agent type"
label variable q3205_08 "Agent type"
label variable q3205_09 "Agent type"
label variable q3205_10 "Agent type"
label variable q3205_11 "Agent type"
label variable q3205_12 "Agent type"
label variable q3205_13 "Agent type"
label variable q3205_14 "Agent type"
label variable q3205_15 "Agent type"
label variable q3205_16 "Agent type"
label variable q3205_17 "Agent type"
label variable q3205_18 "Agent type"
label variable q3205_19 "Agent type"
label variable q3205_20 "Agent type"
label variable q3205_21 "Agent type"
label variable q3205_22 "Agent type"
label variable q3205_23 "Agent type"
label variable q3205_24 "Agent type"
label variable q3205_25 "Agent type"
label variable q3205_26 "Agent type"
label variable q3205_27 "Agent type"
label variable q3205_28 "Agent type"
label variable q3205_29 "Agent type"
label variable q3205_30 "Agent type"
label variable q3205_31 "Agent type"
label variable q3205_32 "Agent type"
label variable q3205_33 "Agent type"
label variable q3205_34 "Agent type"
label variable q3205_35 "Agent type"
label variable q3205_36 "Agent type"
label variable q3205_37 "Agent type"
label variable q3205_38 "Agent type"
label variable q3205_39 "Agent type"
label variable q3205_40 "Agent type"
label variable q3205_41 "Agent type"
label variable q3205_42 "Agent type"
label variable q3205_43 "Agent type"
label variable q3205_44 "Agent type"
label variable q3205_45 "Agent type"
label variable q3205_46 "Agent type"
label variable q3205_47 "Agent type"
label variable q3205_48 "Agent type"
label variable q3205_49 "Agent type"
label variable q3205_50 "Agent type"
label variable q3205_51 "Agent type"
label variable q3205_52 "Agent type"
label variable q3205_53 "Agent type"
label variable q3205_54 "Agent type"
label variable q3205_55 "Agent type"
label variable q3205_56 "Agent type"
label variable q3205_57 "Agent type"
label variable q3205_58 "Agent type"
label variable q3205_59 "Agent type"
label variable q3205_60 "Agent type"
label variable q3205_61 "Agent type"
label variable q3205_62 "Agent type"
label variable q3205_63 "Agent type"
label variable q3205_64 "Agent type"
label variable q3205_65 "Agent type"
label variable q3205_66 "Agent type"
label variable q3205_67 "Agent type"
label variable q3205_68 "Agent type"
label variable q3205_69 "Agent type"
label variable q3205_70 "Agent type"
label variable q3205_71 "Agent type"
label variable q3205_72 "Agent type"
label variable q3205_73 "Agent type"
label variable q3205_74 "Agent type"
label variable q3205_75 "Agent type"
label variable q3205_76 "Agent type"
label variable q3205_77 "Agent type"
label variable q3205_78 "Agent type"
label variable q3205_79 "Agent type"
label variable q3205_80 "Agent type"
label variable q3205_81 "Agent type"
label variable q3205_82 "Agent type"
label variable q3205_83 "Agent type"
label variable q3205_84 "Agent type"
label variable q3205_85 "Agent type"
label variable q3205_86 "Agent type"
label variable q3205_87 "Agent type"
label variable q3205_88 "Agent type"
label variable q3205_89 "Agent type"
label variable q3205_90 "Agent type"
label variable q3205_91 "Agent type"
label variable q3205_92 "Agent type"
label variable q3205_93 "Agent type"
label variable q3205_94 "Agent type"
label variable q3205_95 "Agent type"
label variable q3205_96 "Agent type"
label variable q3205_97 "Agent type"
label variable q3205_98 "Agent type"
label variable q3205_99 "Agent type"
label variable q3208_01 "Year started to work"
label variable q3208_02 "Year started to work"
label variable q3208_03 "Year started to work"
label variable q3208_04 "Year started to work"
label variable q3208_05 "Year started to work"
label variable q3208_06 "Year started to work"
label variable q3208_07 "Year started to work"
label variable q3208_08 "Year started to work"
label variable q3208_09 "Year started to work"
label variable q3208_10 "Year started to work"
label variable q3208_11 "Year started to work"
label variable q3208_12 "Year started to work"
label variable q3208_13 "Year started to work"
label variable q3208_14 "Year started to work"
label variable q3208_15 "Year started to work"
label variable q3208_16 "Year started to work"
label variable q3208_17 "Year started to work"
label variable q3208_18 "Year started to work"
label variable q3208_19 "Year started to work"
label variable q3208_20 "Year started to work"
label variable q3208_21 "Year started to work"
label variable q3208_22 "Year started to work"
label variable q3208_23 "Year started to work"
label variable q3208_24 "Year started to work"
label variable q3208_25 "Year started to work"
label variable q3208_26 "Year started to work"
label variable q3208_27 "Year started to work"
label variable q3208_28 "Year started to work"
label variable q3208_29 "Year started to work"
label variable q3208_30 "Year started to work"
label variable q3208_31 "Year started to work"
label variable q3208_32 "Year started to work"
label variable q3208_33 "Year started to work"
label variable q3208_34 "Year started to work"
label variable q3208_35 "Year started to work"
label variable q3208_36 "Year started to work"
label variable q3208_37 "Year started to work"
label variable q3208_38 "Year started to work"
label variable q3208_39 "Year started to work"
label variable q3208_40 "Year started to work"
label variable q3208_41 "Year started to work"
label variable q3208_42 "Year started to work"
label variable q3208_43 "Year started to work"
label variable q3208_44 "Year started to work"
label variable q3208_45 "Year started to work"
label variable q3208_46 "Year started to work"
label variable q3208_47 "Year started to work"
label variable q3208_48 "Year started to work"
label variable q3208_49 "Year started to work"
label variable q3208_50 "Year started to work"
label variable q3208_51 "Year started to work"
label variable q3208_52 "Year started to work"
label variable q3208_53 "Year started to work"
label variable q3208_54 "Year started to work"
label variable q3208_55 "Year started to work"
label variable q3208_56 "Year started to work"
label variable q3208_57 "Year started to work"
label variable q3208_58 "Year started to work"
label variable q3208_59 "Year started to work"
label variable q3208_60 "Year started to work"
label variable q3208_61 "Year started to work"
label variable q3208_62 "Year started to work"
label variable q3208_63 "Year started to work"
label variable q3208_64 "Year started to work"
label variable q3208_65 "Year started to work"
label variable q3208_66 "Year started to work"
label variable q3208_67 "Year started to work"
label variable q3208_68 "Year started to work"
label variable q3208_69 "Year started to work"
label variable q3208_70 "Year started to work"
label variable q3208_71 "Year started to work"
label variable q3208_72 "Year started to work"
label variable q3208_73 "Year started to work"
label variable q3208_74 "Year started to work"
label variable q3208_75 "Year started to work"
label variable q3208_76 "Year started to work"
label variable q3208_77 "Year started to work"
label variable q3208_78 "Year started to work"
label variable q3208_79 "Year started to work"
label variable q3208_80 "Year started to work"
label variable q3208_81 "Year started to work"
label variable q3208_82 "Year started to work"
label variable q3208_83 "Year started to work"
label variable q3208_84 "Year started to work"
label variable q3208_85 "Year started to work"
label variable q3208_86 "Year started to work"
label variable q3208_87 "Year started to work"
label variable q3208_88 "Year started to work"
label variable q3208_89 "Year started to work"
label variable q3208_90 "Year started to work"
label variable q3208_91 "Year started to work"
label variable q3208_92 "Year started to work"
label variable q3208_93 "Year started to work"
label variable q3208_94 "Year started to work"
label variable q3208_95 "Year started to work"
label variable q3208_96 "Year started to work"
label variable q3208_97 "Year started to work"
label variable q3208_98 "Year started to work"
label variable q3208_99 "Year started to work"

#delimit ;
label define Q3203   
     1 "Homme"
     2 "Femme"
;
label define Q3204   
     1 "Primaire"
     2 "Secondaire"
     3 "Supérieuse"
     9 "Pas disponible"
;
label define Q3205   
     1 "Agent de santé communitaire (ASC)"
     2 "Agent de santé communitaire polyvalent (ASCP)"
     3 "Superviseur"
;
label define Q3208   
  9998 "NSP"
  9999 "Pas disponible"
;

#delimit cr
label values q3203_01 Q3203   
label values q3203_02 Q3203   
label values q3203_03 Q3203   
label values q3203_04 Q3203   
label values q3203_05 Q3203   
label values q3203_06 Q3203   
label values q3203_07 Q3203   
label values q3203_08 Q3203   
label values q3203_09 Q3203   
label values q3203_10 Q3203   
label values q3203_11 Q3203   
label values q3203_12 Q3203   
label values q3203_13 Q3203   
label values q3203_14 Q3203   
label values q3203_15 Q3203   
label values q3203_16 Q3203   
label values q3203_17 Q3203   
label values q3203_18 Q3203   
label values q3203_19 Q3203   
label values q3203_20 Q3203   
label values q3203_21 Q3203   
label values q3203_22 Q3203   
label values q3203_23 Q3203   
label values q3203_24 Q3203   
label values q3203_25 Q3203   
label values q3203_26 Q3203   
label values q3203_27 Q3203   
label values q3203_28 Q3203   
label values q3203_29 Q3203   
label values q3203_30 Q3203   
label values q3203_31 Q3203   
label values q3203_32 Q3203   
label values q3203_33 Q3203   
label values q3203_34 Q3203   
label values q3203_35 Q3203   
label values q3203_36 Q3203   
label values q3203_37 Q3203   
label values q3203_38 Q3203   
label values q3203_39 Q3203   
label values q3203_40 Q3203   
label values q3203_41 Q3203   
label values q3203_42 Q3203   
label values q3203_43 Q3203   
label values q3203_44 Q3203   
label values q3203_45 Q3203   
label values q3203_46 Q3203   
label values q3203_47 Q3203   
label values q3203_48 Q3203   
label values q3203_49 Q3203   
label values q3203_50 Q3203   
label values q3203_51 Q3203   
label values q3203_52 Q3203   
label values q3203_53 Q3203   
label values q3203_54 Q3203   
label values q3203_55 Q3203   
label values q3203_56 Q3203   
label values q3203_57 Q3203   
label values q3203_58 Q3203   
label values q3203_59 Q3203   
label values q3203_60 Q3203   
label values q3203_61 Q3203   
label values q3203_62 Q3203   
label values q3203_63 Q3203   
label values q3203_64 Q3203   
label values q3203_65 Q3203   
label values q3203_66 Q3203   
label values q3203_67 Q3203   
label values q3203_68 Q3203   
label values q3203_69 Q3203   
label values q3203_70 Q3203   
label values q3203_71 Q3203   
label values q3203_72 Q3203   
label values q3203_73 Q3203   
label values q3203_74 Q3203   
label values q3203_75 Q3203   
label values q3203_76 Q3203   
label values q3203_77 Q3203   
label values q3203_78 Q3203   
label values q3203_79 Q3203   
label values q3203_80 Q3203   
label values q3203_81 Q3203   
label values q3203_82 Q3203   
label values q3203_83 Q3203   
label values q3203_84 Q3203   
label values q3203_85 Q3203   
label values q3203_86 Q3203   
label values q3203_87 Q3203   
label values q3203_88 Q3203   
label values q3203_89 Q3203   
label values q3203_90 Q3203   
label values q3203_91 Q3203   
label values q3203_92 Q3203   
label values q3203_93 Q3203   
label values q3203_94 Q3203   
label values q3203_95 Q3203   
label values q3203_96 Q3203   
label values q3203_97 Q3203   
label values q3203_98 Q3203   
label values q3203_99 Q3203   
label values q3204_01 Q3204   
label values q3204_02 Q3204   
label values q3204_03 Q3204   
label values q3204_04 Q3204   
label values q3204_05 Q3204   
label values q3204_06 Q3204   
label values q3204_07 Q3204   
label values q3204_08 Q3204   
label values q3204_09 Q3204   
label values q3204_10 Q3204   
label values q3204_11 Q3204   
label values q3204_12 Q3204   
label values q3204_13 Q3204   
label values q3204_14 Q3204   
label values q3204_15 Q3204   
label values q3204_16 Q3204   
label values q3204_17 Q3204   
label values q3204_18 Q3204   
label values q3204_19 Q3204   
label values q3204_20 Q3204   
label values q3204_21 Q3204   
label values q3204_22 Q3204   
label values q3204_23 Q3204   
label values q3204_24 Q3204   
label values q3204_25 Q3204   
label values q3204_26 Q3204   
label values q3204_27 Q3204   
label values q3204_28 Q3204   
label values q3204_29 Q3204   
label values q3204_30 Q3204   
label values q3204_31 Q3204   
label values q3204_32 Q3204   
label values q3204_33 Q3204   
label values q3204_34 Q3204   
label values q3204_35 Q3204   
label values q3204_36 Q3204   
label values q3204_37 Q3204   
label values q3204_38 Q3204   
label values q3204_39 Q3204   
label values q3204_40 Q3204   
label values q3204_41 Q3204   
label values q3204_42 Q3204   
label values q3204_43 Q3204   
label values q3204_44 Q3204   
label values q3204_45 Q3204   
label values q3204_46 Q3204   
label values q3204_47 Q3204   
label values q3204_48 Q3204   
label values q3204_49 Q3204   
label values q3204_50 Q3204   
label values q3204_51 Q3204   
label values q3204_52 Q3204   
label values q3204_53 Q3204   
label values q3204_54 Q3204   
label values q3204_55 Q3204   
label values q3204_56 Q3204   
label values q3204_57 Q3204   
label values q3204_58 Q3204   
label values q3204_59 Q3204   
label values q3204_60 Q3204   
label values q3204_61 Q3204   
label values q3204_62 Q3204   
label values q3204_63 Q3204   
label values q3204_64 Q3204   
label values q3204_65 Q3204   
label values q3204_66 Q3204   
label values q3204_67 Q3204   
label values q3204_68 Q3204   
label values q3204_69 Q3204   
label values q3204_70 Q3204   
label values q3204_71 Q3204   
label values q3204_72 Q3204   
label values q3204_73 Q3204   
label values q3204_74 Q3204   
label values q3204_75 Q3204   
label values q3204_76 Q3204   
label values q3204_77 Q3204   
label values q3204_78 Q3204   
label values q3204_79 Q3204   
label values q3204_80 Q3204   
label values q3204_81 Q3204   
label values q3204_82 Q3204   
label values q3204_83 Q3204   
label values q3204_84 Q3204   
label values q3204_85 Q3204   
label values q3204_86 Q3204   
label values q3204_87 Q3204   
label values q3204_88 Q3204   
label values q3204_89 Q3204   
label values q3204_90 Q3204   
label values q3204_91 Q3204   
label values q3204_92 Q3204   
label values q3204_93 Q3204   
label values q3204_94 Q3204   
label values q3204_95 Q3204   
label values q3204_96 Q3204   
label values q3204_97 Q3204   
label values q3204_98 Q3204   
label values q3204_99 Q3204   
label values q3205_01 Q3205   
label values q3205_02 Q3205   
label values q3205_03 Q3205   
label values q3205_04 Q3205   
label values q3205_05 Q3205   
label values q3205_06 Q3205   
label values q3205_07 Q3205   
label values q3205_08 Q3205   
label values q3205_09 Q3205   
label values q3205_10 Q3205   
label values q3205_11 Q3205   
label values q3205_12 Q3205   
label values q3205_13 Q3205   
label values q3205_14 Q3205   
label values q3205_15 Q3205   
label values q3205_16 Q3205   
label values q3205_17 Q3205   
label values q3205_18 Q3205   
label values q3205_19 Q3205   
label values q3205_20 Q3205   
label values q3205_21 Q3205   
label values q3205_22 Q3205   
label values q3205_23 Q3205   
label values q3205_24 Q3205   
label values q3205_25 Q3205   
label values q3205_26 Q3205   
label values q3205_27 Q3205   
label values q3205_28 Q3205   
label values q3205_29 Q3205   
label values q3205_30 Q3205   
label values q3205_31 Q3205   
label values q3205_32 Q3205   
label values q3205_33 Q3205   
label values q3205_34 Q3205   
label values q3205_35 Q3205   
label values q3205_36 Q3205   
label values q3205_37 Q3205   
label values q3205_38 Q3205   
label values q3205_39 Q3205   
label values q3205_40 Q3205   
label values q3205_41 Q3205   
label values q3205_42 Q3205   
label values q3205_43 Q3205   
label values q3205_44 Q3205   
label values q3205_45 Q3205   
label values q3205_46 Q3205   
label values q3205_47 Q3205   
label values q3205_48 Q3205   
label values q3205_49 Q3205   
label values q3205_50 Q3205   
label values q3205_51 Q3205   
label values q3205_52 Q3205   
label values q3205_53 Q3205   
label values q3205_54 Q3205   
label values q3205_55 Q3205   
label values q3205_56 Q3205   
label values q3205_57 Q3205   
label values q3205_58 Q3205   
label values q3205_59 Q3205   
label values q3205_60 Q3205   
label values q3205_61 Q3205   
label values q3205_62 Q3205   
label values q3205_63 Q3205   
label values q3205_64 Q3205   
label values q3205_65 Q3205   
label values q3205_66 Q3205   
label values q3205_67 Q3205   
label values q3205_68 Q3205   
label values q3205_69 Q3205   
label values q3205_70 Q3205   
label values q3205_71 Q3205   
label values q3205_72 Q3205   
label values q3205_73 Q3205   
label values q3205_74 Q3205   
label values q3205_75 Q3205   
label values q3205_76 Q3205   
label values q3205_77 Q3205   
label values q3205_78 Q3205   
label values q3205_79 Q3205   
label values q3205_80 Q3205   
label values q3205_81 Q3205   
label values q3205_82 Q3205   
label values q3205_83 Q3205   
label values q3205_84 Q3205   
label values q3205_85 Q3205   
label values q3205_86 Q3205   
label values q3205_87 Q3205   
label values q3205_88 Q3205   
label values q3205_89 Q3205   
label values q3205_90 Q3205   
label values q3205_91 Q3205   
label values q3205_92 Q3205   
label values q3205_93 Q3205   
label values q3205_94 Q3205   
label values q3205_95 Q3205   
label values q3205_96 Q3205   
label values q3205_97 Q3205   
label values q3205_98 Q3205   
label values q3205_99 Q3205   
label values q3208_01 Q3208   
label values q3208_02 Q3208   
label values q3208_03 Q3208   
label values q3208_04 Q3208   
label values q3208_05 Q3208   
label values q3208_06 Q3208   
label values q3208_07 Q3208   
label values q3208_08 Q3208   
label values q3208_09 Q3208   
label values q3208_10 Q3208   
label values q3208_11 Q3208   
label values q3208_12 Q3208   
label values q3208_13 Q3208   
label values q3208_14 Q3208   
label values q3208_15 Q3208   
label values q3208_16 Q3208   
label values q3208_17 Q3208   
label values q3208_18 Q3208   
label values q3208_19 Q3208   
label values q3208_20 Q3208   
label values q3208_21 Q3208   
label values q3208_22 Q3208   
label values q3208_23 Q3208   
label values q3208_24 Q3208   
label values q3208_25 Q3208   
label values q3208_26 Q3208   
label values q3208_27 Q3208   
label values q3208_28 Q3208   
label values q3208_29 Q3208   
label values q3208_30 Q3208   
label values q3208_31 Q3208   
label values q3208_32 Q3208   
label values q3208_33 Q3208   
label values q3208_34 Q3208   
label values q3208_35 Q3208   
label values q3208_36 Q3208   
label values q3208_37 Q3208   
label values q3208_38 Q3208   
label values q3208_39 Q3208   
label values q3208_40 Q3208   
label values q3208_41 Q3208   
label values q3208_42 Q3208   
label values q3208_43 Q3208   
label values q3208_44 Q3208   
label values q3208_45 Q3208   
label values q3208_46 Q3208   
label values q3208_47 Q3208   
label values q3208_48 Q3208   
label values q3208_49 Q3208   
label values q3208_50 Q3208   
label values q3208_51 Q3208   
label values q3208_52 Q3208   
label values q3208_53 Q3208   
label values q3208_54 Q3208   
label values q3208_55 Q3208   
label values q3208_56 Q3208   
label values q3208_57 Q3208   
label values q3208_58 Q3208   
label values q3208_59 Q3208   
label values q3208_60 Q3208   
label values q3208_61 Q3208   
label values q3208_62 Q3208   
label values q3208_63 Q3208   
label values q3208_64 Q3208   
label values q3208_65 Q3208   
label values q3208_66 Q3208   
label values q3208_67 Q3208   
label values q3208_68 Q3208   
label values q3208_69 Q3208   
label values q3208_70 Q3208   
label values q3208_71 Q3208   
label values q3208_72 Q3208   
label values q3208_73 Q3208   
label values q3208_74 Q3208   
label values q3208_75 Q3208   
label values q3208_76 Q3208   
label values q3208_77 Q3208   
label values q3208_78 Q3208   
label values q3208_79 Q3208   
label values q3208_80 Q3208   
label values q3208_81 Q3208   
label values q3208_82 Q3208   
label values q3208_83 Q3208   
label values q3208_84 Q3208   
label values q3208_85 Q3208   
label values q3208_86 Q3208   
label values q3208_87 Q3208   
label values q3208_88 Q3208   
label values q3208_89 Q3208   
label values q3208_90 Q3208   
label values q3208_91 Q3208   
label values q3208_92 Q3208   
label values q3208_93 Q3208   
label values q3208_94 Q3208   
label values q3208_95 Q3208   
label values q3208_96 Q3208   
label values q3208_97 Q3208   
label values q3208_98 Q3208   
label values q3208_99 Q3208   
