DATA LIST FILE='C:\Countries\HT7A\HTCS7AFLSP.DAT' RECORDS=1
  /
  FACIL       1-5   
  REC$TYPE    6-6    (A)
  Q32LINE$01    7-8   
  Q32LINE$02    9-10  
  Q32LINE$03   11-12  
  Q32LINE$04   13-14  
  Q32LINE$05   15-16  
  Q32LINE$06   17-18  
  Q32LINE$07   19-20  
  Q32LINE$08   21-22  
  Q32LINE$09   23-24  
  Q32LINE$10   25-26  
  Q32LINE$11   27-28  
  Q32LINE$12   29-30  
  Q32LINE$13   31-32  
  Q32LINE$14   33-34  
  Q32LINE$15   35-36  
  Q32LINE$16   37-38  
  Q32LINE$17   39-40  
  Q32LINE$18   41-42  
  Q32LINE$19   43-44  
  Q32LINE$20   45-46  
  Q32LINE$21   47-48  
  Q32LINE$22   49-50  
  Q32LINE$23   51-52  
  Q32LINE$24   53-54  
  Q32LINE$25   55-56  
  Q32LINE$26   57-58  
  Q32LINE$27   59-60  
  Q32LINE$28   61-62  
  Q32LINE$29   63-64  
  Q32LINE$30   65-66  
  Q32LINE$31   67-68  
  Q32LINE$32   69-70  
  Q32LINE$33   71-72  
  Q32LINE$34   73-74  
  Q32LINE$35   75-76  
  Q32LINE$36   77-78  
  Q32LINE$37   79-80  
  Q32LINE$38   81-82  
  Q32LINE$39   83-84  
  Q32LINE$40   85-86  
  Q32LINE$41   87-88  
  Q32LINE$42   89-90  
  Q32LINE$43   91-92  
  Q32LINE$44   93-94  
  Q32LINE$45   95-96  
  Q32LINE$46   97-98  
  Q32LINE$47   99-100 
  Q32LINE$48  101-102 
  Q32LINE$49  103-104 
  Q32LINE$50  105-106 
  Q32LINE$51  107-108 
  Q32LINE$52  109-110 
  Q32LINE$53  111-112 
  Q32LINE$54  113-114 
  Q32LINE$55  115-116 
  Q32LINE$56  117-118 
  Q32LINE$57  119-120 
  Q32LINE$58  121-122 
  Q32LINE$59  123-124 
  Q32LINE$60  125-126 
  Q32LINE$61  127-128 
  Q32LINE$62  129-130 
  Q32LINE$63  131-132 
  Q32LINE$64  133-134 
  Q32LINE$65  135-136 
  Q32LINE$66  137-138 
  Q32LINE$67  139-140 
  Q32LINE$68  141-142 
  Q32LINE$69  143-144 
  Q32LINE$70  145-146 
  Q32LINE$71  147-148 
  Q32LINE$72  149-150 
  Q32LINE$73  151-152 
  Q32LINE$74  153-154 
  Q32LINE$75  155-156 
  Q32LINE$76  157-158 
  Q32LINE$77  159-160 
  Q32LINE$78  161-162 
  Q32LINE$79  163-164 
  Q32LINE$80  165-166 
  Q32LINE$81  167-168 
  Q32LINE$82  169-170 
  Q32LINE$83  171-172 
  Q32LINE$84  173-174 
  Q32LINE$85  175-176 
  Q32LINE$86  177-178 
  Q32LINE$87  179-180 
  Q32LINE$88  181-182 
  Q32LINE$89  183-184 
  Q32LINE$90  185-186 
  Q32LINE$91  187-188 
  Q32LINE$92  189-190 
  Q32LINE$93  191-192 
  Q32LINE$94  193-194 
  Q32LINE$95  195-196 
  Q32LINE$96  197-198 
  Q32LINE$97  199-200 
  Q32LINE$98  201-202 
  Q32LINE$99  203-204 
  Q3203$01  205-205 
  Q3203$02  206-206 
  Q3203$03  207-207 
  Q3203$04  208-208 
  Q3203$05  209-209 
  Q3203$06  210-210 
  Q3203$07  211-211 
  Q3203$08  212-212 
  Q3203$09  213-213 
  Q3203$10  214-214 
  Q3203$11  215-215 
  Q3203$12  216-216 
  Q3203$13  217-217 
  Q3203$14  218-218 
  Q3203$15  219-219 
  Q3203$16  220-220 
  Q3203$17  221-221 
  Q3203$18  222-222 
  Q3203$19  223-223 
  Q3203$20  224-224 
  Q3203$21  225-225 
  Q3203$22  226-226 
  Q3203$23  227-227 
  Q3203$24  228-228 
  Q3203$25  229-229 
  Q3203$26  230-230 
  Q3203$27  231-231 
  Q3203$28  232-232 
  Q3203$29  233-233 
  Q3203$30  234-234 
  Q3203$31  235-235 
  Q3203$32  236-236 
  Q3203$33  237-237 
  Q3203$34  238-238 
  Q3203$35  239-239 
  Q3203$36  240-240 
  Q3203$37  241-241 
  Q3203$38  242-242 
  Q3203$39  243-243 
  Q3203$40  244-244 
  Q3203$41  245-245 
  Q3203$42  246-246 
  Q3203$43  247-247 
  Q3203$44  248-248 
  Q3203$45  249-249 
  Q3203$46  250-250 
  Q3203$47  251-251 
  Q3203$48  252-252 
  Q3203$49  253-253 
  Q3203$50  254-254 
  Q3203$51  255-255 
  Q3203$52  256-256 
  Q3203$53  257-257 
  Q3203$54  258-258 
  Q3203$55  259-259 
  Q3203$56  260-260 
  Q3203$57  261-261 
  Q3203$58  262-262 
  Q3203$59  263-263 
  Q3203$60  264-264 
  Q3203$61  265-265 
  Q3203$62  266-266 
  Q3203$63  267-267 
  Q3203$64  268-268 
  Q3203$65  269-269 
  Q3203$66  270-270 
  Q3203$67  271-271 
  Q3203$68  272-272 
  Q3203$69  273-273 
  Q3203$70  274-274 
  Q3203$71  275-275 
  Q3203$72  276-276 
  Q3203$73  277-277 
  Q3203$74  278-278 
  Q3203$75  279-279 
  Q3203$76  280-280 
  Q3203$77  281-281 
  Q3203$78  282-282 
  Q3203$79  283-283 
  Q3203$80  284-284 
  Q3203$81  285-285 
  Q3203$82  286-286 
  Q3203$83  287-287 
  Q3203$84  288-288 
  Q3203$85  289-289 
  Q3203$86  290-290 
  Q3203$87  291-291 
  Q3203$88  292-292 
  Q3203$89  293-293 
  Q3203$90  294-294 
  Q3203$91  295-295 
  Q3203$92  296-296 
  Q3203$93  297-297 
  Q3203$94  298-298 
  Q3203$95  299-299 
  Q3203$96  300-300 
  Q3203$97  301-301 
  Q3203$98  302-302 
  Q3203$99  303-303 
  Q3204$01  304-304 
  Q3204$02  305-305 
  Q3204$03  306-306 
  Q3204$04  307-307 
  Q3204$05  308-308 
  Q3204$06  309-309 
  Q3204$07  310-310 
  Q3204$08  311-311 
  Q3204$09  312-312 
  Q3204$10  313-313 
  Q3204$11  314-314 
  Q3204$12  315-315 
  Q3204$13  316-316 
  Q3204$14  317-317 
  Q3204$15  318-318 
  Q3204$16  319-319 
  Q3204$17  320-320 
  Q3204$18  321-321 
  Q3204$19  322-322 
  Q3204$20  323-323 
  Q3204$21  324-324 
  Q3204$22  325-325 
  Q3204$23  326-326 
  Q3204$24  327-327 
  Q3204$25  328-328 
  Q3204$26  329-329 
  Q3204$27  330-330 
  Q3204$28  331-331 
  Q3204$29  332-332 
  Q3204$30  333-333 
  Q3204$31  334-334 
  Q3204$32  335-335 
  Q3204$33  336-336 
  Q3204$34  337-337 
  Q3204$35  338-338 
  Q3204$36  339-339 
  Q3204$37  340-340 
  Q3204$38  341-341 
  Q3204$39  342-342 
  Q3204$40  343-343 
  Q3204$41  344-344 
  Q3204$42  345-345 
  Q3204$43  346-346 
  Q3204$44  347-347 
  Q3204$45  348-348 
  Q3204$46  349-349 
  Q3204$47  350-350 
  Q3204$48  351-351 
  Q3204$49  352-352 
  Q3204$50  353-353 
  Q3204$51  354-354 
  Q3204$52  355-355 
  Q3204$53  356-356 
  Q3204$54  357-357 
  Q3204$55  358-358 
  Q3204$56  359-359 
  Q3204$57  360-360 
  Q3204$58  361-361 
  Q3204$59  362-362 
  Q3204$60  363-363 
  Q3204$61  364-364 
  Q3204$62  365-365 
  Q3204$63  366-366 
  Q3204$64  367-367 
  Q3204$65  368-368 
  Q3204$66  369-369 
  Q3204$67  370-370 
  Q3204$68  371-371 
  Q3204$69  372-372 
  Q3204$70  373-373 
  Q3204$71  374-374 
  Q3204$72  375-375 
  Q3204$73  376-376 
  Q3204$74  377-377 
  Q3204$75  378-378 
  Q3204$76  379-379 
  Q3204$77  380-380 
  Q3204$78  381-381 
  Q3204$79  382-382 
  Q3204$80  383-383 
  Q3204$81  384-384 
  Q3204$82  385-385 
  Q3204$83  386-386 
  Q3204$84  387-387 
  Q3204$85  388-388 
  Q3204$86  389-389 
  Q3204$87  390-390 
  Q3204$88  391-391 
  Q3204$89  392-392 
  Q3204$90  393-393 
  Q3204$91  394-394 
  Q3204$92  395-395 
  Q3204$93  396-396 
  Q3204$94  397-397 
  Q3204$95  398-398 
  Q3204$96  399-399 
  Q3204$97  400-400 
  Q3204$98  401-401 
  Q3204$99  402-402 
  Q3205$01  403-403 
  Q3205$02  404-404 
  Q3205$03  405-405 
  Q3205$04  406-406 
  Q3205$05  407-407 
  Q3205$06  408-408 
  Q3205$07  409-409 
  Q3205$08  410-410 
  Q3205$09  411-411 
  Q3205$10  412-412 
  Q3205$11  413-413 
  Q3205$12  414-414 
  Q3205$13  415-415 
  Q3205$14  416-416 
  Q3205$15  417-417 
  Q3205$16  418-418 
  Q3205$17  419-419 
  Q3205$18  420-420 
  Q3205$19  421-421 
  Q3205$20  422-422 
  Q3205$21  423-423 
  Q3205$22  424-424 
  Q3205$23  425-425 
  Q3205$24  426-426 
  Q3205$25  427-427 
  Q3205$26  428-428 
  Q3205$27  429-429 
  Q3205$28  430-430 
  Q3205$29  431-431 
  Q3205$30  432-432 
  Q3205$31  433-433 
  Q3205$32  434-434 
  Q3205$33  435-435 
  Q3205$34  436-436 
  Q3205$35  437-437 
  Q3205$36  438-438 
  Q3205$37  439-439 
  Q3205$38  440-440 
  Q3205$39  441-441 
  Q3205$40  442-442 
  Q3205$41  443-443 
  Q3205$42  444-444 
  Q3205$43  445-445 
  Q3205$44  446-446 
  Q3205$45  447-447 
  Q3205$46  448-448 
  Q3205$47  449-449 
  Q3205$48  450-450 
  Q3205$49  451-451 
  Q3205$50  452-452 
  Q3205$51  453-453 
  Q3205$52  454-454 
  Q3205$53  455-455 
  Q3205$54  456-456 
  Q3205$55  457-457 
  Q3205$56  458-458 
  Q3205$57  459-459 
  Q3205$58  460-460 
  Q3205$59  461-461 
  Q3205$60  462-462 
  Q3205$61  463-463 
  Q3205$62  464-464 
  Q3205$63  465-465 
  Q3205$64  466-466 
  Q3205$65  467-467 
  Q3205$66  468-468 
  Q3205$67  469-469 
  Q3205$68  470-470 
  Q3205$69  471-471 
  Q3205$70  472-472 
  Q3205$71  473-473 
  Q3205$72  474-474 
  Q3205$73  475-475 
  Q3205$74  476-476 
  Q3205$75  477-477 
  Q3205$76  478-478 
  Q3205$77  479-479 
  Q3205$78  480-480 
  Q3205$79  481-481 
  Q3205$80  482-482 
  Q3205$81  483-483 
  Q3205$82  484-484 
  Q3205$83  485-485 
  Q3205$84  486-486 
  Q3205$85  487-487 
  Q3205$86  488-488 
  Q3205$87  489-489 
  Q3205$88  490-490 
  Q3205$89  491-491 
  Q3205$90  492-492 
  Q3205$91  493-493 
  Q3205$92  494-494 
  Q3205$93  495-495 
  Q3205$94  496-496 
  Q3205$95  497-497 
  Q3205$96  498-498 
  Q3205$97  499-499 
  Q3205$98  500-500 
  Q3205$99  501-501 
  Q3208$01  502-505 
  Q3208$02  506-509 
  Q3208$03  510-513 
  Q3208$04  514-517 
  Q3208$05  518-521 
  Q3208$06  522-525 
  Q3208$07  526-529 
  Q3208$08  530-533 
  Q3208$09  534-537 
  Q3208$10  538-541 
  Q3208$11  542-545 
  Q3208$12  546-549 
  Q3208$13  550-553 
  Q3208$14  554-557 
  Q3208$15  558-561 
  Q3208$16  562-565 
  Q3208$17  566-569 
  Q3208$18  570-573 
  Q3208$19  574-577 
  Q3208$20  578-581 
  Q3208$21  582-585 
  Q3208$22  586-589 
  Q3208$23  590-593 
  Q3208$24  594-597 
  Q3208$25  598-601 
  Q3208$26  602-605 
  Q3208$27  606-609 
  Q3208$28  610-613 
  Q3208$29  614-617 
  Q3208$30  618-621 
  Q3208$31  622-625 
  Q3208$32  626-629 
  Q3208$33  630-633 
  Q3208$34  634-637 
  Q3208$35  638-641 
  Q3208$36  642-645 
  Q3208$37  646-649 
  Q3208$38  650-653 
  Q3208$39  654-657 
  Q3208$40  658-661 
  Q3208$41  662-665 
  Q3208$42  666-669 
  Q3208$43  670-673 
  Q3208$44  674-677 
  Q3208$45  678-681 
  Q3208$46  682-685 
  Q3208$47  686-689 
  Q3208$48  690-693 
  Q3208$49  694-697 
  Q3208$50  698-701 
  Q3208$51  702-705 
  Q3208$52  706-709 
  Q3208$53  710-713 
  Q3208$54  714-717 
  Q3208$55  718-721 
  Q3208$56  722-725 
  Q3208$57  726-729 
  Q3208$58  730-733 
  Q3208$59  734-737 
  Q3208$60  738-741 
  Q3208$61  742-745 
  Q3208$62  746-749 
  Q3208$63  750-753 
  Q3208$64  754-757 
  Q3208$65  758-761 
  Q3208$66  762-765 
  Q3208$67  766-769 
  Q3208$68  770-773 
  Q3208$69  774-777 
  Q3208$70  778-781 
  Q3208$71  782-785 
  Q3208$72  786-789 
  Q3208$73  790-793 
  Q3208$74  794-797 
  Q3208$75  798-801 
  Q3208$76  802-805 
  Q3208$77  806-809 
  Q3208$78  810-813 
  Q3208$79  814-817 
  Q3208$80  818-821 
  Q3208$81  822-825 
  Q3208$82  826-829 
  Q3208$83  830-833 
  Q3208$84  834-837 
  Q3208$85  838-841 
  Q3208$86  842-845 
  Q3208$87  846-849 
  Q3208$88  850-853 
  Q3208$89  854-857 
  Q3208$90  858-861 
  Q3208$91  862-865 
  Q3208$92  866-869 
  Q3208$93  870-873 
  Q3208$94  874-877 
  Q3208$95  878-881 
  Q3208$96  882-885 
  Q3208$97  886-889 
  Q3208$98  890-893 
  Q3208$99  894-897 
 .
VARIABLE LABELS
   FACIL    "Facility identification"
  /Q32LINE$01 "Line number"
  /Q32LINE$02 "Line number"
  /Q32LINE$03 "Line number"
  /Q32LINE$04 "Line number"
  /Q32LINE$05 "Line number"
  /Q32LINE$06 "Line number"
  /Q32LINE$07 "Line number"
  /Q32LINE$08 "Line number"
  /Q32LINE$09 "Line number"
  /Q32LINE$10 "Line number"
  /Q32LINE$11 "Line number"
  /Q32LINE$12 "Line number"
  /Q32LINE$13 "Line number"
  /Q32LINE$14 "Line number"
  /Q32LINE$15 "Line number"
  /Q32LINE$16 "Line number"
  /Q32LINE$17 "Line number"
  /Q32LINE$18 "Line number"
  /Q32LINE$19 "Line number"
  /Q32LINE$20 "Line number"
  /Q32LINE$21 "Line number"
  /Q32LINE$22 "Line number"
  /Q32LINE$23 "Line number"
  /Q32LINE$24 "Line number"
  /Q32LINE$25 "Line number"
  /Q32LINE$26 "Line number"
  /Q32LINE$27 "Line number"
  /Q32LINE$28 "Line number"
  /Q32LINE$29 "Line number"
  /Q32LINE$30 "Line number"
  /Q32LINE$31 "Line number"
  /Q32LINE$32 "Line number"
  /Q32LINE$33 "Line number"
  /Q32LINE$34 "Line number"
  /Q32LINE$35 "Line number"
  /Q32LINE$36 "Line number"
  /Q32LINE$37 "Line number"
  /Q32LINE$38 "Line number"
  /Q32LINE$39 "Line number"
  /Q32LINE$40 "Line number"
  /Q32LINE$41 "Line number"
  /Q32LINE$42 "Line number"
  /Q32LINE$43 "Line number"
  /Q32LINE$44 "Line number"
  /Q32LINE$45 "Line number"
  /Q32LINE$46 "Line number"
  /Q32LINE$47 "Line number"
  /Q32LINE$48 "Line number"
  /Q32LINE$49 "Line number"
  /Q32LINE$50 "Line number"
  /Q32LINE$51 "Line number"
  /Q32LINE$52 "Line number"
  /Q32LINE$53 "Line number"
  /Q32LINE$54 "Line number"
  /Q32LINE$55 "Line number"
  /Q32LINE$56 "Line number"
  /Q32LINE$57 "Line number"
  /Q32LINE$58 "Line number"
  /Q32LINE$59 "Line number"
  /Q32LINE$60 "Line number"
  /Q32LINE$61 "Line number"
  /Q32LINE$62 "Line number"
  /Q32LINE$63 "Line number"
  /Q32LINE$64 "Line number"
  /Q32LINE$65 "Line number"
  /Q32LINE$66 "Line number"
  /Q32LINE$67 "Line number"
  /Q32LINE$68 "Line number"
  /Q32LINE$69 "Line number"
  /Q32LINE$70 "Line number"
  /Q32LINE$71 "Line number"
  /Q32LINE$72 "Line number"
  /Q32LINE$73 "Line number"
  /Q32LINE$74 "Line number"
  /Q32LINE$75 "Line number"
  /Q32LINE$76 "Line number"
  /Q32LINE$77 "Line number"
  /Q32LINE$78 "Line number"
  /Q32LINE$79 "Line number"
  /Q32LINE$80 "Line number"
  /Q32LINE$81 "Line number"
  /Q32LINE$82 "Line number"
  /Q32LINE$83 "Line number"
  /Q32LINE$84 "Line number"
  /Q32LINE$85 "Line number"
  /Q32LINE$86 "Line number"
  /Q32LINE$87 "Line number"
  /Q32LINE$88 "Line number"
  /Q32LINE$89 "Line number"
  /Q32LINE$90 "Line number"
  /Q32LINE$91 "Line number"
  /Q32LINE$92 "Line number"
  /Q32LINE$93 "Line number"
  /Q32LINE$94 "Line number"
  /Q32LINE$95 "Line number"
  /Q32LINE$96 "Line number"
  /Q32LINE$97 "Line number"
  /Q32LINE$98 "Line number"
  /Q32LINE$99 "Line number"
  /Q3203$01 "Sex"
  /Q3203$02 "Sex"
  /Q3203$03 "Sex"
  /Q3203$04 "Sex"
  /Q3203$05 "Sex"
  /Q3203$06 "Sex"
  /Q3203$07 "Sex"
  /Q3203$08 "Sex"
  /Q3203$09 "Sex"
  /Q3203$10 "Sex"
  /Q3203$11 "Sex"
  /Q3203$12 "Sex"
  /Q3203$13 "Sex"
  /Q3203$14 "Sex"
  /Q3203$15 "Sex"
  /Q3203$16 "Sex"
  /Q3203$17 "Sex"
  /Q3203$18 "Sex"
  /Q3203$19 "Sex"
  /Q3203$20 "Sex"
  /Q3203$21 "Sex"
  /Q3203$22 "Sex"
  /Q3203$23 "Sex"
  /Q3203$24 "Sex"
  /Q3203$25 "Sex"
  /Q3203$26 "Sex"
  /Q3203$27 "Sex"
  /Q3203$28 "Sex"
  /Q3203$29 "Sex"
  /Q3203$30 "Sex"
  /Q3203$31 "Sex"
  /Q3203$32 "Sex"
  /Q3203$33 "Sex"
  /Q3203$34 "Sex"
  /Q3203$35 "Sex"
  /Q3203$36 "Sex"
  /Q3203$37 "Sex"
  /Q3203$38 "Sex"
  /Q3203$39 "Sex"
  /Q3203$40 "Sex"
  /Q3203$41 "Sex"
  /Q3203$42 "Sex"
  /Q3203$43 "Sex"
  /Q3203$44 "Sex"
  /Q3203$45 "Sex"
  /Q3203$46 "Sex"
  /Q3203$47 "Sex"
  /Q3203$48 "Sex"
  /Q3203$49 "Sex"
  /Q3203$50 "Sex"
  /Q3203$51 "Sex"
  /Q3203$52 "Sex"
  /Q3203$53 "Sex"
  /Q3203$54 "Sex"
  /Q3203$55 "Sex"
  /Q3203$56 "Sex"
  /Q3203$57 "Sex"
  /Q3203$58 "Sex"
  /Q3203$59 "Sex"
  /Q3203$60 "Sex"
  /Q3203$61 "Sex"
  /Q3203$62 "Sex"
  /Q3203$63 "Sex"
  /Q3203$64 "Sex"
  /Q3203$65 "Sex"
  /Q3203$66 "Sex"
  /Q3203$67 "Sex"
  /Q3203$68 "Sex"
  /Q3203$69 "Sex"
  /Q3203$70 "Sex"
  /Q3203$71 "Sex"
  /Q3203$72 "Sex"
  /Q3203$73 "Sex"
  /Q3203$74 "Sex"
  /Q3203$75 "Sex"
  /Q3203$76 "Sex"
  /Q3203$77 "Sex"
  /Q3203$78 "Sex"
  /Q3203$79 "Sex"
  /Q3203$80 "Sex"
  /Q3203$81 "Sex"
  /Q3203$82 "Sex"
  /Q3203$83 "Sex"
  /Q3203$84 "Sex"
  /Q3203$85 "Sex"
  /Q3203$86 "Sex"
  /Q3203$87 "Sex"
  /Q3203$88 "Sex"
  /Q3203$89 "Sex"
  /Q3203$90 "Sex"
  /Q3203$91 "Sex"
  /Q3203$92 "Sex"
  /Q3203$93 "Sex"
  /Q3203$94 "Sex"
  /Q3203$95 "Sex"
  /Q3203$96 "Sex"
  /Q3203$97 "Sex"
  /Q3203$98 "Sex"
  /Q3203$99 "Sex"
  /Q3204$01 "Education level"
  /Q3204$02 "Education level"
  /Q3204$03 "Education level"
  /Q3204$04 "Education level"
  /Q3204$05 "Education level"
  /Q3204$06 "Education level"
  /Q3204$07 "Education level"
  /Q3204$08 "Education level"
  /Q3204$09 "Education level"
  /Q3204$10 "Education level"
  /Q3204$11 "Education level"
  /Q3204$12 "Education level"
  /Q3204$13 "Education level"
  /Q3204$14 "Education level"
  /Q3204$15 "Education level"
  /Q3204$16 "Education level"
  /Q3204$17 "Education level"
  /Q3204$18 "Education level"
  /Q3204$19 "Education level"
  /Q3204$20 "Education level"
  /Q3204$21 "Education level"
  /Q3204$22 "Education level"
  /Q3204$23 "Education level"
  /Q3204$24 "Education level"
  /Q3204$25 "Education level"
  /Q3204$26 "Education level"
  /Q3204$27 "Education level"
  /Q3204$28 "Education level"
  /Q3204$29 "Education level"
  /Q3204$30 "Education level"
  /Q3204$31 "Education level"
  /Q3204$32 "Education level"
  /Q3204$33 "Education level"
  /Q3204$34 "Education level"
  /Q3204$35 "Education level"
  /Q3204$36 "Education level"
  /Q3204$37 "Education level"
  /Q3204$38 "Education level"
  /Q3204$39 "Education level"
  /Q3204$40 "Education level"
  /Q3204$41 "Education level"
  /Q3204$42 "Education level"
  /Q3204$43 "Education level"
  /Q3204$44 "Education level"
  /Q3204$45 "Education level"
  /Q3204$46 "Education level"
  /Q3204$47 "Education level"
  /Q3204$48 "Education level"
  /Q3204$49 "Education level"
  /Q3204$50 "Education level"
  /Q3204$51 "Education level"
  /Q3204$52 "Education level"
  /Q3204$53 "Education level"
  /Q3204$54 "Education level"
  /Q3204$55 "Education level"
  /Q3204$56 "Education level"
  /Q3204$57 "Education level"
  /Q3204$58 "Education level"
  /Q3204$59 "Education level"
  /Q3204$60 "Education level"
  /Q3204$61 "Education level"
  /Q3204$62 "Education level"
  /Q3204$63 "Education level"
  /Q3204$64 "Education level"
  /Q3204$65 "Education level"
  /Q3204$66 "Education level"
  /Q3204$67 "Education level"
  /Q3204$68 "Education level"
  /Q3204$69 "Education level"
  /Q3204$70 "Education level"
  /Q3204$71 "Education level"
  /Q3204$72 "Education level"
  /Q3204$73 "Education level"
  /Q3204$74 "Education level"
  /Q3204$75 "Education level"
  /Q3204$76 "Education level"
  /Q3204$77 "Education level"
  /Q3204$78 "Education level"
  /Q3204$79 "Education level"
  /Q3204$80 "Education level"
  /Q3204$81 "Education level"
  /Q3204$82 "Education level"
  /Q3204$83 "Education level"
  /Q3204$84 "Education level"
  /Q3204$85 "Education level"
  /Q3204$86 "Education level"
  /Q3204$87 "Education level"
  /Q3204$88 "Education level"
  /Q3204$89 "Education level"
  /Q3204$90 "Education level"
  /Q3204$91 "Education level"
  /Q3204$92 "Education level"
  /Q3204$93 "Education level"
  /Q3204$94 "Education level"
  /Q3204$95 "Education level"
  /Q3204$96 "Education level"
  /Q3204$97 "Education level"
  /Q3204$98 "Education level"
  /Q3204$99 "Education level"
  /Q3205$01 "Agent type"
  /Q3205$02 "Agent type"
  /Q3205$03 "Agent type"
  /Q3205$04 "Agent type"
  /Q3205$05 "Agent type"
  /Q3205$06 "Agent type"
  /Q3205$07 "Agent type"
  /Q3205$08 "Agent type"
  /Q3205$09 "Agent type"
  /Q3205$10 "Agent type"
  /Q3205$11 "Agent type"
  /Q3205$12 "Agent type"
  /Q3205$13 "Agent type"
  /Q3205$14 "Agent type"
  /Q3205$15 "Agent type"
  /Q3205$16 "Agent type"
  /Q3205$17 "Agent type"
  /Q3205$18 "Agent type"
  /Q3205$19 "Agent type"
  /Q3205$20 "Agent type"
  /Q3205$21 "Agent type"
  /Q3205$22 "Agent type"
  /Q3205$23 "Agent type"
  /Q3205$24 "Agent type"
  /Q3205$25 "Agent type"
  /Q3205$26 "Agent type"
  /Q3205$27 "Agent type"
  /Q3205$28 "Agent type"
  /Q3205$29 "Agent type"
  /Q3205$30 "Agent type"
  /Q3205$31 "Agent type"
  /Q3205$32 "Agent type"
  /Q3205$33 "Agent type"
  /Q3205$34 "Agent type"
  /Q3205$35 "Agent type"
  /Q3205$36 "Agent type"
  /Q3205$37 "Agent type"
  /Q3205$38 "Agent type"
  /Q3205$39 "Agent type"
  /Q3205$40 "Agent type"
  /Q3205$41 "Agent type"
  /Q3205$42 "Agent type"
  /Q3205$43 "Agent type"
  /Q3205$44 "Agent type"
  /Q3205$45 "Agent type"
  /Q3205$46 "Agent type"
  /Q3205$47 "Agent type"
  /Q3205$48 "Agent type"
  /Q3205$49 "Agent type"
  /Q3205$50 "Agent type"
  /Q3205$51 "Agent type"
  /Q3205$52 "Agent type"
  /Q3205$53 "Agent type"
  /Q3205$54 "Agent type"
  /Q3205$55 "Agent type"
  /Q3205$56 "Agent type"
  /Q3205$57 "Agent type"
  /Q3205$58 "Agent type"
  /Q3205$59 "Agent type"
  /Q3205$60 "Agent type"
  /Q3205$61 "Agent type"
  /Q3205$62 "Agent type"
  /Q3205$63 "Agent type"
  /Q3205$64 "Agent type"
  /Q3205$65 "Agent type"
  /Q3205$66 "Agent type"
  /Q3205$67 "Agent type"
  /Q3205$68 "Agent type"
  /Q3205$69 "Agent type"
  /Q3205$70 "Agent type"
  /Q3205$71 "Agent type"
  /Q3205$72 "Agent type"
  /Q3205$73 "Agent type"
  /Q3205$74 "Agent type"
  /Q3205$75 "Agent type"
  /Q3205$76 "Agent type"
  /Q3205$77 "Agent type"
  /Q3205$78 "Agent type"
  /Q3205$79 "Agent type"
  /Q3205$80 "Agent type"
  /Q3205$81 "Agent type"
  /Q3205$82 "Agent type"
  /Q3205$83 "Agent type"
  /Q3205$84 "Agent type"
  /Q3205$85 "Agent type"
  /Q3205$86 "Agent type"
  /Q3205$87 "Agent type"
  /Q3205$88 "Agent type"
  /Q3205$89 "Agent type"
  /Q3205$90 "Agent type"
  /Q3205$91 "Agent type"
  /Q3205$92 "Agent type"
  /Q3205$93 "Agent type"
  /Q3205$94 "Agent type"
  /Q3205$95 "Agent type"
  /Q3205$96 "Agent type"
  /Q3205$97 "Agent type"
  /Q3205$98 "Agent type"
  /Q3205$99 "Agent type"
  /Q3208$01 "Year started to work"
  /Q3208$02 "Year started to work"
  /Q3208$03 "Year started to work"
  /Q3208$04 "Year started to work"
  /Q3208$05 "Year started to work"
  /Q3208$06 "Year started to work"
  /Q3208$07 "Year started to work"
  /Q3208$08 "Year started to work"
  /Q3208$09 "Year started to work"
  /Q3208$10 "Year started to work"
  /Q3208$11 "Year started to work"
  /Q3208$12 "Year started to work"
  /Q3208$13 "Year started to work"
  /Q3208$14 "Year started to work"
  /Q3208$15 "Year started to work"
  /Q3208$16 "Year started to work"
  /Q3208$17 "Year started to work"
  /Q3208$18 "Year started to work"
  /Q3208$19 "Year started to work"
  /Q3208$20 "Year started to work"
  /Q3208$21 "Year started to work"
  /Q3208$22 "Year started to work"
  /Q3208$23 "Year started to work"
  /Q3208$24 "Year started to work"
  /Q3208$25 "Year started to work"
  /Q3208$26 "Year started to work"
  /Q3208$27 "Year started to work"
  /Q3208$28 "Year started to work"
  /Q3208$29 "Year started to work"
  /Q3208$30 "Year started to work"
  /Q3208$31 "Year started to work"
  /Q3208$32 "Year started to work"
  /Q3208$33 "Year started to work"
  /Q3208$34 "Year started to work"
  /Q3208$35 "Year started to work"
  /Q3208$36 "Year started to work"
  /Q3208$37 "Year started to work"
  /Q3208$38 "Year started to work"
  /Q3208$39 "Year started to work"
  /Q3208$40 "Year started to work"
  /Q3208$41 "Year started to work"
  /Q3208$42 "Year started to work"
  /Q3208$43 "Year started to work"
  /Q3208$44 "Year started to work"
  /Q3208$45 "Year started to work"
  /Q3208$46 "Year started to work"
  /Q3208$47 "Year started to work"
  /Q3208$48 "Year started to work"
  /Q3208$49 "Year started to work"
  /Q3208$50 "Year started to work"
  /Q3208$51 "Year started to work"
  /Q3208$52 "Year started to work"
  /Q3208$53 "Year started to work"
  /Q3208$54 "Year started to work"
  /Q3208$55 "Year started to work"
  /Q3208$56 "Year started to work"
  /Q3208$57 "Year started to work"
  /Q3208$58 "Year started to work"
  /Q3208$59 "Year started to work"
  /Q3208$60 "Year started to work"
  /Q3208$61 "Year started to work"
  /Q3208$62 "Year started to work"
  /Q3208$63 "Year started to work"
  /Q3208$64 "Year started to work"
  /Q3208$65 "Year started to work"
  /Q3208$66 "Year started to work"
  /Q3208$67 "Year started to work"
  /Q3208$68 "Year started to work"
  /Q3208$69 "Year started to work"
  /Q3208$70 "Year started to work"
  /Q3208$71 "Year started to work"
  /Q3208$72 "Year started to work"
  /Q3208$73 "Year started to work"
  /Q3208$74 "Year started to work"
  /Q3208$75 "Year started to work"
  /Q3208$76 "Year started to work"
  /Q3208$77 "Year started to work"
  /Q3208$78 "Year started to work"
  /Q3208$79 "Year started to work"
  /Q3208$80 "Year started to work"
  /Q3208$81 "Year started to work"
  /Q3208$82 "Year started to work"
  /Q3208$83 "Year started to work"
  /Q3208$84 "Year started to work"
  /Q3208$85 "Year started to work"
  /Q3208$86 "Year started to work"
  /Q3208$87 "Year started to work"
  /Q3208$88 "Year started to work"
  /Q3208$89 "Year started to work"
  /Q3208$90 "Year started to work"
  /Q3208$91 "Year started to work"
  /Q3208$92 "Year started to work"
  /Q3208$93 "Year started to work"
  /Q3208$94 "Year started to work"
  /Q3208$95 "Year started to work"
  /Q3208$96 "Year started to work"
  /Q3208$97 "Year started to work"
  /Q3208$98 "Year started to work"
  /Q3208$99 "Year started to work"
 .
VALUE LABELS
   Q3203$01
      1 "Homme"
      2 "Femme"
  /Q3203$02
      1 "Homme"
      2 "Femme"
  /Q3203$03
      1 "Homme"
      2 "Femme"
  /Q3203$04
      1 "Homme"
      2 "Femme"
  /Q3203$05
      1 "Homme"
      2 "Femme"
  /Q3203$06
      1 "Homme"
      2 "Femme"
  /Q3203$07
      1 "Homme"
      2 "Femme"
  /Q3203$08
      1 "Homme"
      2 "Femme"
  /Q3203$09
      1 "Homme"
      2 "Femme"
  /Q3203$10
      1 "Homme"
      2 "Femme"
  /Q3203$11
      1 "Homme"
      2 "Femme"
  /Q3203$12
      1 "Homme"
      2 "Femme"
  /Q3203$13
      1 "Homme"
      2 "Femme"
  /Q3203$14
      1 "Homme"
      2 "Femme"
  /Q3203$15
      1 "Homme"
      2 "Femme"
  /Q3203$16
      1 "Homme"
      2 "Femme"
  /Q3203$17
      1 "Homme"
      2 "Femme"
  /Q3203$18
      1 "Homme"
      2 "Femme"
  /Q3203$19
      1 "Homme"
      2 "Femme"
  /Q3203$20
      1 "Homme"
      2 "Femme"
  /Q3203$21
      1 "Homme"
      2 "Femme"
  /Q3203$22
      1 "Homme"
      2 "Femme"
  /Q3203$23
      1 "Homme"
      2 "Femme"
  /Q3203$24
      1 "Homme"
      2 "Femme"
  /Q3203$25
      1 "Homme"
      2 "Femme"
  /Q3203$26
      1 "Homme"
      2 "Femme"
  /Q3203$27
      1 "Homme"
      2 "Femme"
  /Q3203$28
      1 "Homme"
      2 "Femme"
  /Q3203$29
      1 "Homme"
      2 "Femme"
  /Q3203$30
      1 "Homme"
      2 "Femme"
  /Q3203$31
      1 "Homme"
      2 "Femme"
  /Q3203$32
      1 "Homme"
      2 "Femme"
  /Q3203$33
      1 "Homme"
      2 "Femme"
  /Q3203$34
      1 "Homme"
      2 "Femme"
  /Q3203$35
      1 "Homme"
      2 "Femme"
  /Q3203$36
      1 "Homme"
      2 "Femme"
  /Q3203$37
      1 "Homme"
      2 "Femme"
  /Q3203$38
      1 "Homme"
      2 "Femme"
  /Q3203$39
      1 "Homme"
      2 "Femme"
  /Q3203$40
      1 "Homme"
      2 "Femme"
  /Q3203$41
      1 "Homme"
      2 "Femme"
  /Q3203$42
      1 "Homme"
      2 "Femme"
  /Q3203$43
      1 "Homme"
      2 "Femme"
  /Q3203$44
      1 "Homme"
      2 "Femme"
  /Q3203$45
      1 "Homme"
      2 "Femme"
  /Q3203$46
      1 "Homme"
      2 "Femme"
  /Q3203$47
      1 "Homme"
      2 "Femme"
  /Q3203$48
      1 "Homme"
      2 "Femme"
  /Q3203$49
      1 "Homme"
      2 "Femme"
  /Q3203$50
      1 "Homme"
      2 "Femme"
  /Q3203$51
      1 "Homme"
      2 "Femme"
  /Q3203$52
      1 "Homme"
      2 "Femme"
  /Q3203$53
      1 "Homme"
      2 "Femme"
  /Q3203$54
      1 "Homme"
      2 "Femme"
  /Q3203$55
      1 "Homme"
      2 "Femme"
  /Q3203$56
      1 "Homme"
      2 "Femme"
  /Q3203$57
      1 "Homme"
      2 "Femme"
  /Q3203$58
      1 "Homme"
      2 "Femme"
  /Q3203$59
      1 "Homme"
      2 "Femme"
  /Q3203$60
      1 "Homme"
      2 "Femme"
  /Q3203$61
      1 "Homme"
      2 "Femme"
  /Q3203$62
      1 "Homme"
      2 "Femme"
  /Q3203$63
      1 "Homme"
      2 "Femme"
  /Q3203$64
      1 "Homme"
      2 "Femme"
  /Q3203$65
      1 "Homme"
      2 "Femme"
  /Q3203$66
      1 "Homme"
      2 "Femme"
  /Q3203$67
      1 "Homme"
      2 "Femme"
  /Q3203$68
      1 "Homme"
      2 "Femme"
  /Q3203$69
      1 "Homme"
      2 "Femme"
  /Q3203$70
      1 "Homme"
      2 "Femme"
  /Q3203$71
      1 "Homme"
      2 "Femme"
  /Q3203$72
      1 "Homme"
      2 "Femme"
  /Q3203$73
      1 "Homme"
      2 "Femme"
  /Q3203$74
      1 "Homme"
      2 "Femme"
  /Q3203$75
      1 "Homme"
      2 "Femme"
  /Q3203$76
      1 "Homme"
      2 "Femme"
  /Q3203$77
      1 "Homme"
      2 "Femme"
  /Q3203$78
      1 "Homme"
      2 "Femme"
  /Q3203$79
      1 "Homme"
      2 "Femme"
  /Q3203$80
      1 "Homme"
      2 "Femme"
  /Q3203$81
      1 "Homme"
      2 "Femme"
  /Q3203$82
      1 "Homme"
      2 "Femme"
  /Q3203$83
      1 "Homme"
      2 "Femme"
  /Q3203$84
      1 "Homme"
      2 "Femme"
  /Q3203$85
      1 "Homme"
      2 "Femme"
  /Q3203$86
      1 "Homme"
      2 "Femme"
  /Q3203$87
      1 "Homme"
      2 "Femme"
  /Q3203$88
      1 "Homme"
      2 "Femme"
  /Q3203$89
      1 "Homme"
      2 "Femme"
  /Q3203$90
      1 "Homme"
      2 "Femme"
  /Q3203$91
      1 "Homme"
      2 "Femme"
  /Q3203$92
      1 "Homme"
      2 "Femme"
  /Q3203$93
      1 "Homme"
      2 "Femme"
  /Q3203$94
      1 "Homme"
      2 "Femme"
  /Q3203$95
      1 "Homme"
      2 "Femme"
  /Q3203$96
      1 "Homme"
      2 "Femme"
  /Q3203$97
      1 "Homme"
      2 "Femme"
  /Q3203$98
      1 "Homme"
      2 "Femme"
  /Q3203$99
      1 "Homme"
      2 "Femme"
  /Q3204$01
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$02
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$03
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$04
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$05
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$06
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$07
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$08
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$09
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$10
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$11
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$12
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$13
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$14
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$15
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$16
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$17
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$18
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$19
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$20
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$21
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$22
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$23
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$24
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$25
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$26
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$27
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$28
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$29
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$30
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$31
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$32
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$33
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$34
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$35
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$36
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$37
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$38
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$39
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$40
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$41
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$42
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$43
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$44
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$45
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$46
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$47
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$48
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$49
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$50
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$51
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$52
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$53
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$54
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$55
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$56
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$57
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$58
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$59
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$60
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$61
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$62
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$63
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$64
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$65
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$66
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$67
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$68
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$69
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$70
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$71
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$72
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$73
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$74
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$75
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$76
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$77
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$78
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$79
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$80
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$81
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$82
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$83
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$84
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$85
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$86
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$87
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$88
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$89
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$90
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$91
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$92
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$93
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$94
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$95
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$96
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$97
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$98
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3204$99
      1 "Primaire"
      2 "Secondaire"
      3 "Supérieuse"
      9 "Pas disponible"
  /Q3205$01
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$02
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$03
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$04
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$05
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$06
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$07
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$08
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$09
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$10
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$11
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$12
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$13
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$14
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$15
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$16
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$17
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$18
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$19
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$20
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$21
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$22
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$23
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$24
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$25
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$26
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$27
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$28
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$29
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$30
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$31
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$32
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$33
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$34
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$35
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$36
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$37
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$38
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$39
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$40
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$41
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$42
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$43
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$44
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$45
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$46
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$47
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$48
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$49
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$50
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$51
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$52
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$53
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$54
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$55
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$56
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$57
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$58
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$59
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$60
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$61
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$62
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$63
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$64
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$65
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$66
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$67
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$68
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$69
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$70
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$71
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$72
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$73
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$74
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$75
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$76
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$77
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$78
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$79
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$80
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$81
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$82
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$83
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$84
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$85
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$86
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$87
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$88
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$89
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$90
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$91
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$92
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$93
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$94
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$95
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$96
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$97
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$98
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3205$99
      1 "Agent de santé communitaire (ASC)"
      2 "Agent de santé communitaire polyvalent (ASCP)"
      3 "Superviseur"
  /Q3208$01
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$02
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$03
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$04
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$05
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$06
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$07
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$08
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$09
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$10
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$11
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$12
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$13
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$14
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$15
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$16
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$17
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$18
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$19
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$20
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$21
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$22
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$23
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$24
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$25
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$26
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$27
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$28
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$29
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$30
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$31
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$32
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$33
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$34
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$35
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$36
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$37
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$38
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$39
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$40
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$41
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$42
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$43
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$44
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$45
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$46
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$47
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$48
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$49
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$50
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$51
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$52
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$53
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$54
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$55
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$56
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$57
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$58
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$59
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$60
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$61
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$62
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$63
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$64
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$65
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$66
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$67
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$68
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$69
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$70
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$71
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$72
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$73
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$74
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$75
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$76
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$77
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$78
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$79
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$80
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$81
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$82
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$83
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$84
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$85
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$86
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$87
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$88
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$89
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$90
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$91
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$92
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$93
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$94
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$95
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$96
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$97
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$98
   9998 "NSP"
   9999 "Pas disponible"
  /Q3208$99
   9998 "NSP"
   9999 "Pas disponible"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\HT7A\HTCS7AFLSP.sav'.
