DATA LIST FILE='C:\Countries\HT7A\HTFP7AFLSR.DAT' RECORDS=1
  /
  INV_ID      1-5   
  P_ID        6-7   
  OBS_N       8-9    (A)
  OBS_ID     10-12  
  C000       13-16   (A)
  C001       17-18  
  C002       19-22  
  C003       23-23  
  C004       24-28  
  C004P      29-30  
  C004CT     31-32   (A)
  C004CN     33-35  
  C005       36-43  
  C007       44-45  
  C008       46-47  
  C009A      48-51  
  C009B      52-55  
  C009C      56-58  
  C020A      59-59  
  C020B      60-60  
  C021       61-61  
  C022       62-62  
  C023       63-63  
  C024       64-65  
  C032       66-67  
  C033       68-71  
  C033D      72-73  
  C501       74-76  
  C502A      77-77  
  C502B      78-78  
  C502C      79-79  
  C502E      80-80  
  C502F      81-81  
  C502G      82-82  
  C502H      83-83  
  C502I      84-84  
  C502J      85-85  
  C502K      86-86  
  C502L      87-87  
  C503       88-88  
  C504       89-89  
  C505       90-95  
  C507       96-96  
  C508       97-98  
  C510       99-99  
  C511      100-101 
  C512      102-102 
  C514      103-103 
  C515      104-104 
  C517A     105-108 
  C517B     109-112 
  C518A     113-116 
  C518B     117-120 
  C520      121-122 
  C521      123-123 
  C522      124-124 
  SCDEPART  125-126 
  SCLOCAL   127-127 
  C202      128-128 
  C203A     129-129 
  C203B     130-130 
  C203C     131-131 
  C203D     132-132 
  C203Y     133-133 
  C204A     134-134 
  C204B     135-135 
  C204C     136-136 
  C204D     137-137 
  C204E     138-138 
  C204F     139-139 
  C204Y1    140-140 
  C204Y2    141-141 
  C205A     142-142 
  C205B     143-143 
  C205C     144-144 
  C205D     145-145 
  C205E     146-146 
  C205F     147-147 
  C205G     148-148 
  C205H     149-149 
  C205I     150-150 
  C205J     151-151 
  C205K     152-152 
  C205M     153-153 
  C205N     154-154 
  C205P     155-155 
  C205Q     156-156 
  C205R     157-157 
  C205S     158-158 
  C205Y     159-159 
  CF205A    160-160 
  CF205M    161-161 
  CF205N    162-162 
  CF205XA   163-163 
  CF205XB   164-164 
  CF205XC   165-165 
  CF205XD   166-166 
  CF205XE   167-167 
  C206A     168-168 
  C206B     169-169 
  C206C     170-170 
  C206D     171-171 
  C206E     172-172 
  C206F     173-173 
  C206G     174-174 
  C206I     175-175 
  C206Y     176-176 
  C207A     177-177 
  C207B     178-178 
  C207C     179-179 
  C207D     180-180 
  C207E     181-181 
  C207F     182-182 
  C207Y     183-183 
  C208B     184-184 
  C208C     185-185 
  C208D     186-186 
  C208E     187-187 
  C208F     188-188 
  C208G     189-189 
  C208H     190-190 
  C208Y     191-191 
  C209A     192-192 
  C209B     193-193 
  C209C     194-194 
  C209D     195-195 
  C209Y     196-196 
  C211A     197-197 
  C211B     198-198 
  C212      199-199 
  C213      200-200 
  C220      201-201 
  C221A     202-202 
  C221C     203-203 
  C221D     204-204 
  C221E     205-205 
  C221F     206-206 
  C221Y     207-207 
  C222A     208-208 
  C222B     209-209 
  C222C     210-210 
  C222D     211-211 
  C222E     212-212 
  C222F     213-213 
  C222G     214-214 
  C222Y     215-215 
  C223A     216-216 
  C224A     217-217 
  C224B     218-218 
  C224D     219-219 
  C224Y     220-220 
  C225A     221-221 
  C225B     222-222 
  C225C     223-223 
  C225D     224-224 
  C225E     225-225 
  C225F     226-226 
  C225G     227-227 
  C225Y     228-228 
  C226A     229-229 
  C226B     230-230 
  C226C     231-231 
  C226D     232-232 
  C226Y     233-233 
  C227A     234-234 
  C227B     235-235 
  C227C     236-236 
  C227D     237-237 
  C227Y     238-238 
  C228A     239-239 
  C228B     240-240 
  C228C     241-241 
  C228D     242-242 
  C228E     243-243 
  C228Y     244-244 
  C230_36Y  245-245 
  C230A     246-246 
  C230B     247-247 
  C230C     248-248 
  C230E     249-249 
  C230F     250-250 
  C230G     251-251 
  C230H     252-252 
  C230I     253-253 
  C230J     254-254 
  C230K     255-255 
  C230L     256-256 
  C230M     257-257 
  C230N     258-258 
  C230Y     259-259 
  C232A     260-260 
  C232B     261-261 
  C232C     262-262 
  C232D     263-263 
  C232Y     264-264 
  C233A     265-265 
  C233C     266-266 
  C233E     267-267 
  C233F     268-268 
  C234A     269-269 
  C234B     270-270 
  C234C     271-271 
  C234D     272-272 
  C234E     273-273 
  C234F     274-274 
  C234G     275-275 
  C234H     276-276 
  C234X     277-277 
  C234Y     278-278 
  C235A     279-279 
  C235B     280-280 
  C235C     281-281 
  C235Y     282-282 
  C236A     283-283 
  C236B     284-284 
  C236C     285-285 
  C236D     286-286 
  C236E     287-287 
  C236X     288-288 
  C236Y     289-289 
  C238      290-290 
  C239      291-292 
  C250      293-296 
  C251      297-298 
  C252      299-302 
  C253      303-304 
  C254      305-305 
  C255A     306-306 
  C255B     307-307 
  C255C     308-308 
  C255D     309-309 
  C255E     310-310 
  C255F     311-311 
  C255G     312-312 
  C256A     313-313 
  C256B     314-314 
  C256C     315-315 
  C256D     316-316 
  C256E     317-317 
  C256X     318-318 
  C256Y     319-319 
  C257      320-320 
  C258      321-322 
  C259      323-323 
  C260      324-324 
  C261A     325-325 
  C261B     326-326 
  C261C     327-327 
  C261D     328-328 
  C261E     329-329 
  C261F     330-330 
  C261G     331-331 
  C261H     332-332 
  C261X     333-333 
  C261Y     334-334 
  C261Z     335-335 
  C262A     336-336 
  C262B     337-337 
  C262C     338-338 
  C262D     339-339 
  C262E     340-340 
  C262F     341-341 
  C262G     342-342 
  C262X     343-343 
  C262Y     344-344 
  C262Z     345-345 
  C263      346-346 
  C264      347-347 
  C265      348-348 
  C266      349-349 
  C267      350-350 
  C268      351-351 
  C270      352-352 
  C271      353-353 
  C272      354-354 
  C274      355-355 
  C275      356-356 
  C276      357-357 
  C280A     358-358 
  C280B     359-359 
  C280C     360-360 
  C280D     361-361 
  C281A     362-362 
  C281B     363-363 
  C281C     364-364 
  C281D     365-365 
  C281E     366-366 
  C282A     367-367 
  C282B     368-368 
  C282C     369-369 
  C282Y     370-370 
  SXC103D   371-372 
  SXC130    373-373 
  SXC131    374-374 
  SXC132    375-375 
 .
VARIABLE LABELS
   INV_ID   "INVENTORY ID"
  /P_ID     "Unit/Provider line number ID"
  /OBS_N    "Client type code"
  /OBS_ID   "Client ID"
  /C000     "Survey phase"
  /C001     "Department (Country-specific)"
  /C002     "Commune (Country-specific)"
  /C003     "Urban/rural"
  /C004     "Facility number"
  /C004P    "Provider line number"
  /C004CT   "Client type code (alpha)"
  /C004CN   "Client ID number"
  /C005     "Sample weight"
  /C007     "Facility type (Country-specific)"
  /C008     "Facility managing authority (Country-specific)"
  /C009A    "Interviewer for observation"
  /C009B    "Interviewer for exit interview"
  /C009C    "NA - Keyer"
  /C020A    "Result of observation"
  /C020B    "Result of exit interview"
  /C021     "Type of client"
  /C022     "Sex of provider"
  /C023     "Sex of client/sick child"
  /C024     "Technical qualification of provider (Country-specific within ranges)"
  /C032     "Month of observation/interview"
  /C033     "Year of observation/interview"
  /C033D    "Day of observation/interview"
  /C501     "Duration of wait before being seen"
  /C502A    "Client problem during visit: Time had to wait"
  /C502B    "Client problem during visit: Ability to discuss problems/concerns"
  /C502C    "Client problem during visit: Amount of explanation for problem/tx"
  /C502E    "Client problem during visit: Visual privacy"
  /C502F    "Client problem during visit: Auditory privacy"
  /C502G    "Client problem during visit: Availability of medicines at facility"
  /C502H    "Client problem during visit: Hours of service"
  /C502I    "Client problem during visit: Days of service"
  /C502J    "Client problem during visit: Cleanliness of facility"
  /C502K    "Client problem during visit: Staff treatment of client"
  /C502L    "Client problem during visit: Cost"
  /C503     "Part of prepayment plan/insurance that pays part of cost"
  /C504     "Charged for services today"
  /C505     "Total amount paid in Gourdes"
  /C507     "Facility nearest to home"
  /C508     "Reason did not go to nearest facility"
  /C510     "Caretaker relationship to sick child (Sick child exit only)"
  /C511     "Age of client (caretaker of client)"
  /C512     "Highest level of education attended"
  /C514     "Literacy level"
  /C515     "Country reported highest level of education attended (CS)"
  /C517A    "Time observation interview began"
  /C517B    "Time observation interview ended"
  /C518A    "Time exit interview began"
  /C518B    "Time exit interview ended"
  /C520     "Opinion of services given today"
  /C521     "Would recommend to friend/family member"
  /C522     "First observation for this provider for this service"
  /SCDEPART "CS - Region with West separated for metropolitan and other"
  /SCLOCAL  "CS - Metropolitan/other cities/locality"
  /C202     "First visit (Data from observation)"
  /C203A    "Main symptoms: Cough or difficult breathing"
  /C203B    "Main symptoms: Diarrhea"
  /C203C    "Main symptoms: Fever or body hotness"
  /C203D    "Main symptoms: Ear problems"
  /C203Y    "Main symptoms: None of the above 4"
  /C204A    "Other problems General: Unable to drink/breastfeed"
  /C204B    "Other problems General: Vomiting everything"
  /C204C    "Other problems General: Had convulsions"
  /C204D    "Other problems HIV symptomatic: Mother's HIV status"
  /C204E    "Other problems HIV symptomatic: TB infection in either parent in last 5 years"
  /C204F    "Other problems HIV symptomatic: Two or more episodes of diarrhea in child each lasting 14 days+"
  /C204Y1   "Other problems: None of C204A, B, C"
  /C204Y2   "Other problems HIV symptomatic: None of C204D, E, F"
  /C205A    "Physical exam: temperature by thermometer"
  /C205B    "Physical exam: feel for fever or hotness"
  /C205C    "Physical exam: Count respirations"
  /C205D    "Physical exam: Auscultate child"
  /C205E    "Physical exam: Check turgor for dehydration"
  /C205F    "Physical exam: Check for pallor by looking at palms"
  /C205G    "Physical exam: Check for pallor by looking at conjunctiva or mouth"
  /C205H    "Physical exam: Look in ear"
  /C205I    "Physical exam: Feel behind ear"
  /C205J    "Physical exam: Undress child to examine"
  /C205K    "Physical exam: Press feet to check for edema"
  /C205M    "Physical exam: Weigh the child"
  /C205N    "Physical exam: Plot weight on growth chart"
  /C205P    "Physical exam: Look in child's mouth"
  /C205Q    "Physical exam: Check for neck stiffness"
  /C205R    "Physical exam: Check for enlarged lymph nodes in 2+ sites: neck, armpits, groin"
  /C205S    "CS - Physical exam: Compare child's weight with reference"
  /C205Y    "Physical exam: None of the above physical checks"
  /CF205A   "Routine action in facility: Take child's temperature"
  /CF205M   "Routine action in facility: Weigh child"
  /CF205N   "Routine action in facility: Plot child's weight on graph"
  /CF205XA  "Routine action in facility: Conduct group health education"
  /CF205XB  "Routine action in facility: Assess child's vaccination status"
  /CF205XC  "Routine action in facility: Administer fever-reducing med/ sponge for fever"
  /CF205XD  "Routine action in facility: Triage children"
  /CF205XE  "NA - Routine action in facility: CS"
  /C206A    "Other assessments: Offered breast or drink"
  /C206B    "Other assessments: Normal feeding when not ill"
  /C206C    "Other assessments: Normal breastfeeding when not ill"
  /C206D    "Other assessments: Feeding or breastfeeding during this illness"
  /C206E    "Other assessments: Discuss weight/growth/growth chart"
  /C206F    "Other assessments: Review immunization card or ask about vaccination history"
  /C206G    "Other assessments: Ask if child received vitamin A within past 6 months"
  /C206I    "Other assessments: Asked if child received de-worming medication in last 6 months"
  /C206Y    "Other assessments: None of the above"
  /C207A    "Caretaker counseling: Provide general information about feeding/breastfeeding when not sick"
  /C207B    "Caretaker counseling: Advise extra fluids during this sickness"
  /C207C    "Caretaker counseling: Advise continued feeding during sickness"
  /C207D    "Caretaker counseling: Name the illness for the caretaker"
  /C207E    "Caretaker counseling: Describe symptoms requiring immediate return for care"
  /C207F    "Caretaker counseling: Used visual aid to educate the caretaker"
  /C207Y    "Caretaker counseling: No caretaker counseling"
  /C208B    "Referral: Child referred to other provider"
  /C208C    "Referral: Child referred to lab for test"
  /C208D    "Referral: Provider explained referral"
  /C208E    "Referral: Referral slip given"
  /C208F    "Referral: Told where to go and whom to see"
  /C208G    "Referral: Told when to go"
  /C208H    "Referral: Recommended child be hospitalized urgently"
  /C208Y    "Referral: No referrals"
  /C209A    "Home meds: Oral medications prescribed or provided for home treatment"
  /C209B    "Home meds: Oral medication administration explained"
  /C209C    "Home meds: Caretaker asked to repeat instructions"
  /C209D    "Home meds: Oral medications - first dose given"
  /C209Y    "Home meds: Oral medications - none prescribed or given"
  /C211A    "Child's health card: Provider referred to it"
  /C211B    "Child's health card: Provider wrote on it"
  /C212     "Follow-up discussed"
  /C213     "Outcome of consultation"
  /C220     "Asked provider for diagnosis"
  /C221A    "Diagnosis Respiratory: Pneumonia/ Broncopneumonia"
  /C221C    "Diagnosis Respiratory: Bronchial Spasm/asthma"
  /C221D    "Diagnosis Respiratory: Upper respiratory infection (URI)/Acute Respiratory Infection (ARI)"
  /C221E    "Diagnosis Respiratory: Respiratory illness, diagnosis uncertain"
  /C221F    "Diagnosis Respiratory: Cough, diagnosis uncertain"
  /C221Y    "Diagnosis Respiratory: No respiratory diagnosis"
  /C222A    "NA - Diagnosis Digestive: Persistent diarrhea"
  /C222B    "Diagnosis Digestive: Diarrhea"
  /C222C    "Diagnosis Digestive: Dysentery"
  /C222D    "Diagnosis Digestive: Amebiasis"
  /C222E    "Diagnosis Digestive: Other digestive/diarrhea"
  /C222F    "NA - Diagnosis Digestive: Acute watery diarrhea"
  /C222G    "CS - Diagnosis Digestive: Parasitose"
  /C222Y    "Diagnosis Digestive: No digestive diagnosis"
  /C223A    "Diagnosis: Dehydration * special codes"
  /C224A    "Diagnosis Malaria: Clinical diagnosis"
  /C224B    "Diagnosis Malaria: Blood smear"
  /C224D    "Diagnosis Malaria: RDT"
  /C224Y    "Diagnosis Malaria: No malaria diagnosis"
  /C225A    "Diagnosis Fever/Measles: Fever of unknown origin"
  /C225B    "Diagnosis Fever/Measles: Measles with no complications"
  /C225C    "Diagnosis Fever/Measles: Measles with complications"
  /C225D    "Diagnosis Fever/Measles: Typhoid fever"
  /C225E    "Diagnosis Fever/Measles: Urinary track infection"
  /C225F    "Diagnosis Fever/Measles: Septicemia"
  /C225G    "Diagnosis Fever/Measles: Meningitis"
  /C225Y    "Diagnosis Fever/Measles: No fever/ measles diagnosis"
  /C226A    "Diagnosis Ear: Mastoiditis"
  /C226B    "Diagnosis Ear: Acute ear infections"
  /C226C    "Diagnosis Ear: Chronic ear infection"
  /C226D    "Diagnosis Ear: Other ear infection"
  /C226Y    "Diagnosis Ear: No ear diagnosis"
  /C227A    "NA - Diagnosis Throat: Streptococcal sore throat"
  /C227B    "NA - Diagnosis Throat: Non-streptococcal sore throat"
  /C227C    "Diagnosis Throat: Other throat diagnosis"
  /C227D    "Diagnosis Sore throat (Pharyngitis)"
  /C227Y    "Diagnosis Throat: No throat diagnosis"
  /C228A    "Diagnosis: Other diagnosis"
  /C228B    "Diagnosis: Abscess"
  /C228C    "Diagnosis: Bacterial conjunctivitis"
  /C228D    "Diagnosis: Skin condition"
  /C228E    "CS - Diagnosis: Anemia"
  /C228Y    "Diagnosis: No other diagnosis"
  /C230_36Y "No treatment prescribed during consult"
  /C230A    "Treatment General med: Benzyl penicillin injection"
  /C230B    "Treatment General med: Other antibiotic injection"
  /C230C    "Treatment General med: Other injection"
  /C230E    "Treatment General med: Other antibiotic tablet/syrup"
  /C230F    "Treatment General med: Paracetamol"
  /C230G    "Treatment General med: Vitamins"
  /C230H    "Treatment General med: Cough syrups/other meds for symptomatic tx"
  /C230I    "Treatment General med: Zinc"
  /C230J    "Treatment General med: Co-trimoxazole tablets"
  /C230K    "Treatment General med: Co-trimoxazole syrup"
  /C230L    "Treatment General med: Amoxicillin capsules"
  /C230M    "Treatment General med: Amoxicillin syrup"
  /C230N    "Treatment General med: Fever reducing other than paracetamol"
  /C230Y    "Treatment General med: No general treatment medication"
  /C232A    "Treatment Respiratory: Nebulilzer or inhaler"
  /C232B    "Treatment Respiratory: Injectable bronchodilator (adrenaline)"
  /C232C    "Treatment Respiratory: Oral bronchodilator"
  /C232D    "Treatment Respiratory: Dry ear by wicking"
  /C232Y    "Treatment Respiratory: No respiratory treatment"
  /C233A    "Treatment Malaria injectable: Quinine"
  /C233C    "Treatment Malaria injectable: Other injectable antimalarial"
  /C233E    "NA - Treatment Malaria injectable: Artemether/ artesunate"
  /C233F    "NA - Treatment Malaria suppository: Artemether/ artesunate"
  /C234A    "Treatment Malaria oral: Fansidar (SP)"
  /C234B    "NA - Treatment Malaria oral: Artemisinin (incl ACT, COARTEM)"
  /C234C    "NA - Treatment Malaria oral: Amodiaquine"
  /C234D    "NA - Treatment Malaria oral: Artemether/ Artesunate"
  /C234E    "NA - Treatment Malaria oral: Quinine"
  /C234F    "CS - Treatment Malaria oral: Chloroquine"
  /C234G    "CS - Treatment Malaria oral: Primaquine"
  /C234H    "CS - Treatment Malaria oral: Mefloquine"
  /C234X    "Treatment Malaria oral: Other antimalarial"
  /C234Y    "Treatment Malaria: No antimalarial treatment for C233/C234"
  /C235A    "Treatment Dehydration: Home ORT"
  /C235B    "Treatment Dehydration: Initial ORT in facility (4 hours)"
  /C235C    "Treatment Dehydration: Intravenous fluids"
  /C235Y    "Treatment Dehydration: No dehydration treatment"
  /C236A    "Treatment Other: Vitamin A"
  /C236B    "Treatment Other: Feeding solid foods"
  /C236C    "Treatment Other: Feeding extra liquids"
  /C236D    "Treatment Other: Feeding breast milk"
  /C236E    "Treatment Other: Prescribe de-worming medication"
  /C236X    "Treatment Other: Other"
  /C236Y    "Treatment Other: No other treatment"
  /C238     "Child given vaccination"
  /C239     "Reason no vaccination given"
  /C250     "Century month code of birth of child (imputed)"
  /C251     "Month of birth of child"
  /C252     "Year of birth of child"
  /C253     "Age in months of child"
  /C254     "Flag for date of birth"
  /C255A    "Health reason for visit: Cough or difficult breathing"
  /C255B    "Health reason for visit: Diarrhea"
  /C255C    "Health reason for visit: Fever/body hotness at home"
  /C255D    "Health reason for visit: Vomit everything"
  /C255E    "Health reason for visit: Feeding, drinking problems"
  /C255F    "Health reason for visit: Convulsions"
  /C255G    "Health reason for visit: Sleepiness"
  /C256A    "NA - Other reason for visit: Eye problems"
  /C256B    "Other reason for visit: Skin sore"
  /C256C    "Other reason for visit: Injury"
  /C256D    "Other reason for visit: Ear problem"
  /C256E    "CS - Other reason for visit: Abdominal pain"
  /C256X    "Other reason for visit: Other"
  /C256Y    "Other reason for visit: No other reason"
  /C257     "Other visits for same sickness"
  /C258     "Days ago illness began"
  /C259     "Provider named the child's illness"
  /C260     "Caretaker action if child does not get better or gets worse"
  /C261A    "Danger signs addl tx: Fever"
  /C261B    "Danger signs addl tx: Breathing problems"
  /C261C    "Danger signs addl tx: Becomes sicker"
  /C261D    "Danger signs addl tx: Blood in stool"
  /C261E    "Danger signs addl tx: Vomiting"
  /C261F    "Danger signs addl tx: Poor eating/not eating"
  /C261G    "Danger signs addl tx: Poor drinking/not drinking"
  /C261H    "NA - Danger signs addl tx: Convulsions"
  /C261X    "Danger signs addl tx: Other"
  /C261Y    "Danger signs addl tx: No signs"
  /C261Z    "Danger signs addl tx: Don't know"
  /C262A    "Adv non-emergency return: More medicines"
  /C262B    "Adv non-emergency return: Symptoms increase or worsen"
  /C262C    "Adv non-emergency return: Follow-up appointment"
  /C262D    "Adv non-emergency return: Child admitted"
  /C262E    "Adv non-emergency return: Routine immunization"
  /C262F    "NA - Adv non-emergency return: Vitamin A supplementation"
  /C262G    "NA - Adv non-emergency return: Lab test results"
  /C262X    "Adv non-emergency return: Other"
  /C262Y    "Adv non-emergency return: No reason"
  /C262Z    "Adv non-emergency return: Don't know"
  /C263     "Provider gave or prescribed medicines for home use"
  /C264     "Caretaker has medications/prescriptions"
  /C265     "Provider explained how to give medications"
  /C266     "Caretaker feels comfortable about giving medications"
  /C267     "Child given first dose at facility"
  /C268     "Child given injection for treatment today"
  /C270     "Provider asked about types of food given when not sick"
  /C271     "Child weighed at facility"
  /C272     "Provider talked about weight and how child is growing"
  /C274     "Provider advised about feeding solids during illness"
  /C275     "Provider advised about feeding liquids/breastmilk during illness"
  /C276     "Child given vaccination"
  /C280A    "NA - Referral: Caretaker instructed to take child for finger/heel stick to lab or another provider in facility"
  /C280B    "NA - Referral: Caretaker took child for finger/heel stick"
  /C280C    "NA - Referral: Caretaker told result of finger/heel stick test"
  /C280D    "Referral: Caretaker instructed to take child for tests outside facility"
  /C281A    "Outside referral: Given paper or record to take to referral"
  /C281B    "Outside referral: Told where to go for referral"
  /C281C    "Outside referral: Told whom to see for referral"
  /C281D    "Outside referral: Told why to go for referral"
  /C281E    "NA - Outside referral: Caretaker intends to go to referral(s)"
  /C282A    "Provider visited prior to visit: Other provider in this facility"
  /C282B    "Provider visited prior to visit: Other provider in different facility"
  /C282C    "Provider visited prior to visit: Traditional healer"
  /C282Y    "Provider visited prior to visit: No other provider"
  /SXC103D  "CS - Day of birth"
  /SXC130   "CS - Caregiver reported vaccination given during visit"
  /SXC131   "CS - Has vaccination card observed"
  /SXC132   "CS - Observed card shows vaccination on day of visit"
 .
MISSING VALUE
   C003     (9)
  /C022     (9)
  /C023     (9)
  /C501     (999)
  /C502A    (9)
  /C502B    (9)
  /C502C    (9)
  /C502E    (9)
  /C502F    (9)
  /C502G    (9)
  /C502H    (9)
  /C502I    (9)
  /C502J    (9)
  /C502K    (9)
  /C502L    (9)
  /C503     (9)
  /C504     (9)
  /C505     (999999)
  /C507     (9)
  /C508     (99)
  /C510     (9)
  /C511     (99)
  /C512     (9)
  /C514     (9)
  /C515     (9)
  /C517A    (9999)
  /C517B    (9999)
  /C518A    (9999)
  /C518B    (9999)
  /C520     (99)
  /C521     (9)
  /C202     (9)
  /C203A    (9)
  /C203B    (9)
  /C203C    (9)
  /C203D    (9)
  /C203Y    (9)
  /C204A    (9)
  /C204B    (9)
  /C204C    (9)
  /C204D    (9)
  /C204E    (9)
  /C204F    (9)
  /C204Y1   (9)
  /C204Y2   (9)
  /C205A    (9)
  /C205B    (9)
  /C205C    (9)
  /C205D    (9)
  /C205E    (9)
  /C205F    (9)
  /C205G    (9)
  /C205H    (9)
  /C205I    (9)
  /C205J    (9)
  /C205K    (9)
  /C205M    (9)
  /C205N    (9)
  /C205P    (9)
  /C205Q    (9)
  /C205R    (9)
  /C205S    (9)
  /C205Y    (9)
  /C206A    (9)
  /C206B    (9)
  /C206C    (9)
  /C206D    (9)
  /C206E    (9)
  /C206F    (9)
  /C206G    (9)
  /C206I    (9)
  /C206Y    (9)
  /C207A    (9)
  /C207B    (9)
  /C207C    (9)
  /C207D    (9)
  /C207E    (9)
  /C207F    (9)
  /C207Y    (9)
  /C208B    (9)
  /C208C    (9)
  /C208D    (9)
  /C208E    (9)
  /C208F    (9)
  /C208G    (9)
  /C208H    (9)
  /C208Y    (9)
  /C209A    (9)
  /C209B    (9)
  /C209C    (9)
  /C209D    (9)
  /C209Y    (9)
  /C211A    (9)
  /C211B    (9)
  /C212     (9)
  /C213     (9)
  /C220     (9)
  /C221A    (9)
  /C221C    (9)
  /C221D    (9)
  /C221E    (9)
  /C221F    (9)
  /C221Y    (9)
  /C222A    (9)
  /C222B    (9)
  /C222C    (9)
  /C222D    (9)
  /C222E    (9)
  /C222F    (9)
  /C222G    (9)
  /C222Y    (9)
  /C223A    (9)
  /C224A    (9)
  /C224B    (9)
  /C224D    (9)
  /C224Y    (9)
  /C225A    (9)
  /C225B    (9)
  /C225C    (9)
  /C225D    (9)
  /C225E    (9)
  /C225F    (9)
  /C225G    (9)
  /C225Y    (9)
  /C226A    (9)
  /C226B    (9)
  /C226C    (9)
  /C226D    (9)
  /C226Y    (9)
  /C227A    (9)
  /C227B    (9)
  /C227C    (9)
  /C227D    (9)
  /C227Y    (9)
  /C228A    (9)
  /C228B    (9)
  /C228C    (9)
  /C228D    (9)
  /C228E    (9)
  /C228Y    (9)
  /C230_36Y (9)
  /C230A    (9)
  /C230B    (9)
  /C230C    (9)
  /C230E    (9)
  /C230F    (9)
  /C230G    (9)
  /C230H    (9)
  /C230I    (9)
  /C230J    (9)
  /C230K    (9)
  /C230L    (9)
  /C230M    (9)
  /C230N    (9)
  /C230Y    (9)
  /C232A    (9)
  /C232B    (9)
  /C232C    (9)
  /C232D    (9)
  /C232Y    (9)
  /C233A    (9)
  /C233C    (9)
  /C233E    (9)
  /C233F    (9)
  /C234A    (9)
  /C234B    (9)
  /C234C    (9)
  /C234D    (9)
  /C234E    (9)
  /C234F    (9)
  /C234G    (9)
  /C234H    (9)
  /C234X    (9)
  /C234Y    (9)
  /C235A    (9)
  /C235B    (9)
  /C235C    (9)
  /C235Y    (9)
  /C236A    (9)
  /C236B    (9)
  /C236C    (9)
  /C236D    (9)
  /C236E    (9)
  /C236X    (9)
  /C236Y    (9)
  /C238     (9)
  /C239     (99)
  /C250     (9999)
  /C251     (99)
  /C252     (9999)
  /C253     (99)
  /C255A    (9)
  /C255B    (9)
  /C255C    (9)
  /C255D    (9)
  /C255E    (9)
  /C255F    (9)
  /C255G    (9)
  /C256A    (9)
  /C256B    (9)
  /C256C    (9)
  /C256D    (9)
  /C256E    (9)
  /C256X    (9)
  /C256Y    (9)
  /C257     (9)
  /C258     (99)
  /C259     (9)
  /C260     (9)
  /C261A    (9)
  /C261B    (9)
  /C261C    (9)
  /C261D    (9)
  /C261E    (9)
  /C261F    (9)
  /C261G    (9)
  /C261H    (9)
  /C261X    (9)
  /C261Y    (9)
  /C261Z    (9)
  /C262A    (9)
  /C262B    (9)
  /C262C    (9)
  /C262D    (9)
  /C262E    (9)
  /C262F    (9)
  /C262G    (9)
  /C262X    (9)
  /C262Y    (9)
  /C262Z    (9)
  /C263     (9)
  /C264     (9)
  /C265     (9)
  /C266     (9)
  /C267     (9)
  /C268     (9)
  /C270     (9)
  /C271     (9)
  /C272     (9)
  /C274     (9)
  /C275     (9)
  /C276     (9)
  /C280A    (9)
  /C280B    (9)
  /C280C    (9)
  /C280D    (9)
  /C281A    (9)
  /C281B    (9)
  /C281C    (9)
  /C281D    (9)
  /C281E    (9)
  /C282A    (9)
  /C282B    (9)
  /C282C    (9)
  /C282Y    (9)
  /SXC131   (9)
  /SXC132   (9)
 .
VALUE LABELS
   OBS_N   
   'AN' "ANC"
   'SC' "Child Sick"
   'FP' "Family Planning"
   'SI' "STI"
   'IN' "Injection"
   'DC' "Delivery"
   'LD' "Labor/Delivery"
  /C001    
      1 "West"
      2 "Southeast"
      3 "North"
      4 "Northeast"
      5 "Artibonite"
      6 "Central"
      7 "South"
      8 "Grand-Anse"
      9 "Northwest"
     10 "Nippes"
  /C002    
    111 "Port-Au-Prince"
    112 "Cité-Soleil/Delmas/Tabarre"
    113 "Carrefour"
    114 "Pétion-ville"
    115 "Kenscoff"
    116 "Gressier"
    121 "Léogâne"
    122 "Petit-Goâve"
    123 "Grand-Goâve"
    131 "Croix-des-Bouquets"
    132 "Thomazeau"
    133 "Ganthier"
    134 "Cornillon"
    135 "Fonds-Verrettes"
    141 "Arcahaie"
    142 "Cabaret"
    151 "Anse-à-Galets"
    152 "Pointe-à-Raquettes"
    211 "Jacmel"
    212 "Marigot"
    213 "Cayes-Jacmel"
    214 "La Vallée"
    221 "Bainet"
    222 "Côtes-de-Fer"
    231 "Belle-Anse"
    232 "Grand-Gosier"
    233 "Thiotte"
    234 "Anse-à-Pitres"
    311 "Cap-Haïtien"
    312 "Quartier-Morin"
    313 "Limonade"
    321 "Acul-du-Nord"
    322 "Plaine-du-Nord"
    323 "Milot"
    331 "Grande-Rivière"
    332 "Bahon"
    341 "Saint-Raphaël"
    342 "Dondon"
    343 "Ranquitte"
    344 "Pignon"
    345 "La Victoire"
    351 "Borgne"
    352 "Port-Margot"
    361 "Limbé"
    362 "Bas-Limbé"
    371 "Plaisance"
    372 "Pilate"
    411 "Fort-Liberté"
    412 "Ferrier"
    413 "Perches"
    421 "Ouanaminthe"
    422 "Capotille"
    423 "Mont-Organisé"
    431 "Trou-du-Nord"
    432 "Sainte-Suzanne"
    433 "Terrier-Rouge"
    434 "Caracol"
    441 "Vallières"
    442 "Carice"
    443 "Mombin-Crochu"
    511 "Gonaïves"
    512 "Ennery"
    513 "L'Estère"
    521 "Gros-Morne"
    522 "Terre-Neuve"
    523 "Anse-Rouge"
    531 "Saint-Marc"
    532 "Verrettes"
    533 "La Chapelle"
    541 "Dessalines"
    542 "Petite-Rivière de l'Artibonite"
    543 "Grande Saline"
    544 "Desdunes"
    551 "Saint-Michel"
    552 "Marmelade"
    611 "Hinche"
    612 "Maïssade"
    613 "Thomonde"
    614 "Cerca-Cavajal"
    621 "Mirebalais"
    622 "Saut-d'Eau"
    623 "Boucan-Carré"
    631 "Lascahobas"
    632 "Belladère"
    633 "Savanette"
    641 "Cerca-La-Source"
    642 "Thomassique"
    711 "Les Cayes"
    712 "Torbeck"
    713 "Chantal"
    714 "Camp-Perrin"
    715 "Maniche"
    716 "Île-à-Vache"
    721 "Port-Salut"
    722 "Saint-Jean"
    723 "Arniquet"
    731 "Aquin"
    732 "Saint-Louis du Sud"
    733 "Cavaillon"
    741 "Côteaux"
    742 "Port-à-Piment"
    743 "Roche-à-Bateau"
    751 "Chardonnières"
    752 "Les Anglais"
    753 "Tiburon"
    811 "Jérémie"
    812 "Abricots"
    813 "Bonbon"
    814 "Moron"
    815 "Chambellan"
    821 "Anse-d'Hainault"
    822 "Dame-Marie"
    823 "Les Irois"
    831 "Corail"
    832 "Roseaux"
    833 "Beaumont"
    834 "Pestel"
    911 "Port-de-Paix"
    912 "La Tortue"
    913 "Bassin-Bleu"
    914 "Chansolme"
    921 "St-Ls-du-Nord'Ouest"
    922 "Anse-à-Foleur"
    931 "Môle-Saint-Nicolas"
    932 "Baie-de-Henne"
    933 "Bombardopolis"
    934 "Jean-Rabel"
   1001 "Fonds-des-Nègres"
   1002 "Arnaud"
   1003 "Grand-Boucan"
   1004 "Paillant"
   1005 "Plaisance"
   1041 "Miragoâne"
   1042 "Petite-Rivière de Nippes"
   1051 "Anse-à-Veau"
   1052 "Baradères"
   1053 "Petit-Trou"
   1054 "L'Asile"
  /C003    
      1 "Urban"
      2 "Rural"
  /C004CT  
   'AN' "ANC"
   'SC' "Child Sick"
   'FP' "Family Planning"
   'SI' "STI"
   'IN' "Injection"
   'DC' "Delivery"
   'LD' "Labor/Delivery"
  /C007    
      1 "University hospital"
      2 "Department hospital"
      3 "Community reference hospital"
      4 "Other hospitals"
      5 "Health Center with lit"
      6 "Health Center without lit"
      7 "Dispensary/Community Health Center"
  /C008    
      1 "Government/public"
      2 "Private not for profit"
      3 "Private for profit"
      4 "Mixed"
  /C020A   
      0 "Refused by provider or client"
      1 "Complete"
      7 "Not returned from field"
  /C020B   
      0 "Refused by client"
      1 "Complete"
      2 "Sick child admitted, not possible to continue"
      7 "Not returned from field"
  /C021    
      1 "ANC"
      2 "Child Sick"
      3 "Family Planning"
      6 "CS - Labor/Delivery"
  /C022    
      1 "Male"
      2 "Female"
  /C023    
      1 "Male"
      2 "Female"
  /C024    
      1 "Generalist Medical Doctor"
      2 "Specialist Medical Doctor"
      3 "Clinical Officer (Degree Level)"
      4 "Clinical Technician (Diploma)"
      5 "Medical Assistant"
     21 "Registered Nurse (BSN)"
     22 "Registered Nurse Midwife (BSN)"
     23 "Registered Psychiatric Nurse"
     24 "Registered Nurse with Diploma"
     25 "Enrolled Nurse"
     26 "Community Health Nurse"
     27 "Enrolled Midwife /Nurse Midwife Technical"
     28 "Enrolled Nurse Midwife"
     31 "Pharmacist"
     32 "Pharmacy Assistant"
     35 "Laboratory Technician"
     36 "Laboratory Assistant"
     37 "Radiology Technician"
     38 "Medical Imaging Technician"
     41 "Environment Health Officer"
     42 "Health Surveillance Assistant (HSA)"
     43 "HIV Testing and Counseling Counselors (NON-HSA)"
     44 "Dental Hygienist"
     71 "Other Community Health Workers"
     96 "Other"
     97 "No Technical Qualification"
     99 "Missing"
  /C032    
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
  /C501    
      0 "Saw provider immediately"
    998 "Don't know"
  /C502A   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502B   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502C   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502E   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502F   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502G   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502H   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502I   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502J   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502K   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502L   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C503    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C504    
      0 "No"
      1 "Yes"
  /C505    
   999998 "Don't know"
  /C507    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C508    
      1 "Inconvenient operating hours"
      2 "Bad reputation"
      3 "Don't like personnel"
      4 "No medicine"
      5 "Prefers to remain anonymous"
      6 "More expensive"
      7 "Referral"
     96 "Other"
     98 "Don't know"
  /C510    
      1 "Mother"
      2 "Father"
      3 "Sibling"
      4 "Aunt or uncle"
      5 "Grandparent"
      6 "Other"
  /C511    
     98 "Don't know"
  /C512    
      0 "Never attended school"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /C514    
      0 "Cannot read or write"
      1 "Read only"
      2 "Read and write"
      8 "Don't know"
  /C515    
      0 "No schooling"
      1 "Primary"
      2 "Post-primary/Technical"
      3 "Secondary"
      4 "Higher/University"
  /C517A   
   9797 "Inconsistent"
   9898 "Don't know"
  /C517B   
   9797 "Inconsistent"
   9898 "Don't know"
  /C518A   
   9797 "Inconsistent"
   9898 "Don't know"
  /C518B   
   9797 "Inconsistent"
   9898 "Don't know"
  /C520    
      1 "Very satisfied"
      2 "Somewhat satisfied"
      3 "Not satisfied"
  /C521    
      0 "No"
      1 "Yes"
      8 "DK"
  /C522    
      0 "No or incomplete observation"
      1 "Yes"
      2 "More than 1 reported as first"
  /SCDEPART
      0 "West"
      1 "...Metropolitan"
      2 "...Other West"
      3 "Southeast"
      4 "North"
      5 "Northeast"
      6 "Artibonite"
      7 "Central"
      8 "South"
      9 "Grand-Anse"
     10 "Northwest"
     11 "Nippes"
  /SCLOCAL 
      1 "Metropolitan"
      2 "Other cities"
      3 "Locality"
  /C202    
      1 "First visit"
      2 "Follow-up visit"
      8 "Don't know"
  /C203A   
      0 "No"
      1 "Yes"
  /C203B   
      0 "No"
      1 "Yes"
  /C203C   
      0 "No"
      1 "Yes"
  /C203D   
      0 "No"
      1 "Yes"
  /C203Y   
      0 "No"
      1 "Yes, no main symptoms"
  /C204A   
      0 "No"
      1 "Yes, none of first 3 problems"
  /C204B   
      0 "No"
      1 "Yes"
  /C204C   
      0 "No"
      1 "Yes"
  /C204D   
      0 "No"
      1 "Yes"
  /C204E   
      0 "No"
      1 "Yes"
  /C204F   
      0 "No"
      1 "Yes"
  /C204Y1  
      0 "No"
      1 "Yes, none of general danger signs"
  /C204Y2  
      0 "No"
      1 "Yes, none of HIV symptomatic indicators"
  /C205A   
      0 "No"
      1 "Yes"
  /C205B   
      0 "No"
      1 "Yes"
  /C205C   
      0 "No"
      1 "Yes"
  /C205D   
      0 "No"
      1 "Yes"
  /C205E   
      0 "No"
      1 "Yes"
  /C205F   
      0 "No"
      1 "Yes"
  /C205G   
      0 "No"
      1 "Yes"
  /C205H   
      0 "No"
      1 "Yes"
  /C205I   
      0 "No"
      1 "Yes"
  /C205J   
      0 "No"
      1 "Yes"
  /C205K   
      0 "No"
      1 "Yes"
  /C205M   
      0 "No"
      1 "Yes"
  /C205N   
      0 "No"
      1 "Yes"
  /C205P   
      0 "No"
      1 "Yes"
  /C205Q   
      0 "No"
      1 "Yes"
  /C205R   
      0 "No"
      1 "Yes"
  /C205S   
      0 "No"
      1 "Yes"
  /C205Y   
      0 "No"
      1 "Yes, none"
  /CF205A  
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF205M  
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF205N  
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF205XA 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF205XB 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF205XC 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF205XD 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF205XE 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /C206A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C206B   
      0 "No"
      1 "Yes"
  /C206C   
      0 "No"
      1 "Yes"
  /C206D   
      0 "No"
      1 "Yes"
  /C206E   
      0 "No"
      1 "Yes"
  /C206F   
      0 "No"
      1 "Yes"
  /C206G   
      0 "No"
      1 "Yes"
  /C206I   
      0 "No"
      1 "Yes"
  /C206Y   
      0 "No"
      1 "Yes, none"
  /C207A   
      0 "No"
      1 "Yes"
  /C207B   
      0 "No"
      1 "Yes"
  /C207C   
      0 "No"
      1 "Yes"
  /C207D   
      0 "No"
      1 "Yes"
  /C207E   
      0 "No"
      1 "Yes"
  /C207F   
      0 "No"
      1 "Yes"
  /C207Y   
      0 "No"
      1 "Yes, none"
  /C208B   
      0 "No"
      1 "Yes"
  /C208C   
      0 "No"
      1 "Yes"
  /C208D   
      0 "No"
      1 "Yes"
  /C208E   
      0 "No"
      1 "Yes"
  /C208F   
      0 "No"
      1 "Yes"
  /C208G   
      0 "No"
      1 "Yes"
  /C208H   
      0 "No"
      1 "Yes"
  /C208Y   
      0 "No"
      1 "Yes, none"
  /C209A   
      0 "No"
      1 "Yes"
  /C209B   
      0 "No"
      1 "Yes"
  /C209C   
      0 "No"
      1 "Yes"
  /C209D   
      0 "No"
      1 "Yes"
  /C209Y   
      0 "No"
      1 "Yes, none"
  /C211A   
      0 "No"
      1 "Yes"
  /C211B   
      0 "No"
      1 "Yes"
  /C212    
      0 "No"
      1 "Yes"
  /C213    
      1 "Child sent home"
      2 "Child referred to provider at same facility"
      3 "Child admitted to same facility"
      4 "Child sent to lab"
      5 "Child referred to other facility"
  /C220    
      1 "Yes, all with responses"
  /C221A   
      0 "No"
      1 "Yes, severity not reported"
  /C221C   
      0 "No"
      1 "Yes, severity not reported"
  /C221D   
      0 "No"
      1 "Yes, severity not reported"
  /C221E   
      0 "No"
      1 "Yes, severity not reported"
  /C221F   
      0 "No"
      1 "Yes, severity not reported"
  /C221Y   
      0 "No"
      1 "Yes, no respiratory dx"
  /C222A   
      0 "No"
      1 "Yes, severity not reported"
  /C222B   
      0 "No"
      1 "Yes, severity not reported"
  /C222C   
      0 "No"
      1 "Yes, severity not reported"
  /C222D   
      0 "No"
      1 "Yes, severity not reported"
  /C222E   
      0 "No"
      1 "Yes, severity not reported"
  /C222F   
      0 "No"
      1 "Yes, severity not reported"
  /C222G   
      0 "No"
      1 "Yes, severity not reported"
  /C222Y   
      0 "No"
      1 "Yes, no digestive dx"
  /C223A   
      0 "No/No dehydration"
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      8 "Don't know"
  /C224A   
      0 "No"
      1 "Yes, severity not reported"
  /C224B   
      0 "No"
      1 "Yes, severity not reported"
  /C224D   
      0 "No"
      1 "Yes, severity not reported"
  /C224Y   
      0 "No"
      1 "Yes, no malaria dx"
  /C225A   
      0 "No"
      1 "Yes, severity not reported"
  /C225B   
      0 "No"
      1 "Yes, severity not reported"
  /C225C   
      0 "No"
      1 "Yes, severity not reported"
  /C225D   
      0 "No"
      1 "Yes, severity not reported"
  /C225E   
      0 "No"
      1 "Yes, severity not reported"
  /C225F   
      0 "No"
      1 "Yes, severity not reported"
  /C225G   
      0 "No"
      1 "Yes, severity not reported"
  /C225Y   
      0 "No"
      1 "Yes, no fever/measles dx"
  /C226A   
      0 "No"
      1 "Yes, severity not reported"
  /C226B   
      0 "No"
      1 "Yes, severity not reported"
  /C226C   
      0 "No"
      1 "Yes, severity not reported"
  /C226D   
      0 "No"
      1 "Yes, severity not reported"
  /C226Y   
      0 "No"
      1 "Yes, no ear dx"
  /C227A   
      0 "No"
      1 "Yes, severity not reported"
  /C227B   
      0 "No"
      1 "Yes, severity not reported"
  /C227C   
      0 "No"
      1 "Yes, severity not reported"
  /C227D   
      0 "No"
      1 "Yes, severity not reported"
  /C227Y   
      0 "No"
      1 "Yes, no throat dx"
  /C228A   
      0 "No"
      1 "Yes, severity not reported"
  /C228B   
      0 "No"
      1 "Yes, severity not reported"
  /C228C   
      0 "No"
      1 "Yes, severity not reported"
  /C228D   
      0 "No"
      1 "Yes, severity not reported"
  /C228E   
      0 "No"
      1 "Yes, severity not reported"
  /C228Y   
      0 "No"
      1 "Yes, no other dx"
  /C230_36Y
      0 "No, some treatment prescribed"
      1 "Yes, no treatment prescribed during visit"
  /C230A   
      0 "No"
      1 "Yes"
  /C230B   
      0 "No"
      1 "Yes"
  /C230C   
      0 "No"
      1 "Yes"
  /C230E   
      0 "No"
      1 "Yes"
  /C230F   
      0 "No"
      1 "Yes"
  /C230G   
      0 "No"
      1 "Yes"
  /C230H   
      0 "No"
      1 "Yes"
  /C230I   
      0 "No"
      1 "Yes"
  /C230J   
      0 "No"
      1 "Yes"
  /C230K   
      0 "No"
      1 "Yes"
  /C230L   
      0 "No"
      1 "Yes"
  /C230M   
      0 "No"
      1 "Yes"
  /C230N   
      0 "No"
      1 "Yes"
  /C230Y   
      0 "No"
      1 "Yes, no general med given"
  /C232A   
      0 "No"
      1 "Yes"
  /C232B   
      0 "No"
      1 "Yes"
  /C232C   
      0 "No"
      1 "Yes"
  /C232D   
      0 "No"
      1 "Yes"
  /C232Y   
      0 "No"
      1 "Yes, no respiratory med given"
  /C233A   
      0 "No"
      1 "Yes"
  /C233C   
      0 "No"
      1 "Yes"
  /C233E   
      0 "No"
      1 "Yes"
  /C233F   
      0 "No"
      1 "Yes"
  /C234A   
      0 "No"
      1 "Yes"
  /C234B   
      0 "No"
      1 "Yes"
  /C234C   
      0 "No"
      1 "Yes"
  /C234D   
      0 "No"
      1 "Yes"
  /C234E   
      0 "No"
      1 "Yes"
  /C234F   
      0 "No"
      1 "Yes"
  /C234G   
      0 "No"
      1 "Yes"
  /C234H   
      0 "No"
      1 "Yes"
  /C234X   
      0 "No"
      1 "Yes"
  /C234Y   
      0 "No"
      1 "Yes, no malaria medication given"
  /C235A   
      0 "No"
      1 "Yes"
  /C235B   
      0 "No"
      1 "Yes"
  /C235C   
      0 "No"
      1 "Yes"
  /C235Y   
      0 "No"
      1 "Yes, no dehydration tx given"
  /C236A   
      0 "No"
      1 "Yes"
  /C236B   
      0 "No"
      1 "Yes"
  /C236C   
      0 "No"
      1 "Yes"
  /C236D   
      0 "No"
      1 "Yes"
  /C236E   
      0 "No"
      1 "Yes"
  /C236X   
      0 "No"
      1 "Yes"
  /C236Y   
      0 "No"
      1 "Yes, no other treatment/ advice"
  /C238    
      0 "No"
      1 "Yes, given"
      2 "Yes, referred"
  /C239    
      1 "Not due for immunization"
      2 "Vaccine not available"
      3 "Child too sick"
      4 "Not day for immunization"
      5 "Did not check for immunization"
      6 "Completed immunization schedule"
     96 "Other"
  /C251    
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
  /C254    
      1 "Fully specified date"
      2 "Year given"
      3 "Age given"
      6 "No information"
  /C255A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C255B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C255C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C255D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C255E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C255F   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C255G   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C256A   
      0 "No"
      1 "Yes"
  /C256B   
      0 "No"
      1 "Yes"
  /C256C   
      0 "No"
      1 "Yes"
  /C256D   
      0 "No"
      1 "Yes"
  /C256E   
      0 "No"
      1 "Yes"
  /C256X   
      0 "No"
      1 "Yes"
  /C256Y   
      0 "No"
      1 "Yes, no other reason for visit"
  /C257    
      0 "No"
      1 "Yes, within past week"
      2 "Yes, within past 2-4 weeks"
      3 "Yes, more than 4 weeks ago"
      4 "Yes, don't know when"
      8 "Don't know if other visits"
  /C258    
     98 "Don't know"
  /C259    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C260    
      1 "Return to facility"
      2 "Go to other facility"
      3 "Go to other health worker/pharmacy"
      4 "Go to traditional healer"
      5 "Wait"
      6 "Other"
      8 "Don't know"
  /C261A   
      0 "No"
      1 "Yes"
  /C261B   
      0 "No"
      1 "Yes"
  /C261C   
      0 "No"
      1 "Yes"
  /C261D   
      0 "No"
      1 "Yes"
  /C261E   
      0 "No"
      1 "Yes"
  /C261F   
      0 "No"
      1 "Yes"
  /C261G   
      0 "No"
      1 "Yes"
  /C261H   
      0 "No"
      1 "Yes"
  /C261X   
      0 "No"
      1 "Yes"
  /C261Y   
      0 "No"
      1 "Yes, no sign"
  /C261Z   
      0 "No"
      1 "Yes, don't know"
  /C262A   
      0 "No"
      1 "Yes"
  /C262B   
      0 "No"
      1 "Yes"
  /C262C   
      0 "No"
      1 "Yes"
  /C262D   
      0 "No"
      1 "Yes"
  /C262E   
      0 "No"
      1 "Yes"
  /C262F   
      0 "No"
      1 "Yes"
  /C262G   
      0 "No"
      1 "Yes"
  /C262X   
      0 "No"
      1 "Yes"
  /C262Y   
      0 "No"
      1 "Yes. no non-emergency return"
  /C262Z   
      0 "No"
      1 "Yes, don't know"
  /C263    
      0 "No"
      1 "Yes, gave medications"
      2 "Yes, gave prescription"
      3 "Yes, gave medications and prescriptions"
  /C264    
      0 "Has no medications, only prescriptions"
      1 "Has all medications"
      2 "Has some medications and some unfilled prescriptions"
  /C265    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C266    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C267    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C268    
      0 "No"
      1 "Yes, received injection"
      2 "Yes, received prescription for injection"
      8 "Don't know"
  /C270    
      0 "No"
      1 "Yes"
      8 "Can't remember"
  /C271    
      0 "No"
      1 "Yes"
  /C272    
      0 "No"
      1 "Yes"
  /C274    
      0 "Didn't discuss"
      1 "Give less than usual"
      2 "Give same as usual"
      3 "Give more than usual"
      4 "Give nothing/don't feed solids"
      8 "Not certain"
  /C275    
      0 "Didn't discuss"
      1 "Give less than usual"
      2 "Give same as usual"
      3 "Give more than usual"
      4 "Give nothing/don't feed fluids/breastmilk"
      8 "Not certain"
  /C276    
      0 "No"
      1 "Yes, observed"
      2 "Reported, not seen"
      8 "Don't know"
  /C280A   
      0 "No"
      1 "Yes"
  /C280B   
      0 "No"
      1 "Yes"
  /C280C   
      0 "No"
      1 "Yes"
  /C280D   
      0 "No"
      1 "Yes"
  /C281A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C281B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C281C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C281D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C281E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C282A   
      0 "No"
      1 "Yes"
  /C282B   
      0 "No"
      1 "Yes"
  /C282C   
      0 "No"
      1 "Yes"
  /C282Y   
      0 "No"
      1 "Yes, saw no one"
  /SXC103D 
     98 "Don't know"
  /SXC130  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /SXC131  
      0 "No"
      1 "Yes, date of visit observed"
      2 "Yes, but no date for vacc given on day of visit"
  /SXC132  
      0 "No"
      1 "Yes"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\HT7A\HTFP7AFLSR.sav'.
