DATA LIST FILE='C:\Countries\HT7A\HTSC7AFLSR.DAT' RECORDS=1
  /
  INV_ID      1-5   
  P_ID        6-7   
  OBS_N       8-9    (A)
  OBS_ID     10-12  
  C000       13-16   (A)
  C001       17-18  
  C002       19-22  
  C003       23-23  
  C004       24-28  
  C004P      29-30  
  C004CT     31-32   (A)
  C004CN     33-35  
  C005       36-43  
  C007       44-45  
  C008       46-47  
  C009A      48-51  
  C009B      52-55  
  C009C      56-58  
  C020A      59-59  
  C020B      60-60  
  C021       61-61  
  C022       62-62  
  C023       63-63  
  C024       64-65  
  C032       66-67  
  C033       68-71  
  C033D      72-73  
  C501       74-76  
  C502A      77-77  
  C502B      78-78  
  C502C      79-79  
  C502E      80-80  
  C502F      81-81  
  C502G      82-82  
  C502H      83-83  
  C502I      84-84  
  C502J      85-85  
  C502K      86-86  
  C502L      87-87  
  C503       88-88  
  C504       89-89  
  C505       90-95  
  C507       96-96  
  C508       97-98  
  C510       99-99  
  C511      100-101 
  C512      102-102 
  C514      103-103 
  C515      104-104 
  C517A     105-108 
  C517B     109-112 
  C518A     113-116 
  C518B     117-120 
  C520      121-122 
  C521      123-123 
  C522      124-124 
  SCDEPART  125-126 
  SCLOCAL   127-127 
  C301A     128-128 
  C301B     129-129 
  C302A     130-130 
  C302B     131-131 
  C302C     132-132 
  C302E     133-133 
  C302F     134-134 
  C302G     135-135 
  C302H     136-136 
  C302I     137-137 
  C302Y1    138-138 
  C302Y2    139-139 
  C303A     140-140 
  C303B     141-141 
  C303C     142-142 
  C303D     143-143 
  C303E     144-144 
  C303F     145-145 
  C303G     146-146 
  C303Y     147-147 
  CF303A    148-148 
  CF303B    149-149 
  CF303XA   150-150 
  C304A     151-151 
  C304B     152-152 
  C304C     153-153 
  C304Y     154-154 
  C305A     155-155 
  C305B     156-156 
  C305C     157-157 
  C305D     158-158 
  C305E     159-159 
  C305F     160-160 
  C305G     161-161 
  C305Y     162-162 
  C306A     163-163 
  C306B     164-164 
  C306C     165-165 
  C306D     166-166 
  C306E     167-167 
  C306F     168-168 
  C306G     169-169 
  C306H     170-170 
  C306I     171-171 
  C306J     172-172 
  C306K     173-173 
  C306L     174-174 
  C306O     175-175 
  C306P     176-176 
  C306Q     177-177 
  C306R     178-178 
  C306S     179-179 
  C306X     180-180 
  C306Y     181-181 
  C307A     182-182 
  C307B     183-183 
  C307C     184-184 
  C307D     185-185 
  C307E     186-186 
  C307F     187-187 
  C307Y     188-188 
  C308A     189-189 
  C308B     190-190 
  C308C     191-191 
  C308D     192-192 
  C308E     193-193 
  C308Y     194-194 
  C309A     195-195 
  C309B     196-196 
  C309C     197-197 
  C309D     198-198 
  C309E     199-199 
  C309Y     200-200 
  C310A     201-201 
  C310B     202-202 
  C310C     203-203 
  C310D     204-204 
  C310E     205-205 
  C310F     206-206 
  C310Y     207-207 
  C311A     208-208 
  C311B     209-209 
  C311C     210-210 
  C311D     211-211 
  C311E     212-212 
  C311F     213-213 
  C311Y     214-214 
  C313A     215-215 
  C313B     216-216 
  C313C     217-217 
  C313Y     218-218 
  C314A     219-219 
  C314B     220-220 
  C314C     221-221 
  C314D     222-222 
  C314E     223-223 
  C314Y     224-224 
  C315A     225-225 
  C315C     226-226 
  C315D     227-227 
  C315E     228-228 
  C315F     229-229 
  C315G     230-230 
  C315H     231-231 
  C315Y     232-232 
  C316      233-233 
  C317      234-234 
  C318      235-235 
  C319      236-236 
  C320      237-238 
  C321      239-239 
  C322      240-240 
  C323A     241-241 
  C323B     242-242 
  C323C     243-243 
  C323D     244-244 
  C323E     245-245 
  C323F     246-246 
  C323G     247-247 
  C323H     248-248 
  C323I     249-249 
  C323J     250-250 
  C323K     251-251 
  C323L     252-252 
  C323M1    253-253 
  C323M     254-254 
  C323N     255-255 
  C323O     256-256 
  C324      257-257 
  C325A     258-258 
  C325B     259-259 
  C325C     260-260 
  C325D     261-261 
  C325E     262-262 
  C325F     263-263 
  C325G     264-264 
  C325H     265-265 
  C325I     266-266 
  C325I2    267-267 
  C325J     268-268 
  C325K     269-269 
  C325L     270-270 
  C325M     271-271 
  C325N     272-272 
  C325N2    273-273 
  C325O     274-274 
  C325O2    275-275 
  C325P     276-276 
  C325Q     277-277 
  C325R     278-278 
  C325S     279-279 
  C325T     280-280 
  C325U     281-281 
  C325V     282-282 
  C325W     283-283 
  C325XA    284-284 
  C325XB    285-285 
  C325XC    286-286 
  C325Y     287-287 
  C326      288-288 
  C327A     289-289 
  C327B     290-290 
  C327C     291-291 
  C327C2    292-292 
  C327C3    293-293 
  C327D     294-294 
  C327D2    295-295 
  C327E     296-296 
  C327E2    297-297 
  C327F     298-298 
  C327G     299-299 
  C327H     300-300 
  C327I     301-301 
  C327J     302-302 
  C327K     303-303 
  C327L     304-304 
  C327M     305-305 
  C328      306-306 
  C329      307-307 
  C330A     308-308 
  C330B     309-309 
  C330C     310-310 
  C330D     311-311 
  C330E     312-312 
  C330F     313-313 
  C330G     314-314 
  C330H     315-315 
  C330I     316-316 
  C330J     317-317 
  C330K     318-318 
  C330L     319-319 
  C330M     320-320 
  C330N     321-321 
  C330O     322-322 
  C330P     323-323 
  C330P2    324-324 
  C330Q     325-325 
  C330R     326-326 
  C330S     327-327 
  C330T     328-328 
  C330U     329-329 
  C330V     330-330 
  C330W     331-331 
  C330XA    332-332 
  C330XB    333-333 
  C331      334-334 
  C340      335-335 
  C341      336-336 
  C342      337-337 
  C345      338-338 
  C346      339-339 
  C347      340-340 
  C348      341-341 
  C351      342-342 
  C352A     343-343 
  C352B     344-344 
  C352C     345-345 
  C352D     346-346 
  C352E     347-347 
  C352F     348-348 
  C352G     349-349 
  C352H     350-350 
  C352I     351-351 
  C352J     352-352 
  C352K     353-353 
  C352L     354-354 
  C352O     355-355 
  C352P     356-356 
  C352Q     357-357 
  C352R     358-358 
  C352S     359-359 
  C352X     360-360 
  C353A     361-361 
  C353B     362-362 
  C353B2    363-363 
  C353C     364-364 
  C354      365-365 
  C355      366-366 
  C356      367-367 
  C357A     368-368 
  C357B     369-369 
  C357C     370-370 
  C357D     371-371 
  C357E     372-372 
  C357F     373-373 
  C357G     374-374 
  C357H     375-375 
  C357I     376-376 
  C357J     377-377 
  C357K     378-378 
  C357L     379-379 
  C357O     380-380 
  C357P     381-381 
  C357Q     382-382 
  C357R     383-383 
  C357S     384-384 
  C357X     385-385 
  C358      386-386 
  C359A     387-387 
  C359B     388-388 
  C359C     389-389 
  C359D     390-390 
  C359E     391-391 
  C359F     392-392 
  C359G     393-393 
  C359H     394-394 
  C359I     395-395 
  C359J     396-396 
  C359K     397-397 
  C359L     398-398 
  C359O     399-399 
  C359P     400-400 
  C359Q     401-401 
  C359R     402-402 
  C359S     403-403 
  C359X     404-404 
  C359Y     405-405 
  C360A     406-406 
  C360B     407-407 
  C360C     408-408 
  C360D     409-409 
  C360E     410-410 
  C360F     411-411 
  C360G     412-412 
  C360H     413-413 
  C360I     414-414 
  C360J     415-415 
  C360K     416-416 
  C360L     417-417 
  C360O     418-418 
  C360P     419-419 
  C360Q     420-420 
  C360R     421-421 
  C360S     422-422 
  C360X     423-423 
  C360Y     424-424 
  C361      425-425 
  C362A     426-426 
  C362B     427-427 
  C362C     428-428 
  C362D     429-429 
  C363A     430-430 
  C363D     431-431 
  C363E     432-432 
  C363G     433-433 
  C363I     434-434 
  C363J     435-435 
  C363J2    436-436 
  C363K     437-437 
  C363O1    438-438 
  C363O2    439-439 
  C363O3    440-440 
  C363O3A   441-441 
  C363O4    442-442 
  C363O5    443-443 
  C363P     444-444 
  C363Q1    445-445 
  C363Q2    446-446 
  C363R1    447-447 
  C363R2    448-448 
  SXF107A   449-449 
  SXF107B   450-450 
  SXF107C   451-451 
  SXF107D   452-452 
  SXF107E   453-453 
  SXF107F   454-454 
  SXF107G   455-455 
  SXF107H   456-456 
  SXF107I   457-457 
  SXF107J   458-458 
  SXF107K   459-459 
  SXF107X   460-460 
 .
VARIABLE LABELS
   INV_ID   "INVENTORY ID"
  /P_ID     "Unit/Provider line number ID"
  /OBS_N    "Client type code"
  /OBS_ID   "Client ID"
  /C000     "Survey phase"
  /C001     "Department (Country-specific)"
  /C002     "Commune (Country-specific)"
  /C003     "Urban/rural"
  /C004     "Facility number"
  /C004P    "Provider line number"
  /C004CT   "Client type code (alpha)"
  /C004CN   "Client ID number"
  /C005     "Sample weight"
  /C007     "Facility type (Country-specific)"
  /C008     "Facility managing authority (Country-specific)"
  /C009A    "Interviewer for observation"
  /C009B    "Interviewer for exit interview"
  /C009C    "NA - Keyer"
  /C020A    "Result of observation"
  /C020B    "Result of exit interview"
  /C021     "Type of client"
  /C022     "Sex of provider"
  /C023     "Sex of client/sick child"
  /C024     "Technical qualification of provider (Country-specific within ranges)"
  /C032     "Month of observation/interview"
  /C033     "Year of observation/interview"
  /C033D    "Day of observation/interview"
  /C501     "Duration of wait before being seen"
  /C502A    "Client problem during visit: Time had to wait"
  /C502B    "Client problem during visit: Ability to discuss problems/concerns"
  /C502C    "Client problem during visit: Amount of explanation for problem/tx"
  /C502E    "Client problem during visit: Visual privacy"
  /C502F    "Client problem during visit: Auditory privacy"
  /C502G    "Client problem during visit: Availability of medicines at facility"
  /C502H    "Client problem during visit: Hours of service"
  /C502I    "Client problem during visit: Days of service"
  /C502J    "Client problem during visit: Cleanliness of facility"
  /C502K    "Client problem during visit: Staff treatment of client"
  /C502L    "Client problem during visit: Cost"
  /C503     "Part of prepayment plan/insurance that pays part of cost"
  /C504     "Charged for services today"
  /C505     "Total amount paid in Gourdes"
  /C507     "Facility nearest to home"
  /C508     "Reason did not go to nearest facility"
  /C510     "Caretaker relationship to sick child (Sick child exit only)"
  /C511     "Age of client (caretaker of client)"
  /C512     "Highest level of education attended"
  /C514     "Literacy level"
  /C515     "Country reported highest level of education attended (CS)"
  /C517A    "Time observation interview began"
  /C517B    "Time observation interview ended"
  /C518A    "Time exit interview began"
  /C518B    "Time exit interview ended"
  /C520     "Opinion of services given today"
  /C521     "Would recommend to friend/family member"
  /C522     "First observation for this provider for this service"
  /SCDEPART "CS - Region with West separated for metropolitan and other"
  /SCLOCAL  "CS - Metropolitan/other cities/locality"
  /C301A    "Previous contact with provider at this FP clinic"
  /C301B    "Female client has ever been pregnant"
  /C302A    "All client history provided: Age"
  /C302B    "All client history provided: Number of living children"
  /C302C    "Female client history provided: Last delivery date/age of youngest child"
  /C302E    "Female client history  provided: Current pregnancy status"
  /C302F    "All client history provided: Desire for a child or more children"
  /C302G    "All client history provided: Desired timing for birth of next child"
  /C302H    "Female client history provided: Breastfeeding status"
  /C302I    "Female client history provided: Regularity of menstrual cycle"
  /C302Y1   "All client history provided: No history data collection observed"
  /C302Y2   "Female client history provided: No history data collection observed"
  /C303A    "Physical exam/health question asked: Blood pressure"
  /C303B    "Physical exam/health question asked: Client weighed"
  /C303C    "Physical exam/health question asked: Smoking status"
  /C303D    "Physical exam/health question asked: STI symptoms"
  /C303E    "Physical exam/health question asked: Chronic illnesses"
  /C303F    "Physical exam/health question asked: Look at client's health card"
  /C303G    "CS - Physical exam/health question asked: About medicines client is taking"
  /C303Y    "Physical exam/health question asked: No physical exam/ health questions asked"
  /CF303A   "Routine action in facility: Blood pressure"
  /CF303B   "Routine action in facility: Weigh client"
  /CF303XA  "Routine action in facility: Conduct group health education"
  /C304A    "Client privacy: Ensure visual privacy"
  /C304B    "Client privacy: Ensure auditory privacy"
  /C304C    "Client privacy: Assure client orally of confidentiality"
  /C304Y    "Client privacy: No privacy issues observed"
  /C305A    "Issues discussed: Partner's attitude toward FP"
  /C305B    "Issues discussed: Partner status (number, partner's number, partner absent)"
  /C305C    "Issues discussed: Risk of STIs"
  /C305D    "Issues discussed: Use of condoms to prevent STIs"
  /C305E    "Issues discussed: Use condoms with other method to avoid pregnancy and STIs"
  /C305F    "Issues discussed: Ask client about questions/concerns regarding current method(s)"
  /C305G    "Issues discussed: Client expressed concerns or asked questions"
  /C305Y    "Issues discussed: Observed no issues discussed"
  /C306A    "Method provided/ prescribed: Combined oral pill"
  /C306B    "Method provided/ prescribed: Progesterone only pill"
  /C306C    "Method provided/ prescribed: Oral pill type unknown"
  /C306D    "Method provided/ prescribed: Injectable (1 month)"
  /C306E    "Method provided/ prescribed: Injectable (2-3 months)"
  /C306F    "NA - Method provided/ prescribed: Injectable type unknown"
  /C306G    "Method provided/ prescribed: Implant"
  /C306H    "NA - Method provided/ prescribed: Implant 2nd type"
  /C306I    "Method provided/ prescribed: Male condom"
  /C306J    "Method provided/ prescribed: Female condom"
  /C306K    "Method provided/ prescribed: IUCD"
  /C306L    "Method provided/ prescribed: Emergency contraception"
  /C306O    "Method provided/ prescribed: Natural methods/Periodic abstinence (PA)"
  /C306P    "Method provided/ prescribed: LAM/breastfeeding"
  /C306Q    "Method provided/ prescribed: Vasectomy"
  /C306R    "Method provided/ prescribed: Female sterilization"
  /C306S    "Method provided/ prescribed: Cycle beads for SDM"
  /C306X    "Method provided/ prescribed: Other"
  /C306Y    "Method provided/ prescribed: No method"
  /C307A    "Information for pills or injections: How often/ when to take"
  /C307B    "Information for pills or injections: Menstrual changes"
  /C307C    "Information for pills or injections: Initial side effects"
  /C307D    "Information for pills or injections: What to do if forget pill or delay injection"
  /C307E    "Information for pills or injections: Method does not protect from STIs including HIV"
  /C307F    "Information for pills or injections: Should return to clinic if side effects persist"
  /C307Y    "Information for pills or injections: No information for users of pills/ injections"
  /C308A    "Information for implant: Good for 3-5 years"
  /C308B    "Information for implant: Menstrual changes"
  /C308C    "Information for implant: Initial side effects"
  /C308D    "Information for implant: Method does not protect against STIs including HIV"
  /C308E    "Information for implant: Return if side effects persist"
  /C308Y    "Information for implant: No information for users of implant"
  /C309A    "Information for condoms: Cannot use if allergic to latex"
  /C309B    "Information for condoms: Can be used only once"
  /C309C    "Information for condoms: Lubricants may be used"
  /C309D    "Information for condoms: Use as backup"
  /C309E    "Information for condoms: Dual protection"
  /C309Y    "Information for condoms: No information for users of condom"
  /C310A    "Information for IUCD: Check string after menstruation"
  /C310B    "Information for IUCD: May cause heavy bleeding or spotting"
  /C310C    "Information for IUCD: Good for up to 5 or 12 years"
  /C310D    "Information for IUCD: Return 3-6 weeks post insertion/after first menses"
  /C310E    "Information for IUCD: Return if side effects continue"
  /C310F    "Information for IUCD: Method does not protect against STIs including HIV"
  /C310Y    "Information for IUCD: No information for users of IUCD"
  /C311A    "Information for emergency contraception: Need 2nd dose if vomit within 2 hours"
  /C311B    "Information for emergency contraception: Late or light period, return for pregnancy check"
  /C311C    "Information for emergency contraception: First dose within 72 hours of contact"
  /C311D    "Information for emergency contraception: Second dose 12 hours after 1st dose"
  /C311E    "Information for emergency contraception: Do not repeat more often than 3 times/month"
  /C311F    "Information for emergency contraception: Method does not protect against STIs"
  /C311Y    "Information for emergency contraception: No information for users of emergency contraception"
  /C313A    "Information for periodic abstinence (PA): How to identify fertile period"
  /C313B    "Information for periodic abstinence (PA): No intercourse during fertile period without alternative method"
  /C313C    "Information for periodic abstinence (PA): Method does not protect against STIs including HIV"
  /C313Y    "Information for periodic abstinence (PA): No information for users of PA"
  /C314A    "Information for LAM: Slight risk of pregnancy during time before menstruation resumes"
  /C314B    "Information for LAM: Most effective with exclusive breastfeeding without menstruation"
  /C314C    "Information for LAM: Not effective after menstruation resumes"
  /C314D    "Information for LAM: Method does not protect against STIs including HIV"
  /C314E    "Information for LAM: Infant must be less than 6 months of age"
  /C314Y    "Information for LAM: No information for users of LAM"
  /C315A    "Information for sterilization (male and female): Intended to be permanent, slight risk of failure"
  /C315C    "Information for sterilization (male): Use of back-up method for 3 months after procedure"
  /C315D    "Information for sterilization (male): Partner is protected from pregnancy after 3 months"
  /C315E    "Information for sterilization (female): Protected from pregnancy immediately"
  /C315F    "Information for sterilization (male and female): Warning signs that may occur after surgery"
  /C315G    "Information for sterilization (male and female): Should return to clinic if experience warning signs"
  /C315H    "Information for sterilization (male and female): Method does not protect against STIs including HIV"
  /C315Y    "Information for sterilization (male and female): No information for users of sterilization"
  /C316     "Provider wrote on client health card"
  /C317     "Provider used visual aids"
  /C318     "Provider discussed return visit"
  /C319     "Clinical procedure: same provider or different"
  /C320     "Clinical procedure: type of provider"
  /C321     "Clinical procedure: sex of provider"
  /C322     "Pelvic exam performed"
  /C323A    "Before pelvic exam: Ensure visual privacy"
  /C323B    "Before pelvic exam: Ensure auditory privacy"
  /C323C    "Before pelvic exam: Explain procedure before starting"
  /C323D    "Before pelvic exam: Prepare all instruments before procedure"
  /C323E    "During pelvic exam: Use sterilized/HLD instruments"
  /C323F    "Before pelvic exam: Wash hands with soap before examination"
  /C323G    "Before pelvic exam: Put on new or disinfected latex gloves before examination"
  /C323H    "During pelvic exam: Ask client to relax muscles"
  /C323I    "During pelvic exam: Inspect external genitalia"
  /C323J    "During pelvic exam: Explain speculum procedure (if used)"
  /C323K    "During pelvic exam: Inspect cervix and vaginal mucosa"
  /C323L    "During pelvic exam: Perform bimanual exam"
  /C323M1   "After pelvic exam: Removed gloves"
  /C323M    "After pelvic exam: Wash hands after removing gloves"
  /C323N    "After pelvic exam: Wipe contaminated surfaces with disinfectant"
  /C323O    "After pelvic exam: Placed used instruments in disinfectant solution immediately after procedure"
  /C324     "IUCD procedures performed"
  /C325A    "Before IUCD procedures: Ensure visual privacy"
  /C325B    "Before IUCD procedures: Ensure auditory privacy"
  /C325C    "Before IUCD procedures: Explain procedure before starting"
  /C325D    "Before IUCD procedures: Reconfirm choice (with new client)"
  /C325E    "Before IUCD procedures: Verify client not pregnant (with new client)"
  /C325F    "Before IUCD procedures: Prepare all instruments"
  /C325G    "During IUCD procedures: Use sterilized/HLD instruments"
  /C325H    "Before IUCD procedures: Wash hands with soap before procedure"
  /C325I    "Before IUCD procedures: Put on new/disinfected latex gloves"
  /C325I2   "Before IUCD procedures: Clean cervix and vagina with antiseptic"
  /C325J    "During IUCD procedures: Perform speculum exam for RTIs or STIs before bimanual exam"
  /C325K    "During IUCD procedures: Perform bimanual exam"
  /C325L    "During IUCD procedures: Inspect cervix and vaginal mucosa"
  /C325M    "During IUCD procedures: Use a tenaculum"
  /C325N    "During IUCD procedures: Sound uterus before inserting IUCD"
  /C325N2   "During IUCD procedures: explained any of the above procedures"
  /C325O    "During IUCD procedures: Use no-touch technique for inserting IUCD"
  /C325O2   "After IUCD procedures: Remove gloves"
  /C325P    "After IUCD procedures: Wash hands after removing gloves"
  /C325Q    "After IUCD procedures: Ask client to wait and rest for 5 minutes after insertion"
  /C325R    "After IUCD procedures: Wipe contaminated surfaces with disinfectant"
  /C325S    "After IUCD procedures: Placed used instruments in disinfectant solution immediately after procedure"
  /C325T    "IUCD procedures: Instructed client to check string"
  /C325U    "IUCD procedures: Told client about spotting/bleeding"
  /C325V    "IUCD procedures: Told good for up to 5-10 years"
  /C325W    "IUCD procedures: Instructed to return in 3-6 weeks"
  /C325XA   "IUCD procedures: Instructed to return if side effects continue"
  /C325XB   "IUCD procedures: Client provided with card stating date of insertion and follow-up date"
  /C325XC   "IUCD procedures: (If IUCD removed) Showed the removed IUCD to client"
  /C325Y    "IUCD procedures: No client-provider interaction regarding instructions"
  /C326     "Contraceptive injection given"
  /C327A    "Before injection: Reconfirm choice (with new client)"
  /C327B    "Before injection: Verify client not pregnant (with new client)"
  /C327C    "Before injection: Check client card to ensure correct timing"
  /C327C2   "Before injection: Ensured visual privacy"
  /C327C3   "Before injection: Ensure auditory privacy"
  /C327D    "Before injection: Wash hands with soap before giving injection"
  /C327D2   "Before injection: Prepare injection in clean location"
  /C327E    "During injection procedure: Use new syringe and needle from sterile sealed pack (disposables)"
  /C327E2   "During injection procedure: Provider observed opening new packet"
  /C327F    "During injection procedure: Remove needle from multiple dose vial"
  /C327G    "During injection procedure: Stir/mix bottle before drawing dose (DEPO)"
  /C327H    "During injection procedure: Clean/air-dry the injection site before injection"
  /C327I    "During injection procedure: Draw back plunger before giving injection"
  /C327J    "During injection procedure: Allow dose to self-disperse (no massage)"
  /C327K    "After injection: Dispose of sharps in puncture-resistant container"
  /C327L    "NA - After injection: Tell client not to massage injection site"
  /C327M    "NA - After injection: Tell client when to return for next injection"
  /C328     "Needle/syringe provided by facility or client"
  /C329     "Implant procedure"
  /C330A    "Before Implant procedure: Reconfirm choice (with new client)"
  /C330B    "Before Implant procedure: Verify client not pregnant (with new client)"
  /C330C    "Before Implant procedure: Ensure visual privacy"
  /C330D    "Before Implant procedure: Ensure auditory privacy"
  /C330E    "Before Implant procedure: Explain procedure before starting"
  /C330F    "Before Implant procedure: Prepare instruments before procedure"
  /C330G    "During Implant procedure: Use sterilized or HLD instruments"
  /C330H    "Before Implant procedure: Wash hands with soap before procedure"
  /C330I    "Before Implant procedure: Put on sterile gloves/maintain sterility during insertion"
  /C330J    "During Implant procedure: Clean skin with antiseptic"
  /C330K    "During Implant procedure: Use sterile towel to protect area"
  /C330L    "During Implant procedure: New or sterilized needle and syringe for local anesthetic"
  /C330M    "During Implant procedure: Allow time for anesthetic to work"
  /C330N    "After Implant procedure: Dispose of sharps in puncture-resistant container"
  /C330O    "After Implant procedure: Disinfect area"
  /C330P    "After Implant procedure: Places used instruments in disinfectant solution immediately after procedure"
  /C330P2   "After Implant procedure: Remove gloves"
  /C330Q    "After Implant procedure: Wash hands after removing gloves"
  /C330R    "After Implant procedure: Explain incision care and removal of bandage"
  /C330S    "After Implant procedure: Discuss return visit to remove plaster"
  /C330T    "Implant procedure: Provide card with date of implant and date of expiration"
  /C330U    "Implant procedure: Reinforce expectations about side effects"
  /C330V    "Implant procedure: (In case of removal) Showed each removed implant stick"
  /C330W    "Implant procedure: Told about menstrual changes"
  /C330XA   "Implant procedure: Client instructed that implant is good for 3-5 years"
  /C330XB   "Implant procedure: Client instructed to return if side effects persist"
  /C331     "Needle/syringe for implant provided by facility or client"
  /C340     "Family planning status at beginning of consult"
  /C341     "Principal reason for visit"
  /C342     "Current user: outcome of visit"
  /C345     "Not current user: outcome of visit"
  /C346     "Client left with method"
  /C347     "Reason client left with no method"
  /C348     "Provider updated client record"
  /C351     "Doing something to avoid pregnancy before today"
  /C352A    "FP method used current/last 6 months: Combined pill"
  /C352B    "FP method used current/last 6 months: Progestin-only pill"
  /C352C    "FP method used current/last 6 months: Pill (type unspecified)"
  /C352D    "FP method used current/last 6 months: Injectable (1 mo)"
  /C352E    "FP method used current/last 6 months: Injectable (2-3 month)"
  /C352F    "NA - FP method used current/last 6 months: Injectable (type unspecified)"
  /C352G    "FP method used current/last 6 months: Implant"
  /C352H    "NA - FP method used current/last 6 months: Implant 2nd type"
  /C352I    "FP method used current/last 6 months: Male condom"
  /C352J    "FP method used current/last 6 months: Female condom"
  /C352K    "FP method used current/last 6 months: IUCD"
  /C352L    "FP method used current/last 6 months: Emergency Contraception"
  /C352O    "FP method used current/last 6 months: Periodic abstinence (PA)"
  /C352P    "FP method used current/last 6 months: LAM"
  /C352Q    "FP method used current/last 6 months: Vasectomy"
  /C352R    "FP method used current/last 6 months: Female sterilization"
  /C352S    "FP method used current/last 6 months: Cycle beads for SDM"
  /C352X    "FP method used current/last 6 months: Other"
  /C353A    "Problem with method: Provider asked if problem existed"
  /C353B    "Problem with method: Client is having a problem with method"
  /C353B2   "Problem with method: Client mentioned problem to provider"
  /C353C    "Problem with method: Provider suggested an action to resolve it"
  /C354     "Client's outcome of visit"
  /C355     "Client considered switching to new method"
  /C356     "New user thought about method to start"
  /C357A    "FP method considered before today's visit: Combined pill"
  /C357B    "FP method considered before today's visit: Progestin-only pill"
  /C357C    "FP method considered before today's visit: Pill (type unspecified)"
  /C357D    "FP method considered before today's visit: Injectable (1 month)"
  /C357E    "FP method considered before today's visit: Injectable (2-3 month)"
  /C357F    "NA - FP method considered before today's visit: Injectable (type unspecified)"
  /C357G    "FP method considered before today's visit: Implant"
  /C357H    "NA - FP method considered before today's visit: Implant 2nd type"
  /C357I    "FP method considered before today's visit: Male condom"
  /C357J    "FP method considered before today's visit: Female condom"
  /C357K    "FP method considered before today's visit: IUCD"
  /C357L    "FP method considered before today's visit: Emergency Contraception"
  /C357O    "FP method considered before today's visit: Periodic abstinence (PA)"
  /C357P    "FP method considered before today's visit: LAM"
  /C357Q    "FP method considered before today's visit: Vasectomy"
  /C357R    "FP method considered before today's visit: Female sterilization"
  /C357S    "FP method considered before today's visit: Cycle beads for SDM"
  /C357X    "FP method considered before today's visit: Other"
  /C358     "Provider talked about any considered methods"
  /C359A    "FP method provider talked about: Combined pill"
  /C359B    "FP method provider talked about: Progestin-only pill"
  /C359C    "FP method provider talked about: Pill (type unspecified)"
  /C359D    "FP method provider talked about: Injectable (1 mo)"
  /C359E    "FP method provider talked about: Injectable (2-3 mo)"
  /C359F    "NA - FP method provider talked about: Injectable (type unspecified)"
  /C359G    "FP method provider talked about: Implant"
  /C359H    "NA - FP method provider talked about: Implant 2nd type"
  /C359I    "FP method provider talked about: Male condom"
  /C359J    "FP method provider talked about: Female condom"
  /C359K    "FP method provider talked about: IUD"
  /C359L    "FP method provider talked about: Emergency Contraception"
  /C359O    "FP method provider talked about: Periodic abstinence (PA)"
  /C359P    "FP method provider talked about: LAM/ breastfeeding"
  /C359Q    "FP method provider talked about: Vasectomy"
  /C359R    "FP method provider talked about: Female sterilization"
  /C359S    "FP method provider talked about: Cycle beads for SDM"
  /C359X    "FP method provider talked about: Other"
  /C359Y    "CS - FP method provider talked about: Did not mention other method"
  /C360A    "FP method received/prescribed today: Combined pill"
  /C360B    "FP method received/prescribed today: Progestin-only pill"
  /C360C    "FP method received/prescribed today: Pill (type unspecified)"
  /C360D    "FP method received/prescribed today: Combined injection (1 month)"
  /C360E    "FP method received/prescribed today: Injection progestin only ((2-3 mo - ex:Depo)"
  /C360F    "NA - FP method received/prescribed today: Injection (type unspecified)"
  /C360G    "FP method received/prescribed today: Implant"
  /C360H    "NA - FP method received/prescribed today: Implant 2nd type"
  /C360I    "FP method received/prescribed today: Male condom"
  /C360J    "FP method received/prescribed today: Female condom"
  /C360K    "FP method received/prescribed today: IUCD"
  /C360L    "FP method received/prescribed today: Emergency Contraception"
  /C360O    "FP method received/prescribed today: Periodic abstinence (PA)"
  /C360P    "FP method received/prescribed today: LAM/breastfeeding"
  /C360Q    "FP method received/prescribed today: Male sterilization"
  /C360R    "FP method received/prescribed today: Female sterilization"
  /C360S    "FP method received/prescribed today: Cycle beads for SDM"
  /C360X    "FP method received/prescribed today: Other"
  /C360Y    "FP method received/prescribed today: No method"
  /C361     "FP method protects against STI and HIV/AIDS"
  /C362A    "During consult, provider: Explained how to use method"
  /C362B    "During consult, provider: Talked about possible side effects"
  /C362C    "During consult, provider: Advised what to do if problems occurred"
  /C362D    "During consult, provider: Told when to return for follow-up"
  /C363A    "Method-related question: (pill) Take pill daily"
  /C363D    "Method-related question: (Injectable combined) Duration of protection one month"
  /C363E    "Method-related question: (Injectable progestin-only) Duration of protection 2-3 months"
  /C363G    "Method-related question: (Implant) Duration of protection 3-7 years"
  /C363I    "Method-related question: (Male condom) Can be used only once"
  /C363J    "NA - Method-related question: (Female condom) Type of lubricant that can be used"
  /C363J2   "Method-related question: CS (Female condom) Can be used only once"
  /C363K    "Method-related question: (IUCD) Check string to make sure IUCD in place"
  /C363O1   "Method-related question: (Per abst/SDM) Fertile - body temperature rises"
  /C363O2   "Method-related question: (Per abst/SDM) Fertile - mucus in vagina"
  /C363O3   "Method-related question: (Per abst/SDM) Fertile - Days 12-16 of cycle"
  /C363O3A  "Method-related question: (Per abst/SDM) Fertile - White bead days/ Days 8-19 of cycle"
  /C363O4   "Method-related question: (Per abst/SDM) Fertile - Other"
  /C363O5   "Method-related question: (Per abst/SDM) Fertile - Don't know"
  /C363P    "Method-related question: (LAM) Can use method if menses resumes?"
  /C363Q1   "NA - Method-related question: (Vasectomy) After sterilization, how long to wait for protection from pregnancy?"
  /C363Q2   "Method-related question: CS (Vasectomy) After sterilization (& 3 mos) can impregnate woman?"
  /C363R1   "NA - Method-related question: (Female sterilization) After sterilization, how long to wait for protection from pregnancy?"
  /C363R2   "Method-related question: CS (Female sterilization) After sterilization, can become pregnant?"
  /SXF107A  "CS - Specific problem with method being used: Nausea"
  /SXF107B  "CS - Specific problem with method being used: Headache"
  /SXF107C  "CS - Specific problem with method being used: Spotting"
  /SXF107D  "CS - Specific problem with method being used: Hemhorraging"
  /SXF107E  "CS - Specific problem with method being used: Absence of menstrual period"
  /SXF107F  "CS - Specific problem with method being used: Cramps"
  /SXF107G  "CS - Specific problem with method being used: Heavy menstruation"
  /SXF107H  "CS - Specific problem with method being used: Infection"
  /SXF107I  "CS - Specific problem with method being used: Rejected"
  /SXF107J  "CS - Specific problem with method being used: Forgot to use"
  /SXF107K  "CS - Specific problem with method being used: Abdominal pain"
  /SXF107X  "CS - Specific problem with method being used: Other"
 .
MISSING VALUE
   C003     (9)
  /C022     (9)
  /C023     (9)
  /C501     (999)
  /C502A    (9)
  /C502B    (9)
  /C502C    (9)
  /C502E    (9)
  /C502F    (9)
  /C502G    (9)
  /C502H    (9)
  /C502I    (9)
  /C502J    (9)
  /C502K    (9)
  /C502L    (9)
  /C503     (9)
  /C504     (9)
  /C505     (999999)
  /C507     (9)
  /C508     (99)
  /C510     (9)
  /C511     (99)
  /C512     (9)
  /C514     (9)
  /C515     (9)
  /C517A    (9999)
  /C517B    (9999)
  /C518A    (9999)
  /C518B    (9999)
  /C520     (99)
  /C521     (9)
  /C301A    (9)
  /C301B    (9)
  /C302A    (9)
  /C302B    (9)
  /C302C    (9)
  /C302E    (9)
  /C302F    (9)
  /C302G    (9)
  /C302H    (9)
  /C302I    (9)
  /C302Y1   (9)
  /C302Y2   (9)
  /C303A    (9)
  /C303B    (9)
  /C303C    (9)
  /C303D    (9)
  /C303E    (9)
  /C303F    (9)
  /C303G    (9)
  /C303Y    (9)
  /C304A    (9)
  /C304B    (9)
  /C304C    (9)
  /C304Y    (9)
  /C305A    (9)
  /C305B    (9)
  /C305C    (9)
  /C305D    (9)
  /C305E    (9)
  /C305F    (9)
  /C305G    (9)
  /C305Y    (9)
  /C306A    (9)
  /C306B    (9)
  /C306C    (9)
  /C306D    (9)
  /C306E    (9)
  /C306F    (9)
  /C306G    (9)
  /C306H    (9)
  /C306I    (9)
  /C306J    (9)
  /C306K    (9)
  /C306L    (9)
  /C306O    (9)
  /C306P    (9)
  /C306Q    (9)
  /C306R    (9)
  /C306S    (9)
  /C306X    (9)
  /C306Y    (9)
  /C307A    (9)
  /C307B    (9)
  /C307C    (9)
  /C307D    (9)
  /C307E    (9)
  /C307F    (9)
  /C307Y    (9)
  /C308A    (9)
  /C308B    (9)
  /C308C    (9)
  /C308D    (9)
  /C308E    (9)
  /C308Y    (9)
  /C309A    (9)
  /C309B    (9)
  /C309C    (9)
  /C309D    (9)
  /C309E    (9)
  /C309Y    (9)
  /C310A    (9)
  /C310B    (9)
  /C310C    (9)
  /C310D    (9)
  /C310E    (9)
  /C310F    (9)
  /C310Y    (9)
  /C311A    (9)
  /C311B    (9)
  /C311C    (9)
  /C311D    (9)
  /C311E    (9)
  /C311F    (9)
  /C311Y    (9)
  /C313A    (9)
  /C313B    (9)
  /C313C    (9)
  /C313Y    (9)
  /C314A    (9)
  /C314B    (9)
  /C314C    (9)
  /C314D    (9)
  /C314E    (9)
  /C314Y    (9)
  /C315A    (9)
  /C315C    (9)
  /C315D    (9)
  /C315E    (9)
  /C315F    (9)
  /C315G    (9)
  /C315H    (9)
  /C315Y    (9)
  /C316     (9)
  /C317     (9)
  /C318     (9)
  /C319     (9)
  /C321     (9)
  /C322     (9)
  /C323A    (9)
  /C323B    (9)
  /C323C    (9)
  /C323D    (9)
  /C323E    (9)
  /C323F    (9)
  /C323G    (9)
  /C323H    (9)
  /C323I    (9)
  /C323J    (9)
  /C323K    (9)
  /C323L    (9)
  /C323M1   (9)
  /C323M    (9)
  /C323N    (9)
  /C323O    (9)
  /C324     (9)
  /C325A    (9)
  /C325B    (9)
  /C325C    (9)
  /C325D    (9)
  /C325E    (9)
  /C325F    (9)
  /C325G    (9)
  /C325H    (9)
  /C325I    (9)
  /C325I2   (9)
  /C325J    (9)
  /C325K    (9)
  /C325L    (9)
  /C325M    (9)
  /C325N    (9)
  /C325N2   (9)
  /C325O    (9)
  /C325O2   (9)
  /C325P    (9)
  /C325Q    (9)
  /C325R    (9)
  /C325S    (9)
  /C325T    (9)
  /C325U    (9)
  /C325V    (9)
  /C325W    (9)
  /C325XA   (9)
  /C325XB   (9)
  /C325XC   (9)
  /C325Y    (9)
  /C326     (9)
  /C327A    (9)
  /C327B    (9)
  /C327C    (9)
  /C327C2   (9)
  /C327C3   (9)
  /C327D    (9)
  /C327D2   (9)
  /C327E    (9)
  /C327E2   (9)
  /C327F    (9)
  /C327G    (9)
  /C327H    (9)
  /C327I    (9)
  /C327J    (9)
  /C327K    (9)
  /C327L    (9)
  /C327M    (9)
  /C328     (9)
  /C329     (9)
  /C330A    (9)
  /C330B    (9)
  /C330C    (9)
  /C330D    (9)
  /C330E    (9)
  /C330F    (9)
  /C330G    (9)
  /C330H    (9)
  /C330I    (9)
  /C330J    (9)
  /C330K    (9)
  /C330L    (9)
  /C330M    (9)
  /C330N    (9)
  /C330O    (9)
  /C330P    (9)
  /C330P2   (9)
  /C330Q    (9)
  /C330R    (9)
  /C330S    (9)
  /C330T    (9)
  /C330U    (9)
  /C330V    (9)
  /C330W    (9)
  /C330XA   (9)
  /C330XB   (9)
  /C331     (9)
  /C340     (9)
  /C341     (9)
  /C342     (9)
  /C345     (9)
  /C346     (9)
  /C347     (9)
  /C348     (9)
  /C351     (9)
  /C352A    (9)
  /C352B    (9)
  /C352C    (9)
  /C352D    (9)
  /C352E    (9)
  /C352F    (9)
  /C352G    (9)
  /C352H    (9)
  /C352I    (9)
  /C352J    (9)
  /C352K    (9)
  /C352L    (9)
  /C352O    (9)
  /C352P    (9)
  /C352Q    (9)
  /C352R    (9)
  /C352S    (9)
  /C352X    (9)
  /C353A    (9)
  /C353B    (9)
  /C353B2   (9)
  /C353C    (9)
  /C354     (9)
  /C355     (9)
  /C356     (9)
  /C357A    (9)
  /C357B    (9)
  /C357C    (9)
  /C357D    (9)
  /C357E    (9)
  /C357F    (9)
  /C357G    (9)
  /C357H    (9)
  /C357I    (9)
  /C357J    (9)
  /C357K    (9)
  /C357L    (9)
  /C357O    (9)
  /C357P    (9)
  /C357Q    (9)
  /C357R    (9)
  /C357S    (9)
  /C357X    (9)
  /C358     (9)
  /C359A    (9)
  /C359B    (9)
  /C359C    (9)
  /C359D    (9)
  /C359E    (9)
  /C359F    (9)
  /C359G    (9)
  /C359H    (9)
  /C359I    (9)
  /C359J    (9)
  /C359K    (9)
  /C359L    (9)
  /C359O    (9)
  /C359P    (9)
  /C359Q    (9)
  /C359R    (9)
  /C359S    (9)
  /C359X    (9)
  /C359Y    (9)
  /C360A    (9)
  /C360B    (9)
  /C360C    (9)
  /C360D    (9)
  /C360E    (9)
  /C360F    (9)
  /C360G    (9)
  /C360H    (9)
  /C360I    (9)
  /C360J    (9)
  /C360K    (9)
  /C360L    (9)
  /C360O    (9)
  /C360P    (9)
  /C360Q    (9)
  /C360R    (9)
  /C360S    (9)
  /C360X    (9)
  /C360Y    (9)
  /C361     (9)
  /C362A    (9)
  /C362B    (9)
  /C362C    (9)
  /C362D    (9)
  /C363A    (9)
  /C363D    (9)
  /C363E    (9)
  /C363G    (9)
  /C363I    (9)
  /C363J    (9)
  /C363J2   (9)
  /C363K    (9)
  /C363O1   (9)
  /C363O2   (9)
  /C363O3   (9)
  /C363O3A  (9)
  /C363O4   (9)
  /C363O5   (9)
  /C363P    (9)
  /C363Q1   (9)
  /C363Q2   (9)
  /C363R1   (9)
  /C363R2   (9)
  /SXF107A  (9)
  /SXF107B  (9)
  /SXF107C  (9)
  /SXF107D  (9)
  /SXF107E  (9)
  /SXF107F  (9)
  /SXF107G  (9)
  /SXF107H  (9)
  /SXF107I  (9)
  /SXF107J  (9)
  /SXF107K  (9)
  /SXF107X  (9)
 .
VALUE LABELS
   OBS_N   
   'AN' "ANC"
   'SC' "Child Sick"
   'FP' "Family Planning"
   'SI' "STI"
   'IN' "Injection"
   'DC' "Delivery"
   'LD' "Labor/Delivery"
  /C001    
      1 "West"
      2 "Southeast"
      3 "North"
      4 "Northeast"
      5 "Artibonite"
      6 "Central"
      7 "South"
      8 "Grand-Anse"
      9 "Northwest"
     10 "Nippes"
  /C002    
    111 "Port-Au-Prince"
    112 "Cité-Soleil/Delmas/Tabarre"
    113 "Carrefour"
    114 "Pétion-ville"
    115 "Kenscoff"
    116 "Gressier"
    121 "Léogâne"
    122 "Petit-Goâve"
    123 "Grand-Goâve"
    131 "Croix-des-Bouquets"
    132 "Thomazeau"
    133 "Ganthier"
    134 "Cornillon"
    135 "Fonds-Verrettes"
    141 "Arcahaie"
    142 "Cabaret"
    151 "Anse-à-Galets"
    152 "Pointe-à-Raquettes"
    211 "Jacmel"
    212 "Marigot"
    213 "Cayes-Jacmel"
    214 "La Vallée"
    221 "Bainet"
    222 "Côtes-de-Fer"
    231 "Belle-Anse"
    232 "Grand-Gosier"
    233 "Thiotte"
    234 "Anse-à-Pitres"
    311 "Cap-Haïtien"
    312 "Quartier-Morin"
    313 "Limonade"
    321 "Acul-du-Nord"
    322 "Plaine-du-Nord"
    323 "Milot"
    331 "Grande-Rivière"
    332 "Bahon"
    341 "Saint-Raphaël"
    342 "Dondon"
    343 "Ranquitte"
    344 "Pignon"
    345 "La Victoire"
    351 "Borgne"
    352 "Port-Margot"
    361 "Limbé"
    362 "Bas-Limbé"
    371 "Plaisance"
    372 "Pilate"
    411 "Fort-Liberté"
    412 "Ferrier"
    413 "Perches"
    421 "Ouanaminthe"
    422 "Capotille"
    423 "Mont-Organisé"
    431 "Trou-du-Nord"
    432 "Sainte-Suzanne"
    433 "Terrier-Rouge"
    434 "Caracol"
    441 "Vallières"
    442 "Carice"
    443 "Mombin-Crochu"
    511 "Gonaïves"
    512 "Ennery"
    513 "L'Estère"
    521 "Gros-Morne"
    522 "Terre-Neuve"
    523 "Anse-Rouge"
    531 "Saint-Marc"
    532 "Verrettes"
    533 "La Chapelle"
    541 "Dessalines"
    542 "Petite-Rivière de l'Artibonite"
    543 "Grande Saline"
    544 "Desdunes"
    551 "Saint-Michel"
    552 "Marmelade"
    611 "Hinche"
    612 "Maïssade"
    613 "Thomonde"
    614 "Cerca-Cavajal"
    621 "Mirebalais"
    622 "Saut-d'Eau"
    623 "Boucan-Carré"
    631 "Lascahobas"
    632 "Belladère"
    633 "Savanette"
    641 "Cerca-La-Source"
    642 "Thomassique"
    711 "Les Cayes"
    712 "Torbeck"
    713 "Chantal"
    714 "Camp-Perrin"
    715 "Maniche"
    716 "Île-à-Vache"
    721 "Port-Salut"
    722 "Saint-Jean"
    723 "Arniquet"
    731 "Aquin"
    732 "Saint-Louis du Sud"
    733 "Cavaillon"
    741 "Côteaux"
    742 "Port-à-Piment"
    743 "Roche-à-Bateau"
    751 "Chardonnières"
    752 "Les Anglais"
    753 "Tiburon"
    811 "Jérémie"
    812 "Abricots"
    813 "Bonbon"
    814 "Moron"
    815 "Chambellan"
    821 "Anse-d'Hainault"
    822 "Dame-Marie"
    823 "Les Irois"
    831 "Corail"
    832 "Roseaux"
    833 "Beaumont"
    834 "Pestel"
    911 "Port-de-Paix"
    912 "La Tortue"
    913 "Bassin-Bleu"
    914 "Chansolme"
    921 "St-Ls-du-Nord'Ouest"
    922 "Anse-à-Foleur"
    931 "Môle-Saint-Nicolas"
    932 "Baie-de-Henne"
    933 "Bombardopolis"
    934 "Jean-Rabel"
   1001 "Fonds-des-Nègres"
   1002 "Arnaud"
   1003 "Grand-Boucan"
   1004 "Paillant"
   1005 "Plaisance"
   1041 "Miragoâne"
   1042 "Petite-Rivière de Nippes"
   1051 "Anse-à-Veau"
   1052 "Baradères"
   1053 "Petit-Trou"
   1054 "L'Asile"
  /C003    
      1 "Urban"
      2 "Rural"
  /C004CT  
   'AN' "ANC"
   'SC' "Child Sick"
   'FP' "Family Planning"
   'SI' "STI"
   'IN' "Injection"
   'DC' "Delivery"
   'LD' "Labor/Delivery"
  /C007    
      1 "University hospital"
      2 "Department hospital"
      3 "Community reference hospital"
      4 "Other hospitals"
      5 "Health Center with lit"
      6 "Health Center without lit"
      7 "Dispensary/Community Health Center"
  /C008    
      1 "Government/public"
      2 "Private not for profit"
      3 "Private for profit"
      4 "Mixed"
  /C020A   
      0 "Refused by provider or client"
      1 "Complete"
      7 "Not returned from field"
  /C020B   
      0 "Refused by client"
      1 "Complete"
      2 "Sick child admitted, not possible to continue"
      7 "Not returned from field"
  /C021    
      1 "ANC"
      2 "Child Sick"
      3 "Family Planning"
      6 "CS - Labor/Delivery"
  /C022    
      1 "Male"
      2 "Female"
  /C023    
      1 "Male"
      2 "Female"
  /C024    
      1 "Generalist Medical Doctor"
      2 "Specialist Medical Doctor"
      3 "Clinical Officer (Degree Level)"
      4 "Clinical Technician (Diploma)"
      5 "Medical Assistant"
     21 "Registered Nurse (BSN)"
     22 "Registered Nurse Midwife (BSN)"
     23 "Registered Psychiatric Nurse"
     24 "Registered Nurse with Diploma"
     25 "Enrolled Nurse"
     26 "Community Health Nurse"
     27 "Enrolled Midwife /Nurse Midwife Technical"
     28 "Enrolled Nurse Midwife"
     31 "Pharmacist"
     32 "Pharmacy Assistant"
     35 "Laboratory Technician"
     36 "Laboratory Assistant"
     37 "Radiology Technician"
     38 "Medical Imaging Technician"
     41 "Environment Health Officer"
     42 "Health Surveillance Assistant (HSA)"
     43 "HIV Testing and Counseling Counselors (NON-HSA)"
     44 "Dental Hygienist"
     71 "Other Community Health Workers"
     96 "Other"
     97 "No Technical Qualification"
     99 "Missing"
  /C032    
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
  /C501    
      0 "Saw provider immediately"
    998 "Don't know"
  /C502A   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502B   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502C   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502E   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502F   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502G   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502H   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502I   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502J   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502K   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502L   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C503    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C504    
      0 "No"
      1 "Yes"
  /C505    
   999998 "Don't know"
  /C507    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C508    
      1 "Inconvenient operating hours"
      2 "Bad reputation"
      3 "Don't like personnel"
      4 "No medicine"
      5 "Prefers to remain anonymous"
      6 "More expensive"
      7 "Referral"
     96 "Other"
     98 "Don't know"
  /C510    
      1 "Mother"
      2 "Father"
      3 "Sibling"
      4 "Aunt or uncle"
      5 "Grandparent"
      6 "Other"
  /C511    
     98 "Don't know"
  /C512    
      0 "Never attended school"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /C514    
      0 "Cannot read or write"
      1 "Read only"
      2 "Read and write"
      8 "Don't know"
  /C515    
      0 "No schooling"
      1 "Primary"
      2 "Post-primary/Technical"
      3 "Secondary"
      4 "Higher/University"
  /C517A   
   9797 "Inconsistent"
   9898 "Don't know"
  /C517B   
   9797 "Inconsistent"
   9898 "Don't know"
  /C518A   
   9797 "Inconsistent"
   9898 "Don't know"
  /C518B   
   9797 "Inconsistent"
   9898 "Don't know"
  /C520    
      1 "Very satisfied"
      2 "Somewhat satisfied"
      3 "Not satisfied"
  /C521    
      0 "No"
      1 "Yes"
      8 "DK"
  /C522    
      0 "No or incomplete observation"
      1 "Yes"
      2 "More than 1 reported as first"
  /SCDEPART
      0 "West"
      1 "...Metropolitan"
      2 "...Other West"
      3 "Southeast"
      4 "North"
      5 "Northeast"
      6 "Artibonite"
      7 "Central"
      8 "South"
      9 "Grand-Anse"
     10 "Northwest"
     11 "Nippes"
  /SCLOCAL 
      1 "Metropolitan"
      2 "Other cities"
      3 "Locality"
  /C301A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C301B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C302A   
      0 "No"
      1 "Yes"
  /C302B   
      0 "No"
      1 "Yes"
  /C302C   
      0 "No"
      1 "Yes"
  /C302E   
      0 "No"
      1 "Yes"
  /C302F   
      0 "No"
      1 "Yes"
  /C302G   
      0 "No"
      1 "Yes"
  /C302H   
      0 "No"
      1 "Yes"
  /C302I   
      0 "No"
      1 "Yes"
  /C302Y1  
      0 "No"
      1 "Yes, no client history for all clients"
  /C302Y2  
      0 "No"
      1 "Yes, no client history for female clients"
  /C303A   
      0 "No"
      1 "Yes"
  /C303B   
      0 "No"
      1 "Yes"
  /C303C   
      0 "No"
      1 "Yes"
  /C303D   
      0 "No"
      1 "Yes"
  /C303E   
      0 "No"
      1 "Yes"
  /C303F   
      0 "No"
      1 "Yes"
  /C303G   
      0 "No"
      1 "Yes"
  /C303Y   
      0 "No"
      1 "Yes, no physical exam/ health questions"
  /CF303A  
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF303B  
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF303XA 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /C304A   
      0 "No"
      1 "Yes"
  /C304B   
      0 "No"
      1 "Yes"
  /C304C   
      0 "No"
      1 "Yes"
  /C304Y   
      0 "No"
      1 "Yes, no privacy issues observed"
  /C305A   
      0 "No"
      1 "Yes"
  /C305B   
      0 "No"
      1 "Yes"
  /C305C   
      0 "No"
      1 "Yes"
  /C305D   
      0 "No"
      1 "Yes"
  /C305E   
      0 "No"
      1 "Yes"
  /C305F   
      0 "No"
      1 "Yes"
  /C305G   
      0 "No"
      1 "Yes"
  /C305Y   
      0 "No"
      1 "Yes, no discussion of issues observed"
  /C306A   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306B   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306C   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306D   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306E   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306F   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306G   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306H   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306I   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306J   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306K   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306L   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306O   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306P   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306Q   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306R   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306S   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306X   
      0 "No"
      1 "Yes, provided"
      2 "Yes, prescribed to be filled later/ different location"
  /C306Y   
      0 "No, something provided or prescribed"
      1 "Yes nothing provided or prescribed"
  /C307A   
      0 "No"
      1 "Yes"
  /C307B   
      0 "No"
      1 "Yes"
  /C307C   
      0 "No"
      1 "Yes"
  /C307D   
      0 "No"
      1 "Yes"
  /C307E   
      0 "No"
      1 "Yes"
  /C307F   
      0 "No"
      1 "Yes"
  /C307Y   
      0 "No"
      1 "Yes, no information for user"
  /C308A   
      0 "No"
      1 "Yes"
  /C308B   
      0 "No"
      1 "Yes"
  /C308C   
      0 "No"
      1 "Yes"
  /C308D   
      0 "No"
      1 "Yes"
  /C308E   
      0 "No"
      1 "Yes"
  /C308Y   
      0 "No"
      1 "Yes, no information for user"
  /C309A   
      0 "No"
      1 "Yes"
  /C309B   
      0 "No"
      1 "Yes"
  /C309C   
      0 "No"
      1 "Yes"
  /C309D   
      0 "No"
      1 "Yes"
  /C309E   
      0 "No"
      1 "Yes"
  /C309Y   
      0 "No"
      1 "Yes, no information for user"
  /C310A   
      0 "No"
      1 "Yes"
  /C310B   
      0 "No"
      1 "Yes"
  /C310C   
      0 "No"
      1 "Yes"
  /C310D   
      0 "No"
      1 "Yes"
  /C310E   
      0 "No"
      1 "Yes"
  /C310F   
      0 "No"
      1 "Yes"
  /C310Y   
      0 "No"
      1 "Yes, no information for user"
  /C311A   
      0 "No"
      1 "Yes"
  /C311B   
      0 "No"
      1 "Yes"
  /C311C   
      0 "No"
      1 "Yes"
  /C311D   
      0 "No"
      1 "Yes"
  /C311E   
      0 "No"
      1 "Yes"
  /C311F   
      0 "No"
      1 "Yes"
  /C311Y   
      0 "No"
      1 "Yes, no information for user"
  /C313A   
      0 "No"
      1 "Yes"
  /C313B   
      0 "No"
      1 "Yes"
  /C313C   
      0 "No"
      1 "Yes"
  /C313Y   
      0 "No"
      1 "Yes, no information for user"
  /C314A   
      0 "No"
      1 "Yes"
  /C314B   
      0 "No"
      1 "Yes"
  /C314C   
      0 "No"
      1 "Yes"
  /C314D   
      0 "No"
      1 "Yes"
  /C314E   
      0 "No"
      1 "Yes"
  /C314Y   
      0 "No"
      1 "Yes, no information for user"
  /C315A   
      0 "No"
      1 "Yes"
  /C315C   
      0 "No"
      1 "Yes"
  /C315D   
      0 "No"
      1 "Yes"
  /C315E   
      0 "No"
      1 "Yes"
  /C315F   
      0 "No"
      1 "Yes"
  /C315G   
      0 "No"
      1 "Yes"
  /C315H   
      0 "No"
      1 "Yes"
  /C315Y   
      0 "No"
      1 "Yes, no information for user"
  /C316    
      0 "No"
      1 "Yes"
  /C317    
      0 "No"
      1 "Yes"
  /C318    
      0 "No"
      1 "Yes"
  /C319    
      0 "No clinical procedure"
      1 "Yes, same provider"
      2 "Yes, different provider agreed"
      3 "Yes, different provider refused"
  /C320    
      1 "Generalist Medical Doctor"
      2 "Specialist Medical Doctor"
      3 "Clinical Officer (Degree Level)"
      4 "Clinical Technician (Diploma)"
      5 "Medical Assistant"
     21 "Registered Nurse (BSN)"
     22 "Registered Nurse Midwife (BSN)"
     23 "Registered Psychiatric Nurse"
     24 "Registered Nurse with Diploma"
     25 "Enrolled Nurse"
     26 "Community Health Nurse"
     27 "Enrolled Midwife /Nurse Midwife Technical"
     28 "Enrolled Nurse Midwife"
     31 "Pharmacist"
     32 "Pharmacy Assistant"
     35 "Laboratory Technician"
     36 "Laboratory Assistant"
     37 "Radiology Technician"
     38 "Medical Imaging Technician"
     41 "Environment Health Officer"
     42 "Health Surveillance Assistant (HSA)"
     43 "HIV Testing and Counseling Counselors (NON-HSA)"
     44 "Dental Hygienist"
     71 "Other Community Health Workers"
     96 "Other"
     97 "No Technical Qualification"
     99 "Missing"
  /C321    
      1 "Male"
      2 "Female"
  /C322    
      0 "No"
      1 "Yes"
  /C323A   
      0 "No"
      1 "Yes"
  /C323B   
      0 "No"
      1 "Yes"
  /C323C   
      0 "No"
      1 "Yes"
  /C323D   
      0 "No"
      1 "Yes"
  /C323E   
      0 "No"
      1 "Yes"
  /C323F   
      0 "No"
      1 "Yes"
  /C323G   
      0 "No"
      1 "Yes"
  /C323H   
      0 "No"
      1 "Yes"
  /C323I   
      0 "No"
      1 "Yes"
  /C323J   
      0 "No"
      1 "Yes"
  /C323K   
      0 "No"
      1 "Yes"
  /C323L   
      0 "No"
      1 "Yes"
  /C323M1  
      0 "No"
      1 "Yes"
  /C323M   
      0 "No"
      1 "Yes"
  /C323N   
      0 "No"
      1 "Yes"
  /C323O   
      0 "No"
      1 "Yes"
  /C324    
      0 "No"
      1 "Yes,Removed and inserted"
      2 "Yes,Inserted only"
      3 "Yes,Removed only"
      4 "IUD inspected only"
  /C325A   
      0 "No"
      1 "Yes"
  /C325B   
      0 "No"
      1 "Yes"
  /C325C   
      0 "No"
      1 "Yes"
  /C325D   
      0 "No"
      1 "Yes"
  /C325E   
      0 "No"
      1 "Yes"
  /C325F   
      0 "No"
      1 "Yes"
  /C325G   
      0 "No"
      1 "Yes"
  /C325H   
      0 "No"
      1 "Yes"
  /C325I   
      0 "No"
      1 "Yes"
  /C325I2  
      0 "No"
      1 "Yes"
  /C325J   
      0 "No"
      1 "Yes"
  /C325K   
      0 "No"
      1 "Yes"
  /C325L   
      0 "No"
      1 "Yes"
  /C325M   
      0 "No"
      1 "Yes"
  /C325N   
      0 "No"
      1 "Yes"
  /C325N2  
      0 "No"
      1 "Yes"
  /C325O   
      0 "No"
      1 "Yes"
  /C325O2  
      0 "No"
      1 "Yes"
  /C325P   
      0 "No"
      1 "Yes"
  /C325Q   
      0 "No"
      1 "Yes"
  /C325R   
      0 "No"
      1 "Yes"
  /C325S   
      0 "No"
      1 "Yes"
  /C325T   
      0 "No"
      1 "Yes"
  /C325U   
      0 "No"
      1 "Yes"
  /C325V   
      0 "No"
      1 "Yes"
  /C325W   
      0 "No"
      1 "Yes"
  /C325XA  
      0 "No"
      1 "Yes"
  /C325XB  
      0 "No"
      1 "Yes"
  /C325XC  
      0 "No"
      1 "Yes"
  /C325Y   
      0 "No"
      1 "Yes, none observed"
  /C326    
      0 "No"
      1 "Yes"
  /C327A   
      0 "No"
      1 "Yes"
  /C327B   
      0 "No"
      1 "Yes"
  /C327C   
      0 "No"
      1 "Yes"
  /C327C2  
      0 "No"
      1 "Yes"
  /C327C3  
      0 "No"
      1 "Yes"
  /C327D   
      0 "No"
      1 "Yes"
  /C327D2  
      0 "No"
      1 "Yes"
  /C327E   
      0 "No"
      1 "Yes"
  /C327E2  
      0 "No"
      1 "Yes"
  /C327F   
      0 "No"
      1 "Yes"
  /C327G   
      0 "No"
      1 "Yes"
  /C327H   
      0 "No"
      1 "Yes"
  /C327I   
      0 "No"
      1 "Yes"
  /C327J   
      0 "No"
      1 "Yes"
  /C327K   
      0 "No"
      1 "Yes"
  /C327L   
      0 "No"
      1 "Yes"
  /C327M   
      0 "No"
      1 "Yes"
  /C328    
      1 "Provided by facility"
      2 "Provided by client"
      8 "Don't know"
  /C329    
      0 "No"
      1 "Yes, removal and insertion"
      2 "Yes, insertion only"
      3 "Yes, removal only"
  /C330A   
      0 "No"
      1 "Yes"
  /C330B   
      0 "No"
      1 "Yes"
  /C330C   
      0 "No"
      1 "Yes"
  /C330D   
      0 "No"
      1 "Yes"
  /C330E   
      0 "No"
      1 "Yes"
  /C330F   
      0 "No"
      1 "Yes"
  /C330G   
      0 "No"
      1 "Yes"
  /C330H   
      0 "No"
      1 "Yes"
  /C330I   
      0 "No"
      1 "Yes"
  /C330J   
      0 "No"
      1 "Yes"
  /C330K   
      0 "No"
      1 "Yes"
  /C330L   
      0 "No"
      1 "Yes"
  /C330M   
      0 "No"
      1 "Yes"
  /C330N   
      0 "No"
      1 "Yes"
  /C330O   
      0 "No"
      1 "Yes"
  /C330P   
      0 "No"
      1 "Yes"
  /C330P2  
      0 "No"
      1 "Yes"
  /C330Q   
      0 "No"
      1 "Yes"
  /C330R   
      0 "No"
      1 "Yes"
  /C330S   
      0 "No"
      1 "Yes"
  /C330T   
      0 "No"
      1 "Yes"
  /C330U   
      0 "No"
      1 "Yes"
  /C330V   
      0 "No"
      1 "Yes"
  /C330W   
      0 "No"
      1 "Yes"
  /C330XA  
      0 "No"
      1 "Yes"
  /C330XB  
      0 "No"
      1 "Yes"
  /C331    
      1 "Provided by facility"
      2 "Provided by client"
      8 "Don't know"
  /C340    
      1 "Current user"
      2 "Nonuser, used in past"
      3 "Nonuser, no past use"
      8 "Not determined"
  /C341    
      1 "Resupply/routine follow-up"
      2 "Discuss problem with method"
      3 "Desire to change or discontinue FP"
      4 "Desire to change methods - no specific problem"
      5 "Desire to discontinue - no specific problem"
      6 "Discuss other physical problem"
  /C342    
      0 "Decided to stop using FP"
      1 "Continued with current method"
      2 "Switched method"
      3 "Planned method switch, not received, continued with current method"
      4 "Planned method switch, not received today, discontinue current method"
  /C345    
      0 "Did not decide on method"
      1 "Accepted to start method"
  /C346    
      0 "No"
      1 "Yes"
  /C347    
      0 "Decided to stop/ not begin using"
      1 "Method not in stock"
      2 "Requires appointment"
      3 "Delay receiving due to health problems"
      4 "Pregnancy status uncertain"
      6 "Other"
  /C348    
      0 "No"
      1 "Yes"
      2 "No individual card used"
      8 "Don't know"
  /C351    
      0 "No"
      1 "Yes, currently"
      2 "Yes, in last 6 months"
  /C352A   
      0 "No"
      1 "Yes"
  /C352B   
      0 "No"
      1 "Yes"
  /C352C   
      0 "No"
      1 "Yes"
  /C352D   
      0 "No"
      1 "Yes"
  /C352E   
      0 "No"
      1 "Yes"
  /C352F   
      0 "No"
      1 "Yes"
  /C352G   
      0 "No"
      1 "Yes"
  /C352H   
      0 "No"
      1 "Yes"
  /C352I   
      0 "No"
      1 "Yes"
  /C352J   
      0 "No"
      1 "Yes"
  /C352K   
      0 "No"
      1 "Yes"
  /C352L   
      0 "No"
      1 "Yes"
  /C352O   
      0 "No"
      1 "Yes"
  /C352P   
      0 "No"
      1 "Yes"
  /C352Q   
      0 "No"
      1 "Yes"
  /C352R   
      0 "No"
      1 "Yes"
  /C352S   
      0 "No"
      1 "Yes"
  /C352X   
      0 "No"
      1 "Yes"
  /C353A   
      0 "No"
      1 "Yes, asked"
  /C353B   
      0 "No"
      1 "Yes, having a problem"
  /C353B2  
      0 "No"
      1 "Yes, having a problem"
  /C353C   
      0 "No"
      1 "Yes, provider suggested action"
      2 "Client didn't mention problem to provider"
      3 "Client had no problem"
      8 "Don't know"
  /C354    
      1 "Continue or restart same method"
      2 "Switch methods"
      3 "Stop using method due to problems"
      4 "Stop using method no problems"
  /C355    
      0 "No"
      1 "Yes"
  /C356    
      0 "No"
      1 "Yes"
  /C357A   
      0 "No"
      1 "Yes"
  /C357B   
      0 "No"
      1 "Yes"
  /C357C   
      0 "No"
      1 "Yes"
  /C357D   
      0 "No"
      1 "Yes"
  /C357E   
      0 "No"
      1 "Yes"
  /C357F   
      0 "No"
      1 "Yes"
  /C357G   
      0 "No"
      1 "Yes"
  /C357H   
      0 "No"
      1 "Yes"
  /C357I   
      0 "No"
      1 "Yes"
  /C357J   
      0 "No"
      1 "Yes"
  /C357K   
      0 "No"
      1 "Yes"
  /C357L   
      0 "No"
      1 "Yes"
  /C357O   
      0 "No"
      1 "Yes"
  /C357P   
      0 "No"
      1 "Yes"
  /C357Q   
      0 "No"
      1 "Yes"
  /C357R   
      0 "No"
      1 "Yes"
  /C357S   
      0 "No"
      1 "Yes"
  /C357X   
      0 "No"
      1 "Yes"
  /C358    
      0 "No"
      1 "Yes"
  /C359A   
      0 "No"
      1 "Yes"
  /C359B   
      0 "No"
      1 "Yes"
  /C359C   
      0 "No"
      1 "Yes"
  /C359D   
      0 "No"
      1 "Yes"
  /C359E   
      0 "No"
      1 "Yes"
  /C359F   
      0 "No"
      1 "Yes"
  /C359G   
      0 "No"
      1 "Yes"
  /C359H   
      0 "No"
      1 "Yes"
  /C359I   
      0 "No"
      1 "Yes"
  /C359J   
      0 "No"
      1 "Yes"
  /C359K   
      0 "No"
      1 "Yes"
  /C359L   
      0 "No"
      1 "Yes"
  /C359O   
      0 "No"
      1 "Yes"
  /C359P   
      0 "No"
      1 "Yes"
  /C359Q   
      0 "No"
      1 "Yes"
  /C359R   
      0 "No"
      1 "Yes"
  /C359S   
      0 "No"
      1 "Yes"
  /C359X   
      0 "No"
      1 "Yes"
  /C359Y   
      0 "No, mention other method"
      1 "Yes, did not mention other method"
  /C360A   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360B   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360C   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360D   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360E   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360F   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360G   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360H   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360I   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360J   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360K   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360L   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360O   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360P   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360Q   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360R   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360S   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360X   
      0 "No"
      1 "Yes received"
      2 "Yes, received and prescribed"
      3 "Yes, prescribed only"
      4 "Continuing with method, received none"
  /C360Y   
      0 "No some method received or prescribed or continuing with current method"
      1 "Yes none"
  /C361    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C362A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C362B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C362C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C362D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C363A   
      1 "Once a day"
      2 "Other response"
      8 "Don't know"
  /C363D   
      1 "1 month"
      2 "Other response"
      8 "Don't know"
  /C363E   
      1 "2-3 months"
      2 "Other response"
      8 "Don't know"
  /C363G   
      1 "3-5 years"
      2 "Other response"
      8 "Don't know"
  /C363I   
      1 "Once"
      2 "Other response"
      8 "Don't know"
  /C363J   
      1 "Any oil or lubricant"
      2 "Other response"
      8 "Don't know"
  /C363J2  
      1 "Only once"
      2 "Other response"
      8 "Don't know"
  /C363K   
      1 "Check string"
      2 "Other response"
      8 "Don't know"
  /C363O1  
      0 "No, not mentioned"
      1 "Yes, body temperature rises"
  /C363O2  
      0 "No, not mentioned"
      1 "Yes, mucus in vagina"
  /C363O3  
      0 "No, not mentioned"
      1 "Yes, days 12-16 of cycle"
  /C363O3A 
      0 "No, not mentioned"
      1 "Yes, white bead days"
  /C363O4  
      0 "No, not mentioned"
      1 "Yes, other way"
  /C363O5  
      0 "No, mentioned some way"
      1 "Yes, doesn't know way to identify fertile days"
  /C363P   
      0 "No, cannot use"
      1 "Yes, can use"
      8 "Don't know"
  /C363Q1  
      1 "Immediate protection"
      2 "Wait 1-3 months"
      3 "Only after 3 months or 30 ejaculations"
      8 "Don't know"
  /C363Q2  
      0 "Cannot impregnate"
      1 "Yes, definitely can impregnate"
      2 "Slight risk of impregnating"
      8 "Don't know"
  /C363R1  
      1 "Immediate protection"
      2 "Wait 1-3 months"
      3 "Only after 3 months"
      8 "Don't know"
  /C363R2  
      0 "Cannot become pregnant"
      1 "Yes, definitely can become pregnant"
      2 "Slight risk of becoming pregnant"
      8 "Don't know"
  /SXF107A 
      0 "No"
      1 "Yes"
  /SXF107B 
      0 "No"
      1 "Yes"
  /SXF107C 
      0 "No"
      1 "Yes"
  /SXF107D 
      0 "No"
      1 "Yes"
  /SXF107E 
      0 "No"
      1 "Yes"
  /SXF107F 
      0 "No"
      1 "Yes"
  /SXF107G 
      0 "No"
      1 "Yes"
  /SXF107H 
      0 "No"
      1 "Yes"
  /SXF107I 
      0 "No"
      1 "Yes"
  /SXF107J 
      0 "No"
      1 "Yes"
  /SXF107K 
      0 "No"
      1 "Yes"
  /SXF107X 
      0 "No"
      1 "Yes"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\HT7A\HTSC7AFLSR.sav'.
