infix using "C:\HT7A\EXPORT RECODE\EXPORTEDFILES\HTDQR7AFLSR.dct"

label variable inv_id   "Facility identification"
label variable sf3121   "Facility provide data on number of ART patients to a reporting / information sys"
label variable sf3122_1 "Monitoring Evaluation System Interface (MESI) - Electronic"
label variable sf3122_2 "Monthly report ART - Paper"
label variable sf3122_3 "DATIM (Electronic platform for reporting to PEPFAR)"
label variable sf3122_4 "Other reporting / information system"
label variable sf3123_1 "ART register"
label variable sf3123_2 "EMR (Electronic Medical Record)"
label variable sf3123_3 "ARV dispensing cards (found at the pharmacy)"
label variable sf3123_4 "Other"
label variable sf3124   "Source document for monthly reporting the number of ART patients"
label variable sf3125_1a "Source document ART patients available - July 2017"
label variable sf3125_1b "Number of  ART patients, source documents - July 2017"
label variable sf3125_2a "Source document  ART patients available - August 2017"
label variable sf3125_2b "Number of  ART patients, source documents - August 2017"
label variable sf3125_3a "Source document  ART patients available - September 2017"
label variable sf3125_3b "Number of ART patients, source documents - September 2017"
label variable sf3126_1a "Monthly report  ART patients available - July 2017"
label variable sf3126_1b "Number of  ART patients, monthly report - July 2017"
label variable sf3126_2a "Monthly report  ART patients available - August 2017"
label variable sf3126_2b "Number of  ART patients, monthly report - August 2017"
label variable sf3126_3a "Monthly report  ART patients available - September 2017"
label variable sf3126_3b "Number of  ART patients, monthly report - September 2017"
label variable sf3127a  "Reason discrepancy source doc & monthly report: No deviation"
label variable sf3127b  "Reason discrepancy source doc & monthly report: Data entry errors"
label variable sf3127c  "Reason discrepancy source doc & monthly report: Calculation errors"
label variable sf3127d  "Reason discrepancy source doc & monthly report: Info for diff source docs not co"
label variable sf3127e  "Reason discrepancy source doc & monthly report: Source doc/monthly rep not avail"
label variable sf3127x  "Reason discrepancy source doc & monthly report: Other"
label variable sf3131   "Facility provide data on number of cases of tuberculosis to a reporting / inform"
label variable sf3132_1 "National Tuberculosis Program (NTP) System"
label variable sf3132_2 "Other reporting / information system"
label variable sf3133_1 "Tuberculosis case record pharmaco sensitive"
label variable sf3133_2 "Electronic patient record system"
label variable sf3133_3 "Other"
label variable sf3134   "Source document for the quarterly reporting of cases of tuberculosis"
label variable sf3135_1 "Missing data: year of registration"
label variable sf3135_2 "Missing data: sex"
label variable sf3135_3 "Missing data: age"
label variable sf3135_4 "Missing data: disease classification / anatomical site of the disease (type TB)"
label variable sf3135_5 "Missing data: type of patient/TB Treatment History / Patient Enrollment Group"
label variable sf3135_6 "Missing data: bacteriological results (Pre-treatment)"
label variable sf3135_7 "Missing data: number of cases missing at least one of the six data points"
label variable sf3136_1a "Source document TB available - Quarter 1"
label variable sf3136_1b "Number of notified TB cases, source document - Quarter 1"
label variable sf3137   "Number of TB cases transferred"
label variable sf3138   "TB cases that should have been reported"
label variable sf3139_1a "Quarterly report TB available - Quarter 1"
label variable sf3139_1b "Number of notified TB cases, quarterly report - Quarter 1"
label variable sf3140a  "Reason discrepancy source doc & quarterly report: No deviation"
label variable sf3140b  "Reason discrepancy source doc & quarterly report: Data entry errors"
label variable sf3140c  "Reason discrepancy source doc & quarterly report: Calculation errors"
label variable sf3140d  "Reason discrepancy source doc & quarterly report: Info for diff source docs not "
label variable sf3140e  "Reason discrepancy source doc & quarterly report: Source doc/monthly rep not ava"
label variable sf3140x  "Reason discrepancy source doc & quarterly report: Other"
label variable sf3151   "Facility provide data on number of cases of malaria to a reporting / information"
label variable sf3152   "Indicator definition used for reporting malaria cases"
label variable sf3153_1 "Single National Health Information System (SISNU)"
label variable sf3153_2 "National malaria program"
label variable sf3153_3 "Other reporting / information system"
label variable sf3154_1 "Morbidity register"
label variable sf3154_2 "Laboratory register"
label variable sf3154_3 "Other"
label variable sf3155   "Source document for monthly reporting cases of malaria"
label variable sf3156_1a "Source document malaria available - July 2017"
label variable sf3156_1b "Number of malaria cases, source documents - July 2017"
label variable sf3156_2a "Source document  malaria available - August 2017"
label variable sf3156_2b "Number of malaria cases, source documents - August 2017"
label variable sf3156_3a "Source document  malaria available - September 2017"
label variable sf3156_3b "Number of malaria cases, source documents - September 2017"
label variable sf3157_1a "Monthly report  malaria cases available - July 2017"
label variable sf3157_1b "Number of  malaria cases, monthly report - July 2017"
label variable sf3157_2a "Monthly report  malaria cases available - August 2017"
label variable sf3157_2b "Number of  malaria cases, monthly report - August 2017"
label variable sf3157_3a "Monthly report  malaria cases available - September 2017"
label variable sf3157_3b "Number of  malaria cases, monthly report - September 2017"
label variable sf3158a  "Reason discrepancy source doc & monthly report: No deviation"
label variable sf3158b  "Reason discrepancy source doc & monthly report: Data entry errors"
label variable sf3158c  "Reason discrepancy source doc & monthly report: Calculation errors"
label variable sf3158d  "Reason discrepancy source doc & monthly report: Info for diff source docs not co"
label variable sf3158e  "Reason discrepancy source doc & monthly report: Source doc/monthly rep not avail"
label variable sf3158x  "Reason discrepancy source doc & monthly report: Other"
label variable sf3160   "Responsibility for recording provision of services clearly attributed to staff c"
label variable sf3161   "Staff responsible for collecting data/compiling reports received appropriate tra"
label variable sf3162   "Staff asked to review aggregated figures before transmission to the next level"
label variable sf3163_1 "Standard definitions: number of visits antenatal care 1"
label variable sf3163_2 "Standard definitions: number of vaccinations DTP3 (Penta3)"
label variable sf3163_3 "Standard definitions: current ART patients"
label variable sf3163_4 "Standard definitions: tuberculosis cases notified"
label variable sf3163_5 "Standard definitions: confirmed cases of malaria treated"
label variable sf3163_6 "Standard definitions: other"
label variable sf3164_1 "Guidelines available: information supposed to be transmitted"
label variable sf3164_2 "Guidelines available: how reports are to be submitted"
label variable sf3164_3 "Guidelines available: to whom reports are to be submitted"
label variable sf3164_4 "Guidelines available: date on which reports are due"
label variable sf3165   "Instructions provided on how to complete the data collection/transmission forms/"
label variable sf3166_1a "Source document ART register: available"
label variable sf3166_1b "Source document ART register: standard or improvised"
label variable sf3166_1c "Source document ART register: up-to-date"
label variable sf3166_1d "Source document ART register: stock-out in the past 12 months"
label variable sf3166_2a "Source document tuberculosis pharmaco sensitive registry: available"
label variable sf3166_2b "Source document tuberculosis pharmaco sensitive registry: standard or improvised"
label variable sf3166_2c "Source document tuberculosis pharmaco sensitive registry: up-to-date"
label variable sf3166_2d "Source document tuberculosis pharmaco sensitive registry: stock-out in the past "
label variable sf3166_3a "Source document morbidity / laboratory register: available"
label variable sf3166_3b "Source document morbidity / laboratory register: standard or improvised"
label variable sf3166_3c "Source document morbidity / laboratory register: up-to-date"
label variable sf3166_3d "Source document morbidity / laboratory register: stock-out in the past 12 months"
label variable sf3166_4a "Source document other: available"
label variable sf3166_4b "Source document other: standard or improvised"
label variable sf3166_4c "Source document other: up-to-date"
label variable sf3166_4d "Source document other: stock-out in the past 12 months"
label variable sf3167   "Form used to report monthly/quarterly results of all health programs to SISNU"
label variable sf3168_1a "HIV / AIDS form: available"
label variable sf3168_1b "HIV / AIDS form: NHIS or Program"
label variable sf3168_1c "HIV / AIDS form: standard or improvised"
label variable sf3168_1d "HIV / AIDS form: out of stock in last 12 months"
label variable sf3168_2a "Tuberculosis form: available"
label variable sf3168_2b "Tuberculosis form: NHIS or Program"
label variable sf3168_2c "Tuberculosis form: standard or improvised"
label variable sf3168_2d "Tuberculosis form: out of stock in last 12 months"
label variable sf3168_3a "Malaria form: available"
label variable sf3168_3b "Malaria form: NHIS or Program"
label variable sf3168_3c "Malaria form: standard or improvised"
label variable sf3168_3d "Malaria form: out of stock in last 12 months"
label variable sf3168_4a "Other program area form: available"
label variable sf3168_4b "Other program area form: NHIS or Program"
label variable sf3168_4c "Other program area form: standard or improvised"
label variable sf3168_4d "Other program area form: out of stock in last 12 months"
label variable sf3169   "Facility have a systematic process to verify the quality of the reports compiled"
label variable sf3170   "Verifications of data accuracy performed regularly"
label variable sf3171   "Consistency checks of data syntheses are carried out regularly"
label variable sf3172   "Checks on punctuality/completeness of source documents performed regularly by su"
label variable sf3173   "Facility have written documentation on the results of data quality checks"
label variable sf3174   "Facility have written policy/guide on when/how to conduct data quality checks"
label variable sf3175   "Facility regularly receive supervision visits from the district level"
label variable sf3176   "Documented supervision visit to the facility in the last six months"
label variable sf3177   "Copies of sent reports are available in the facility for the last 12 months"
label variable sf3178   "Completed data collection forms are available for the last 12 months"
label variable sf3179   "Archived data is organized in a way that files are easy to access"
label variable sf3180   "Appropriate space available for safe organization of source documents/reports"
label variable sf3181   "Access to archived data is limited to the personnel concerned"
label variable sf3182   "Computer systems have clearly documented database administration procedure"
label variable sf3183   "Most recent backup date appropriate, given frequency of updating computer system"
label variable sf3184   "Computer system protected by a password"
label variable sf3185   "Relevant personal data stored in accordance with national privacy guidelines"
label variable sf3200   "Facility have community health workers attached to it"
label variable sf3201   "CHW could not perform their work due to stock-out of supplies during past week"
label variable sf3201a  "Agree to start community health worker list"
label variable sf3201b  "Total number of community health workers in the list"

#delimit ;
label define SF3121  
     0 "No"
     1 "Yes"
;
label define SF3122_1
     0 "No"
     1 "Yes"
;
label define SF3122_2
     0 "No"
     1 "Yes"
;
label define SF3122_3
     0 "No"
     1 "Yes"
;
label define SF3122_4
     0 "No"
     1 "Yes"
;
label define SF3123_1
     0 "No"
     1 "Yes"
;
label define SF3123_2
     0 "No"
     1 "Yes"
;
label define SF3123_3
     0 "No"
     1 "Yes"
;
label define SF3123_4
     0 "No"
     1 "Yes"
;
label define SF3124  
     1 "ART registry"
     2 "EMR (Medical Electronic Dossier)"
     3 "TARV dispensing sheets"
     6 "Other"
;
label define SF3125_1A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3125_2A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3125_3A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3126_1A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3126_2A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3126_3A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3127A 
     0 "No"
     1 "Yes"
;
label define SF3127B 
     0 "No"
     1 "Yes"
;
label define SF3127C 
     0 "No"
     1 "Yes"
;
label define SF3127D 
     0 "No"
     1 "Yes"
;
label define SF3127E 
     0 "No"
     1 "Yes"
;
label define SF3127X 
     0 "No"
     1 "Yes"
;
label define SF3131  
     0 "No"
     1 "Yes"
;
label define SF3132_1
     0 "No"
     1 "Yes"
;
label define SF3132_2
     0 "No"
     1 "Yes"
;
label define SF3133_1
     0 "No"
     1 "Yes"
;
label define SF3133_2
     0 "No"
     1 "Yes"
;
label define SF3133_3
     0 "No"
     1 "Yes"
;
label define SF3134  
     1 "Tuberculosis case record pharmaco sensitive"
     2 "Electronic patient record system"
     6 "Other"
;
label define SF3136_1A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3139_1A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3140A 
     0 "No"
     1 "Yes"
;
label define SF3140B 
     0 "No"
     1 "Yes"
;
label define SF3140C 
     0 "No"
     1 "Yes"
;
label define SF3140D 
     0 "No"
     1 "Yes"
;
label define SF3140E 
     0 "No"
     1 "Yes"
;
label define SF3140X 
     0 "No"
     1 "Yes"
;
label define SF3151  
     0 "No"
     1 "Yes"
;
label define SF3152  
     1 "Number of malaria cases treated"
     2 "Malaria cases confirmed"
     3 "Suspected cases of malaria tested"
     6 "Other"
;
label define SF3153_1
     0 "No"
     1 "Yes"
;
label define SF3153_2
     0 "No"
     1 "Yes"
;
label define SF3153_3
     0 "No"
     1 "Yes"
;
label define SF3154_1
     0 "No"
     1 "Yes"
;
label define SF3154_2
     0 "No"
     1 "Yes"
;
label define SF3154_3
     0 "No"
     1 "Yes"
;
label define SF3155  
     1 "Morbidity register"
     2 "Laboratory register"
     6 "Other"
;
label define SF3156_1A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3156_2A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3156_3A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3157_1A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3157_2A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3157_3A
     0 "No"
     1 "Yes, available and complete"
     2 "Yes, available but partially complete"
     3 "Yes, available but not captured"
;
label define SF3158A 
     0 "No"
     1 "Yes"
;
label define SF3158B 
     0 "No"
     1 "Yes"
;
label define SF3158C 
     0 "No"
     1 "Yes"
;
label define SF3158D 
     0 "No"
     1 "Yes"
;
label define SF3158E 
     0 "No"
     1 "Yes"
;
label define SF3158X 
     0 "No"
     1 "Yes"
;
label define SF3160  
     0 "Not attributed"
     1 "Yes"
     2 "Partially"
;
label define SF3161  
     0 "Not at all"
     1 "Yes"
     2 "To a large extent"
     3 "Partially"
;
label define SF3162  
     0 "Not attributed"
     1 "Yes"
     2 "Partially"
;
label define SF3163_1
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3163_2
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3163_3
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3163_4
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3163_5
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3163_6
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3164_1
     0 "Not at all"
     1 "Yes"
     2 "To a large extent"
     3 "Partially"
;
label define SF3164_2
     0 "Not at all"
     1 "Yes"
     2 "To a large extent"
     3 "Partially"
;
label define SF3164_3
     0 "Not at all"
     1 "Yes"
     2 "To a large extent"
     3 "Partially"
;
label define SF3164_4
     0 "Not at all"
     1 "Yes"
     2 "To a large extent"
     3 "Partially"
;
label define SF3165  
     0 "Not at all"
     1 "Yes"
     2 "To a large extent"
     3 "Partially"
;
label define SF3166_1A
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3166_1B
     1 "Standard"
     2 "Improvised"
;
label define SF3166_1C
     0 "No"
     1 "Yes"
;
label define SF3166_1D
     0 "No"
     1 "Yes"
;
label define SF3166_2A
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3166_2B
     1 "Standard"
     2 "Improvised"
;
label define SF3166_2C
     0 "No"
     1 "Yes"
;
label define SF3166_2D
     0 "No"
     1 "Yes"
;
label define SF3166_3A
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3166_3B
     1 "Standard"
     2 "Improvised"
;
label define SF3166_3C
     0 "No"
     1 "Yes"
;
label define SF3166_3D
     0 "No"
     1 "Yes"
;
label define SF3166_4A
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3166_4B
     1 "Standard"
     2 "Improvised"
;
label define SF3166_4C
     0 "No"
     1 "Yes"
;
label define SF3166_4D
     0 "No"
     1 "Yes"
;
label define SF3167  
     0 "No"
     1 "Yes"
;
label define SF3168_1A
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3168_1B
     1 "SISNU"
     2 "Program"
;
label define SF3168_1C
     1 "Standard"
     2 "Improvised"
;
label define SF3168_1D
     0 "No"
     1 "Yes"
;
label define SF3168_2A
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3168_2B
     1 "SISNU"
     2 "Program"
;
label define SF3168_2C
     1 "Standard"
     2 "Improvised"
;
label define SF3168_2D
     0 "No"
     1 "Yes"
;
label define SF3168_3A
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3168_3B
     1 "SISNU"
     2 "Program"
;
label define SF3168_3C
     1 "Standard"
     2 "Improvised"
;
label define SF3168_3D
     0 "No"
     1 "Yes"
;
label define SF3168_4A
     0 "No"
     1 "Yes"
     3 "Not applicable"
;
label define SF3168_4B
     1 "SISNU"
     2 "Program"
;
label define SF3168_4C
     1 "Standard"
     2 "Improvised"
;
label define SF3168_4D
     0 "No"
     1 "Yes"
;
label define SF3169  
     0 "Not at all"
     1 "Yes"
     2 "To a large extent"
     3 "Partially"
;
label define SF3170  
     0 "Not at all"
     1 "Yes"
     2 "Partially"
;
label define SF3171  
     0 "Not at all"
     1 "Yes"
     2 "Partially"
;
label define SF3172  
     0 "Not at all"
     1 "Yes"
     2 "Partially"
;
label define SF3173  
     0 "No"
     1 "Yes"
;
label define SF3174  
     0 "Not at all"
     1 "Yes"
     2 "To a large extent"
     3 "Partially"
;
label define SF3175  
     0 "Not at all"
     1 "Yes"
     2 "Partially"
;
label define SF3176  
     0 "Not at all"
     1 "Yes"
     2 "Partially"
;
label define SF3177  
     0 "Not at all"
     1 "Yes"
     2 "Partially"
;
label define SF3178  
     0 "Not at all"
     1 "Yes"
     2 "Partially"
;
label define SF3179  
     0 "No"
     1 "Yes"
;
label define SF3180  
     0 "Not at all"
     1 "Yes"
     2 "To a large extent"
     3 "Partially"
;
label define SF3181  
     0 "Not at all"
     1 "Yes"
     2 "Partially"
;
label define SF3182  
     0 "Not at all"
     1 "Yes"
     2 "To a large extent"
     3 "Partially"
     5 "There is no computer system"
;
label define SF3183  
     0 "No"
     1 "Yes"
;
label define SF3184  
     0 "No"
     1 "Yes"
;
label define SF3185  
     0 "No"
     1 "Yes"
;
label define SF3200  
     0 "No"
     1 "Yes"
;
label define SF3201  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SF3201A 
     0 "No"
     1 "Yes"
;

#delimit cr
label values sf3121   SF3121  
label values sf3122_1 SF3122_1
label values sf3122_2 SF3122_2
label values sf3122_3 SF3122_3
label values sf3122_4 SF3122_4
label values sf3123_1 SF3123_1
label values sf3123_2 SF3123_2
label values sf3123_3 SF3123_3
label values sf3123_4 SF3123_4
label values sf3124   SF3124  
label values sf3125_1a SF3125_1A
label values sf3125_2a SF3125_2A
label values sf3125_3a SF3125_3A
label values sf3126_1a SF3126_1A
label values sf3126_2a SF3126_2A
label values sf3126_3a SF3126_3A
label values sf3127a  SF3127A 
label values sf3127b  SF3127B 
label values sf3127c  SF3127C 
label values sf3127d  SF3127D 
label values sf3127e  SF3127E 
label values sf3127x  SF3127X 
label values sf3131   SF3131  
label values sf3132_1 SF3132_1
label values sf3132_2 SF3132_2
label values sf3133_1 SF3133_1
label values sf3133_2 SF3133_2
label values sf3133_3 SF3133_3
label values sf3134   SF3134  
label values sf3136_1a SF3136_1A
label values sf3139_1a SF3139_1A
label values sf3140a  SF3140A 
label values sf3140b  SF3140B 
label values sf3140c  SF3140C 
label values sf3140d  SF3140D 
label values sf3140e  SF3140E 
label values sf3140x  SF3140X 
label values sf3151   SF3151  
label values sf3152   SF3152  
label values sf3153_1 SF3153_1
label values sf3153_2 SF3153_2
label values sf3153_3 SF3153_3
label values sf3154_1 SF3154_1
label values sf3154_2 SF3154_2
label values sf3154_3 SF3154_3
label values sf3155   SF3155  
label values sf3156_1a SF3156_1A
label values sf3156_2a SF3156_2A
label values sf3156_3a SF3156_3A
label values sf3157_1a SF3157_1A
label values sf3157_2a SF3157_2A
label values sf3157_3a SF3157_3A
label values sf3158a  SF3158A 
label values sf3158b  SF3158B 
label values sf3158c  SF3158C 
label values sf3158d  SF3158D 
label values sf3158e  SF3158E 
label values sf3158x  SF3158X 
label values sf3160   SF3160  
label values sf3161   SF3161  
label values sf3162   SF3162  
label values sf3163_1 SF3163_1
label values sf3163_2 SF3163_2
label values sf3163_3 SF3163_3
label values sf3163_4 SF3163_4
label values sf3163_5 SF3163_5
label values sf3163_6 SF3163_6
label values sf3164_1 SF3164_1
label values sf3164_2 SF3164_2
label values sf3164_3 SF3164_3
label values sf3164_4 SF3164_4
label values sf3165   SF3165  
label values sf3166_1a SF3166_1A
label values sf3166_1b SF3166_1B
label values sf3166_1c SF3166_1C
label values sf3166_1d SF3166_1D
label values sf3166_2a SF3166_2A
label values sf3166_2b SF3166_2B
label values sf3166_2c SF3166_2C
label values sf3166_2d SF3166_2D
label values sf3166_3a SF3166_3A
label values sf3166_3b SF3166_3B
label values sf3166_3c SF3166_3C
label values sf3166_3d SF3166_3D
label values sf3166_4a SF3166_4A
label values sf3166_4b SF3166_4B
label values sf3166_4c SF3166_4C
label values sf3166_4d SF3166_4D
label values sf3167   SF3167  
label values sf3168_1a SF3168_1A
label values sf3168_1b SF3168_1B
label values sf3168_1c SF3168_1C
label values sf3168_1d SF3168_1D
label values sf3168_2a SF3168_2A
label values sf3168_2b SF3168_2B
label values sf3168_2c SF3168_2C
label values sf3168_2d SF3168_2D
label values sf3168_3a SF3168_3A
label values sf3168_3b SF3168_3B
label values sf3168_3c SF3168_3C
label values sf3168_3d SF3168_3D
label values sf3168_4a SF3168_4A
label values sf3168_4b SF3168_4B
label values sf3168_4c SF3168_4C
label values sf3168_4d SF3168_4D
label values sf3169   SF3169  
label values sf3170   SF3170  
label values sf3171   SF3171  
label values sf3172   SF3172  
label values sf3173   SF3173  
label values sf3174   SF3174  
label values sf3175   SF3175  
label values sf3176   SF3176  
label values sf3177   SF3177  
label values sf3178   SF3178  
label values sf3179   SF3179  
label values sf3180   SF3180  
label values sf3181   SF3181  
label values sf3182   SF3182  
label values sf3183   SF3183  
label values sf3184   SF3184  
label values sf3185   SF3185  
label values sf3200   SF3200  
label values sf3201   SF3201  
label values sf3201a  SF3201A 
