DATA LIST FILE='C:\Countries\HT7A\HTAN7AFLSR.DAT' RECORDS=1
  /
  INV_ID      1-5   
  P_ID        6-7   
  OBS_N       8-9    (A)
  OBS_ID     10-12  
  C000       13-16   (A)
  C001       17-18  
  C002       19-22  
  C003       23-23  
  C004       24-28  
  C004P      29-30  
  C004CT     31-32   (A)
  C004CN     33-35  
  C005       36-43  
  C007       44-45  
  C008       46-47  
  C009A      48-51  
  C009B      52-55  
  C009C      56-58  
  C020A      59-59  
  C020B      60-60  
  C021       61-61  
  C022       62-62  
  C023       63-63  
  C024       64-65  
  C032       66-67  
  C033       68-71  
  C033D      72-73  
  C501       74-76  
  C502A      77-77  
  C502B      78-78  
  C502C      79-79  
  C502E      80-80  
  C502F      81-81  
  C502G      82-82  
  C502H      83-83  
  C502I      84-84  
  C502J      85-85  
  C502K      86-86  
  C502L      87-87  
  C503       88-88  
  C504       89-89  
  C505       90-95  
  C507       96-96  
  C508       97-98  
  C510       99-99  
  C511      100-101 
  C512      102-102 
  C514      103-103 
  C515      104-104 
  C517A     105-108 
  C517B     109-112 
  C518A     113-116 
  C518B     117-120 
  C520      121-122 
  C521      123-123 
  C522      124-124 
  SCDEPART  125-126 
  SCLOCAL   127-127 
  C101A     128-128 
  C101F     129-129 
  C102      130-130 
  C102F     131-131 
  C103A     132-132 
  C103B     133-133 
  C103C     134-134 
  C103D     135-135 
  C103Y     136-136 
  C104A     137-137 
  C104B     138-138 
  C104C     139-139 
  C104D     140-140 
  C104E     141-141 
  C104F     142-142 
  C104G     143-143 
  C104H     144-144 
  C104I     145-145 
  C104J     146-146 
  C104K     147-147 
  C104Y     148-148 
  C105A     149-149 
  C105B     150-150 
  C105C     151-151 
  C105D     152-152 
  C105E     153-153 
  C105F     154-154 
  C105G     155-155 
  C105H     156-156 
  C105X     157-157 
  C105Y     158-158 
  C105A1    159-159 
  C105B1    160-160 
  C105C1    161-161 
  C105D1    162-162 
  C105E1    163-163 
  C105F1    164-164 
  C105G1    165-165 
  C105H1    166-166 
  C105X1    167-167 
  C105Y1    168-168 
  C106A     169-169 
  C106B     170-170 
  C106C     171-171 
  C106D     172-172 
  C106K     173-173 
  C106L     174-174 
  C106M     175-175 
  C106N     176-176 
  C106O     177-177 
  C106P     178-178 
  C106Q     179-179 
  C106R     180-180 
  C106Y     181-181 
  CF106A    182-182 
  CF106K    183-183 
  CF106XA   184-184 
  CF106XB   185-185 
  CF106XC   186-186 
  CF106XD   187-187 
  CF106XE   188-188 
  CF106XF   189-189 
  CF106XG   190-190 
  C107A     191-191 
  C107B     192-192 
  C107C     193-193 
  C107D     194-194 
  C107E     195-195 
  C107F     196-196 
  C107P     197-197 
  C107Q     198-198 
  C107Y1    199-199 
  C107Y2    200-200 
  C107Y3    201-201 
  C108      202-202 
  C110      203-203 
  C111      204-204 
  C111A     205-205 
  C111B     206-206 
  C111C     207-207 
  C111E     208-208 
  C113      209-209 
  C114      210-210 
  C115      211-211 
  C116A     212-212 
  C116      213-213 
  C117      214-215 
  C117F     216-216 
  C118      217-217 
  C119A     218-218 
  C119B     219-219 
  C119C     220-220 
  C119D     221-221 
  C119Y     222-222 
  C120A     223-223 
  C120B     224-224 
  C120C     225-225 
  C120D     226-226 
  C120E     227-227 
  C120Y     228-228 
  C121A     229-229 
  C121B     230-230 
  C121C     231-231 
  C121D     232-232 
  C121E     233-233 
  C121F     234-234 
  C121G     235-235 
  C121H     236-236 
  C121I     237-237 
  C121Y     238-238 
  C122A     239-239 
  C122B     240-240 
  C122C     241-241 
  C122D     242-242 
  C122Y     243-243 
  C150      244-244 
  C151      245-245 
  C152      246-247 
  C154      248-248 
  C155A     249-249 
  C156      250-250 
  C158      251-251 
  C159      252-252 
  C160A     253-253 
  C160B     254-254 
  C160C     255-255 
  C160X     256-256 
  C160Z     257-257 
  C161      258-258 
  C166      259-259 
  C166A     260-260 
  C167A     261-261 
  C167B     262-262 
  C167C     263-263 
  C167D     264-264 
  C167E     265-265 
  C167F     266-266 
  C167G     267-267 
  C167X     268-268 
  C167Z     269-269 
  C168      270-270 
  C169      271-271 
  C170A     272-272 
  C170B     273-273 
  C170C     274-274 
  C170D     275-275 
  C170E     276-276 
  C170F     277-277 
  C170G     278-278 
  C170H     279-279 
  C170I     280-280 
  C170X     281-281 
  C170Z     282-282 
  C171A     283-283 
  C171B     284-284 
  C171C     285-285 
  C171X     286-286 
  C171Y     287-287 
  C172A     288-288 
  C172B     289-289 
  C172C     290-290 
  C172D     291-291 
  C172Y     292-292 
  C173      293-293 
  C174      294-294 
  C175      295-296 
  C176      297-297 
  C177      298-298 
  C178      299-299 
  C179      300-300 
  C180      301-301 
  C181      302-302 
  C182      303-303 
  C183      304-304 
  C184      305-305 
  SOA110Y   306-306 
  SOA115Y   307-307 
 .
VARIABLE LABELS
   INV_ID   "INVENTORY ID"
  /P_ID     "Unit/Provider line number ID"
  /OBS_N    "Client type code"
  /OBS_ID   "Client ID"
  /C000     "Survey phase"
  /C001     "Department (Country-specific)"
  /C002     "Commune (Country-specific)"
  /C003     "Urban/rural"
  /C004     "Facility number"
  /C004P    "Provider line number"
  /C004CT   "Client type code (alpha)"
  /C004CN   "Client ID number"
  /C005     "Sample weight"
  /C007     "Facility type (Country-specific)"
  /C008     "Facility managing authority (Country-specific)"
  /C009A    "Interviewer for observation"
  /C009B    "Interviewer for exit interview"
  /C009C    "NA - Keyer"
  /C020A    "Result of observation"
  /C020B    "Result of exit interview"
  /C021     "Type of client"
  /C022     "Sex of provider"
  /C023     "Sex of client/sick child"
  /C024     "Technical qualification of provider (Country-specific within ranges)"
  /C032     "Month of observation/interview"
  /C033     "Year of observation/interview"
  /C033D    "Day of observation/interview"
  /C501     "Duration of wait before being seen"
  /C502A    "Client problem during visit: Time had to wait"
  /C502B    "Client problem during visit: Ability to discuss problems/concerns"
  /C502C    "Client problem during visit: Amount of explanation for problem/tx"
  /C502E    "Client problem during visit: Visual privacy"
  /C502F    "Client problem during visit: Auditory privacy"
  /C502G    "Client problem during visit: Availability of medicines at facility"
  /C502H    "Client problem during visit: Hours of service"
  /C502I    "Client problem during visit: Days of service"
  /C502J    "Client problem during visit: Cleanliness of facility"
  /C502K    "Client problem during visit: Staff treatment of client"
  /C502L    "Client problem during visit: Cost"
  /C503     "Part of prepayment plan/insurance that pays part of cost"
  /C504     "Charged for services today"
  /C505     "Total amount paid in Gourdes"
  /C507     "Facility nearest to home"
  /C508     "Reason did not go to nearest facility"
  /C510     "Caretaker relationship to sick child (Sick child exit only)"
  /C511     "Age of client (caretaker of client)"
  /C512     "Highest level of education attended"
  /C514     "Literacy level"
  /C515     "Country reported highest level of education attended (CS)"
  /C517A    "Time observation interview began"
  /C517B    "Time observation interview ended"
  /C518A    "Time exit interview began"
  /C518B    "Time exit interview ended"
  /C520     "Opinion of services given today"
  /C521     "Would recommend to friend/family member"
  /C522     "First observation for this provider for this service"
  /SCDEPART "CS - Region with West separated for metropolitan and other"
  /SCLOCAL  "CS - Metropolitan/other cities/locality"
  /C101A    "Number of visits to this facility for this pregnancy (OBSERVATION only)"
  /C101F    "Flag: Consistency of visit number: observation and exit (C155)"
  /C102     "Client first pregnancy (OBSERVATION only)"
  /C102F    "Flag: Consistency of first pregnancy: observation and exit (C154)"
  /C103A    "Client history information provided: Age"
  /C103B    "Client history information provided: Current medications"
  /C103C    "Client history information provided: Date last menstrual period began"
  /C103D    "Client history information provided: Number of prior pregnancies"
  /C103Y    "Client history information provided: No history mentioned"
  /C104A    "Client prior pregnancy: Prior stillbirth(s)"
  /C104B    "Client prior pregnancy: Infants who died in first week"
  /C104C    "Client prior pregnancy: Heavy bleeding during or after delivery"
  /C104D    "Client prior pregnancy: Previous assisted delivery"
  /C104E    "Client prior pregnancy: Previous spontaneous abortions"
  /C104F    "Client prior pregnancy: Multiple pregnancies"
  /C104G    "Client prior pregnancy: Prolonged labor"
  /C104H    "Client prior pregnancy: Pregnancy-induced hypertension"
  /C104I    "Client prior pregnancy: Pregnancy related convulsions"
  /C104J    "Client prior pregnancy: High fever or infection during prior pregnancy/pregnancies"
  /C104K    "CS - Client prior pregnancy: Infants who died during first 4 weeks"
  /C104Y    "Client prior pregnancy: No aspects of prior pregnancies mentioned"
  /C105A    "Provider/client asked about danger sign: Bleeding"
  /C105B    "Provider/client asked about danger sign: Fever"
  /C105C    "Provider/client asked about danger sign: Headache or blurred vision"
  /C105D    "Provider/client asked about danger sign: Swollen face, hands or extremities"
  /C105E    "Provider/client asked about danger sign: Tiredness or breathlessness"
  /C105F    "Provider/client asked about danger sign: Fetal movement (loss of, excessive, normal)"
  /C105G    "Provider/client asked about danger sign: Any other symptoms or problems in pregnancy"
  /C105H    "Provider/client asked about danger sign: Cough or difficulty breathing for 3 weeks or longer"
  /C105X    "NA - Provider/client asked about danger sign: Other problems client believes related to pregnancy"
  /C105Y    "Provider/client asked about danger sign: No danger signs of current pregnancy mentioned"
  /C105A1   "Provider counseled danger sign: Bleeding"
  /C105B1   "Provider counseled danger sign: Fever"
  /C105C1   "Provider counseled danger sign: Headache or blurred vision"
  /C105D1   "Provider counseled danger sign: Swollen face, hands or extremities"
  /C105E1   "Provider counseled danger sign: Tiredness or breathlessness"
  /C105F1   "Provider counseled danger sign: Fetal movement (loss of, excessive, normal)"
  /C105G1   "Provider counseled danger sign: Any other symptoms or problems in pregnancy"
  /C105H1   "Provider counseled danger sign: Cough or difficulty breathing for 3 weeks or longer"
  /C105X1   "NA - Provider counseled danger sign: Other problems client believes related to pregnancy"
  /C105Y1   "Provider counseled danger sign: No danger signs of current pregnancy counseled"
  /C106A    "Procedures performed: Blood pressure"
  /C106B    "Procedures performed: Palpate abdomen for fetal presentation"
  /C106C    "Procedures performed: Palpate abdomen for fetal height"
  /C106D    "Procedures performed: Listen to abdomen for fetal heartbeat"
  /C106K    "Procedures performed: Weigh client"
  /C106L    "Procedures performed: Examine conjunctiva/palms for anemia"
  /C106M    "Procedures performed: Examine legs/feet/hands for edema"
  /C106N    "Procedures performed: Examine client's breasts"
  /C106O    "Procedures performed: Conduct vaginal exam/exam of perineal area"
  /C106P    "Procedures performed: Examine for swollen glands"
  /C106Q    "Procedures performed: Conduct/refer ultrasound or look at ultrasound report"
  /C106R    "NA - Procedures performed: Measure fundal height with a tape measure"
  /C106Y    "Procedures performed: None of physical exam components"
  /CF106A   "Routine action in facility: Blood pressure"
  /CF106K   "Routine action in facility: Weigh client"
  /CF106XA  "Routine action in facility: Conduct group health education"
  /CF106XB  "Routine action in facility: Urine test for protein"
  /CF106XC  "Routine action in facility: Blood test for anemia"
  /CF106XD  "NA - Routine action in facility: Malaria RDT"
  /CF106XE  "NA - Routine action in facility: HIV testing and counseling"
  /CF106XF  "NA - CS Routine action in facility: Syphilis RDT"
  /CF106XG  "NA - CS Routine action in facility: Blood sample for lab Syphilis testing"
  /C107A    "Provider treatments or counsel: Prescribe/give iron, folic acid or both"
  /C107B    "Provider treatments or counsel: Explain purpose of iron/folic acid"
  /C107C    "Provider treatments or counsel: Explain how to take iron/folic acid tablets"
  /C107D    "Provider treatments or counsel: Explain side effects of iron tablets"
  /C107E    "Provider treatments or counsel: Prescribe or give tetanus toxoid injection"
  /C107F    "Provider treatments or counsel: Explain purpose of tetanus toxoid"
  /C107P    "Provider treatments or counsel: Prescribe or give deworming medication"
  /C107Q    "Provider treatments or counsel: Explain purpose of deworming medication"
  /C107Y1   "Provider treatments or counsel: No Iron Prophylaxis components"
  /C107Y2   "Provider treatments or counsel: No Tetanus Toxoid components"
  /C107Y3   "Provider treatments or counsel: No Deworming components"
  /C108     "Provider discussed quantity/quality of food eaten during pregnancy"
  /C110     "Provider informed client about progress of pregnancy"
  /C111     "Provider discussed importance of at least 4 ANC visits"
  /C111A    "Provider advised/counsel about delivery: Asked client where she will deliver"
  /C111B    "Provider advised/counsel about delivery: Use skilled health worker for delivery"
  /C111C    "Provider advised/counsel about delivery: Items to have for home delivery"
  /C111E    "Provider advised/counsel about delivery: Advised to prepare for delivery"
  /C113     "Provider discussed use of family planning after delivery"
  /C114     "Provider asked if client had any questions/encouraged questions"
  /C115     "Provider used visual aids during consult"
  /C116A    "Provider looked at client health card"
  /C116     "Provider wrote on client health card"
  /C117     "Weeks of pregnancy according to provider"
  /C117F    "Flag: Consistency of weeks of pregnancy in observation and exit (C152)"
  /C118     "Outcome of consult"
  /C119A    "Routine tests: Perform or refer for anemia (hemoglobin) test"
  /C119B    "Routine tests: Perform or refer for urine test"
  /C119C    "Routine tests: Perform or refer for syphilis test"
  /C119D    "Routine tests: Perform or refer for blood grouping"
  /C119Y    "Routine tests: Perform or refer for no test"
  /C120A    "HIV counsel/test: Ask if client knows HIV status"
  /C120B    "HIV counsel/test: Provide counseling related to HIV test"
  /C120C    "HIV counsel/test: Refer for counseling related to HIV test"
  /C120D    "HIV counsel/test: Perform HIV test"
  /C120E    "HIV counsel/test: Refer for HIV test"
  /C120Y    "HIV counsel/test: No HIV counsel/test"
  /C121A    "NA - Malaria: Gave malaria prophylaxis medicine (SP) during consult"
  /C121B    "NA - Malaria: Prescribed malaria prophylaxis medicine (SP) for client to obtain elsewhere"
  /C121C    "NA - Malaria: Explain purpose of preventative anti-malarial"
  /C121D    "Malarial: Explain how to take anti-malarial"
  /C121E    "Malaria: Explain possible side effects of anti-malarial"
  /C121F    "NA - Malaria: Observed 1st dose of IPT taken in presence of provider"
  /C121G    "NA - Malaria: Importance of further doses of IPT explained"
  /C121H    "NA - Malaria: Provided ITN to client or instructed client to obtain ITN elsewhere in facility"
  /C121I    "Malaria: Explicitly explained importance of using ITN"
  /C121Y    "Malaria: No components of malaria prevention/protection mentioned"
  /C122A    "Newborn recommendations: Care of newborn (warmth, hygiene, etc)"
  /C122B    "Newborn recommendations: Early initiation and prolonged breastfeeding"
  /C122C    "Newborn recommendations: Exclusive breastfeeding"
  /C122D    "Newborn recommendations: Importance of newborn vaccination"
  /C122Y    "Newborn recommendations: No newborn/post-partum recommendations given"
  /C150     "Antenatal care card seen"
  /C151     "Tetanus toxoid notation in antenatal care card"
  /C152     "Weeks pregnant according to card"
  /C154     "First pregnancy according to respondent"
  /C155A    "Number of visits to this facility for this pregnancy"
  /C156     "Given iron tablets, folic acid, combined tablet or prescriptions"
  /C158     "Provider explained how to take tablets"
  /C159     "Provider discussed side effects of iron tablets"
  /C160A    "Iron side effect known by client: Nausea"
  /C160B    "Iron side effect known by client: Black stools"
  /C160C    "Iron side effect known by client: Constipation"
  /C160X    "Iron side effect known by client: Other"
  /C160Z    "Iron side effect known by client: Don't know"
  /C161     "Provider given or prescribed anti-malarial"
  /C166     "Provider has discussed preparation for delivery"
  /C166A    "Provider has discussed preparation for delivery (this/previous visit)"
  /C167A    "Preparation for delivery: Emergency transport"
  /C167B    "Preparation for delivery: Money"
  /C167C    "Preparation for delivery: Disinfectant"
  /C167D    "Preparation for delivery: Sterile blade/scissors to cut cord"
  /C167E    "NA - Preparation for delivery: Gloves"
  /C167F    "NA - Preparation for delivery: Cord tie/ clean string"
  /C167G    "CS - Preparation for delivery: Baby stuff (clothes, etc.)"
  /C167X    "Preparation for delivery: Other"
  /C167Z    "Preparation for delivery: Don't know"
  /C168     "Has enough money for delivery"
  /C169     "Provider talked about pregnancy dangers/problems"
  /C170A    "Client knows danger sign: Bleeding"
  /C170B    "Client knows danger sign: Fever"
  /C170C    "Client knows danger sign: Swollen hand, face or extremities"
  /C170D    "Client knows danger sign: Tiredness or breathlessness"
  /C170E    "Client knows danger sign: Headache or blurred vision"
  /C170F    "Client knows danger sign: Convulsions"
  /C170G    "Client knows danger sign: Reduced or absence of fetal movement"
  /C170H    "Client knows danger sign: Premature rupture of membranes"
  /C170I    "NA - Client knows danger sign: Cough or difficulty breathing for 3 weeks or longer"
  /C170X    "Client knows danger sign: Other"
  /C170Z    "Client knows danger sign: Don't know"
  /C171A    "Provider advice if danger sign: Seek care at facility"
  /C171B    "Provider advice if danger sign: Decrease activity"
  /C171C    "Provider advice if danger sign: Change diet"
  /C171X    "Provider advice if danger sign: Other"
  /C171Y    "Provider advice if danger sign: None"
  /C172A    "Danger sign after delivery known: Heavy bleeding"
  /C172B    "Danger sign after delivery known: Fever"
  /C172C    "Danger sign after delivery known: Genital injuries"
  /C172D    "Danger sign after delivery known: None thereof"
  /C172Y    "Danger sign after delivery known: None"
  /C173     "Provider talked about diet during pregnancy"
  /C174     "Provider discussed importance of exclusive breastfeeding"
  /C175     "Number of months provider recommended for exclusive breastfeeding"
  /C176     "Provider discussed place of delivery"
  /C177     "Planned place of delivery"
  /C178     "Provider discussed FP use after delivery"
  /C179     "NA - Number of doses of IPT indicated on ANC card"
  /C180     "Provider gave anti-malaria pills to client"
  /C181     "Asked to swallow malaria pills in presence of provider"
  /C182     "Provider advised use of ITN"
  /C183     "Provider offered an ITN to client"
  /C184     "Provider offered to sell client an ITN"
  /SOA110Y  "CS - No components of maintaining a healthy pregnancy discussed"
  /SOA115Y  "CS - No components of preparation for delivery discussed"
 .
MISSING VALUE
   C003     (9)
  /C022     (9)
  /C023     (9)
  /C501     (999)
  /C502A    (9)
  /C502B    (9)
  /C502C    (9)
  /C502E    (9)
  /C502F    (9)
  /C502G    (9)
  /C502H    (9)
  /C502I    (9)
  /C502J    (9)
  /C502K    (9)
  /C502L    (9)
  /C503     (9)
  /C504     (9)
  /C505     (999999)
  /C507     (9)
  /C508     (99)
  /C510     (9)
  /C511     (99)
  /C512     (9)
  /C514     (9)
  /C515     (9)
  /C517A    (9999)
  /C517B    (9999)
  /C518A    (9999)
  /C518B    (9999)
  /C520     (99)
  /C521     (9)
  /C101A    (9)
  /C102     (9)
  /C103A    (9)
  /C103B    (9)
  /C103C    (9)
  /C103D    (9)
  /C103Y    (9)
  /C104A    (9)
  /C104B    (9)
  /C104C    (9)
  /C104D    (9)
  /C104E    (9)
  /C104F    (9)
  /C104G    (9)
  /C104H    (9)
  /C104I    (9)
  /C104J    (9)
  /C104K    (9)
  /C104Y    (9)
  /C105A    (9)
  /C105B    (9)
  /C105C    (9)
  /C105D    (9)
  /C105E    (9)
  /C105F    (9)
  /C105G    (9)
  /C105H    (9)
  /C105X    (9)
  /C105Y    (9)
  /C105A1   (9)
  /C105B1   (9)
  /C105C1   (9)
  /C105D1   (9)
  /C105E1   (9)
  /C105F1   (9)
  /C105G1   (9)
  /C105H1   (9)
  /C105X1   (9)
  /C105Y1   (9)
  /C106A    (9)
  /C106B    (9)
  /C106C    (9)
  /C106D    (9)
  /C106K    (9)
  /C106L    (9)
  /C106M    (9)
  /C106N    (9)
  /C106O    (9)
  /C106P    (9)
  /C106Q    (9)
  /C106R    (9)
  /C106Y    (9)
  /C107A    (9)
  /C107B    (9)
  /C107C    (9)
  /C107D    (9)
  /C107E    (9)
  /C107F    (9)
  /C107P    (9)
  /C107Q    (9)
  /C107Y1   (9)
  /C107Y2   (9)
  /C107Y3   (9)
  /C108     (9)
  /C110     (9)
  /C111     (9)
  /C111A    (9)
  /C111B    (9)
  /C111C    (9)
  /C111E    (9)
  /C113     (9)
  /C114     (9)
  /C115     (9)
  /C116A    (9)
  /C116     (9)
  /C117     (99)
  /C118     (9)
  /C119A    (9)
  /C119B    (9)
  /C119C    (9)
  /C119D    (9)
  /C119Y    (9)
  /C120A    (9)
  /C120B    (9)
  /C120C    (9)
  /C120D    (9)
  /C120E    (9)
  /C120Y    (9)
  /C121A    (9)
  /C121B    (9)
  /C121C    (9)
  /C121D    (9)
  /C121E    (9)
  /C121F    (9)
  /C121G    (9)
  /C121H    (9)
  /C121I    (9)
  /C121Y    (9)
  /C122A    (9)
  /C122B    (9)
  /C122C    (9)
  /C122D    (9)
  /C122Y    (9)
  /C150     (9)
  /C151     (9)
  /C152     (99)
  /C154     (9)
  /C155A    (9)
  /C156     (9)
  /C158     (9)
  /C159     (9)
  /C160A    (9)
  /C160B    (9)
  /C160C    (9)
  /C160X    (9)
  /C160Z    (9)
  /C161     (9)
  /C166     (9)
  /C166A    (9)
  /C167A    (9)
  /C167B    (9)
  /C167C    (9)
  /C167D    (9)
  /C167E    (9)
  /C167F    (9)
  /C167G    (9)
  /C167X    (9)
  /C167Z    (9)
  /C168     (9)
  /C169     (9)
  /C170A    (9)
  /C170B    (9)
  /C170C    (9)
  /C170D    (9)
  /C170E    (9)
  /C170F    (9)
  /C170G    (9)
  /C170H    (9)
  /C170I    (9)
  /C170X    (9)
  /C170Z    (9)
  /C171A    (9)
  /C171B    (9)
  /C171C    (9)
  /C171X    (9)
  /C171Y    (9)
  /C172A    (9)
  /C172B    (9)
  /C172C    (9)
  /C172D    (9)
  /C172Y    (9)
  /C173     (9)
  /C174     (9)
  /C175     (99)
  /C176     (9)
  /C177     (9)
  /C178     (9)
  /C179     (9)
  /C180     (9)
  /C181     (9)
  /C182     (9)
  /C183     (9)
  /C184     (9)
  /SOA110Y  (9)
  /SOA115Y  (9)
 .
VALUE LABELS
   OBS_N   
   'AN' "ANC"
   'SC' "Child Sick"
   'FP' "Family Planning"
   'SI' "STI"
   'IN' "Injection"
   'DC' "Delivery"
   'LD' "Labor/Delivery"
  /C001    
      1 "West"
      2 "Southeast"
      3 "North"
      4 "Northeast"
      5 "Artibonite"
      6 "Central"
      7 "South"
      8 "Grand-Anse"
      9 "Northwest"
     10 "Nippes"
  /C002    
    111 "Port-Au-Prince"
    112 "Cité-Soleil/Delmas/Tabarre"
    113 "Carrefour"
    114 "Pétion-ville"
    115 "Kenscoff"
    116 "Gressier"
    121 "Léogâne"
    122 "Petit-Goâve"
    123 "Grand-Goâve"
    131 "Croix-des-Bouquets"
    132 "Thomazeau"
    133 "Ganthier"
    134 "Cornillon"
    135 "Fonds-Verrettes"
    141 "Arcahaie"
    142 "Cabaret"
    151 "Anse-à-Galets"
    152 "Pointe-à-Raquettes"
    211 "Jacmel"
    212 "Marigot"
    213 "Cayes-Jacmel"
    214 "La Vallée"
    221 "Bainet"
    222 "Côtes-de-Fer"
    231 "Belle-Anse"
    232 "Grand-Gosier"
    233 "Thiotte"
    234 "Anse-à-Pitres"
    311 "Cap-Haïtien"
    312 "Quartier-Morin"
    313 "Limonade"
    321 "Acul-du-Nord"
    322 "Plaine-du-Nord"
    323 "Milot"
    331 "Grande-Rivière"
    332 "Bahon"
    341 "Saint-Raphaël"
    342 "Dondon"
    343 "Ranquitte"
    344 "Pignon"
    345 "La Victoire"
    351 "Borgne"
    352 "Port-Margot"
    361 "Limbé"
    362 "Bas-Limbé"
    371 "Plaisance"
    372 "Pilate"
    411 "Fort-Liberté"
    412 "Ferrier"
    413 "Perches"
    421 "Ouanaminthe"
    422 "Capotille"
    423 "Mont-Organisé"
    431 "Trou-du-Nord"
    432 "Sainte-Suzanne"
    433 "Terrier-Rouge"
    434 "Caracol"
    441 "Vallières"
    442 "Carice"
    443 "Mombin-Crochu"
    511 "Gonaïves"
    512 "Ennery"
    513 "L'Estère"
    521 "Gros-Morne"
    522 "Terre-Neuve"
    523 "Anse-Rouge"
    531 "Saint-Marc"
    532 "Verrettes"
    533 "La Chapelle"
    541 "Dessalines"
    542 "Petite-Rivière de l'Artibonite"
    543 "Grande Saline"
    544 "Desdunes"
    551 "Saint-Michel"
    552 "Marmelade"
    611 "Hinche"
    612 "Maïssade"
    613 "Thomonde"
    614 "Cerca-Cavajal"
    621 "Mirebalais"
    622 "Saut-d'Eau"
    623 "Boucan-Carré"
    631 "Lascahobas"
    632 "Belladère"
    633 "Savanette"
    641 "Cerca-La-Source"
    642 "Thomassique"
    711 "Les Cayes"
    712 "Torbeck"
    713 "Chantal"
    714 "Camp-Perrin"
    715 "Maniche"
    716 "Île-à-Vache"
    721 "Port-Salut"
    722 "Saint-Jean"
    723 "Arniquet"
    731 "Aquin"
    732 "Saint-Louis du Sud"
    733 "Cavaillon"
    741 "Côteaux"
    742 "Port-à-Piment"
    743 "Roche-à-Bateau"
    751 "Chardonnières"
    752 "Les Anglais"
    753 "Tiburon"
    811 "Jérémie"
    812 "Abricots"
    813 "Bonbon"
    814 "Moron"
    815 "Chambellan"
    821 "Anse-d'Hainault"
    822 "Dame-Marie"
    823 "Les Irois"
    831 "Corail"
    832 "Roseaux"
    833 "Beaumont"
    834 "Pestel"
    911 "Port-de-Paix"
    912 "La Tortue"
    913 "Bassin-Bleu"
    914 "Chansolme"
    921 "St-Ls-du-Nord'Ouest"
    922 "Anse-à-Foleur"
    931 "Môle-Saint-Nicolas"
    932 "Baie-de-Henne"
    933 "Bombardopolis"
    934 "Jean-Rabel"
   1001 "Fonds-des-Nègres"
   1002 "Arnaud"
   1003 "Grand-Boucan"
   1004 "Paillant"
   1005 "Plaisance"
   1041 "Miragoâne"
   1042 "Petite-Rivière de Nippes"
   1051 "Anse-à-Veau"
   1052 "Baradères"
   1053 "Petit-Trou"
   1054 "L'Asile"
  /C003    
      1 "Urban"
      2 "Rural"
  /C004CT  
   'AN' "ANC"
   'SC' "Child Sick"
   'FP' "Family Planning"
   'SI' "STI"
   'IN' "Injection"
   'DC' "Delivery"
   'LD' "Labor/Delivery"
  /C007    
      1 "University hospital"
      2 "Department hospital"
      3 "Community reference hospital"
      4 "Other hospitals"
      5 "Health Center with lit"
      6 "Health Center without lit"
      7 "Dispensary/Community Health Center"
  /C008    
      1 "Government/public"
      2 "Private not for profit"
      3 "Private for profit"
      4 "Mixed"
  /C020A   
      0 "Refused by provider or client"
      1 "Complete"
      7 "Not returned from field"
  /C020B   
      0 "Refused by client"
      1 "Complete"
      2 "Sick child admitted, not possible to continue"
      7 "Not returned from field"
  /C021    
      1 "ANC"
      2 "Child Sick"
      3 "Family Planning"
      6 "CS - Labor/Delivery"
  /C022    
      1 "Male"
      2 "Female"
  /C023    
      1 "Male"
      2 "Female"
  /C024    
      1 "Generalist Medical Doctor"
      2 "Specialist Medical Doctor"
      3 "Clinical Officer (Degree Level)"
      4 "Clinical Technician (Diploma)"
      5 "Medical Assistant"
     21 "Registered Nurse (BSN)"
     22 "Registered Nurse Midwife (BSN)"
     23 "Registered Psychiatric Nurse"
     24 "Registered Nurse with Diploma"
     25 "Enrolled Nurse"
     26 "Community Health Nurse"
     27 "Enrolled Midwife /Nurse Midwife Technical"
     28 "Enrolled Nurse Midwife"
     31 "Pharmacist"
     32 "Pharmacy Assistant"
     35 "Laboratory Technician"
     36 "Laboratory Assistant"
     37 "Radiology Technician"
     38 "Medical Imaging Technician"
     41 "Environment Health Officer"
     42 "Health Surveillance Assistant (HSA)"
     43 "HIV Testing and Counseling Counselors (NON-HSA)"
     44 "Dental Hygienist"
     71 "Other Community Health Workers"
     96 "Other"
     97 "No Technical Qualification"
     99 "Missing"
  /C032    
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
  /C501    
      0 "Saw provider immediately"
    998 "Don't know"
  /C502A   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502B   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502C   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502E   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502F   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502G   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502H   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502I   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502J   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502K   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C502L   
      0 "No problem"
      1 "Large problem"
      2 "Small problem"
      8 "Don't know"
  /C503    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C504    
      0 "No"
      1 "Yes"
  /C505    
   999998 "Don't know"
  /C507    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C508    
      1 "Inconvenient operating hours"
      2 "Bad reputation"
      3 "Don't like personnel"
      4 "No medicine"
      5 "Prefers to remain anonymous"
      6 "More expensive"
      7 "Referral"
     96 "Other"
     98 "Don't know"
  /C510    
      1 "Mother"
      2 "Father"
      3 "Sibling"
      4 "Aunt or uncle"
      5 "Grandparent"
      6 "Other"
  /C511    
     98 "Don't know"
  /C512    
      0 "Never attended school"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /C514    
      0 "Cannot read or write"
      1 "Read only"
      2 "Read and write"
      8 "Don't know"
  /C515    
      0 "No schooling"
      1 "Primary"
      2 "Post-primary/Technical"
      3 "Secondary"
      4 "Higher/University"
  /C517A   
   9797 "Inconsistent"
   9898 "Don't know"
  /C517B   
   9797 "Inconsistent"
   9898 "Don't know"
  /C518A   
   9797 "Inconsistent"
   9898 "Don't know"
  /C518B   
   9797 "Inconsistent"
   9898 "Don't know"
  /C520    
      1 "Very satisfied"
      2 "Somewhat satisfied"
      3 "Not satisfied"
  /C521    
      0 "No"
      1 "Yes"
      8 "DK"
  /C522    
      0 "No or incomplete observation"
      1 "Yes"
      2 "More than 1 reported as first"
  /SCDEPART
      0 "West"
      1 "...Metropolitan"
      2 "...Other West"
      3 "Southeast"
      4 "North"
      5 "Northeast"
      6 "Artibonite"
      7 "Central"
      8 "South"
      9 "Grand-Anse"
     10 "Northwest"
     11 "Nippes"
  /SCLOCAL 
      1 "Metropolitan"
      2 "Other cities"
      3 "Locality"
  /C101A   
      5 "5 or more visits"
      8 "Don't  know"
  /C101F   
      0 "One first visit, other not first visit"
      1 "Both the same"
      2 "Both greater than 1st visit"
  /C102    
      0 "No"
      1 "Yes, first"
      8 "Don't know"
  /C102F   
      1 "Both the same"
      2 "First pregnancy in observation, not first pregnancy reported by client"
      3 "First pregnancy reported by client, not first pregnancy in observation"
      8 "Observation responses is DK/Missing"
  /C103A   
      0 "No"
      1 "Yes"
  /C103B   
      0 "No"
      1 "Yes"
  /C103C   
      0 "No"
      1 "Yes"
  /C103D   
      0 "No"
      1 "Yes"
  /C103Y   
      0 "No"
      1 "Yes, none"
  /C104A   
      0 "No"
      1 "Yes"
  /C104B   
      0 "No"
      1 "Yes"
  /C104C   
      0 "No"
      1 "Yes"
  /C104D   
      0 "No"
      1 "Yes"
  /C104E   
      0 "No"
      1 "Yes"
  /C104F   
      0 "No"
      1 "Yes"
  /C104G   
      0 "No"
      1 "Yes"
  /C104H   
      0 "No"
      1 "Yes"
  /C104I   
      0 "No"
      1 "Yes"
  /C104J   
      0 "No"
      1 "Yes"
  /C104K   
      0 "No"
      1 "Yes"
  /C104Y   
      0 "No"
      1 "Yes, none"
  /C105A   
      0 "No"
      1 "Yes"
  /C105B   
      0 "No"
      1 "Yes"
  /C105C   
      0 "No"
      1 "Yes"
  /C105D   
      0 "No"
      1 "Yes"
  /C105E   
      0 "No"
      1 "Yes"
  /C105F   
      0 "No"
      1 "Yes"
  /C105G   
      0 "No"
      1 "Yes"
  /C105H   
      0 "No"
      1 "Yes"
  /C105X   
      0 "No"
      1 "Yes"
  /C105Y   
      0 "No"
      1 "Yes, none"
  /C105A1  
      0 "No"
      1 "Yes"
  /C105B1  
      0 "No"
      1 "Yes"
  /C105C1  
      0 "No"
      1 "Yes"
  /C105D1  
      0 "No"
      1 "Yes"
  /C105E1  
      0 "No"
      1 "Yes"
  /C105F1  
      0 "No"
      1 "Yes"
  /C105G1  
      0 "No"
      1 "Yes"
  /C105H1  
      0 "No"
      1 "Yes"
  /C105X1  
      0 "No"
      1 "Yes"
  /C105Y1  
      0 "No"
      1 "Yes, none"
  /C106A   
      0 "No"
      1 "Yes"
  /C106B   
      0 "No"
      1 "Yes"
  /C106C   
      0 "No"
      1 "Yes"
  /C106D   
      0 "No"
      1 "Yes"
  /C106K   
      0 "No"
      1 "Yes"
  /C106L   
      0 "No"
      1 "Yes"
  /C106M   
      0 "No"
      1 "Yes"
  /C106N   
      0 "No"
      1 "Yes"
  /C106O   
      0 "No"
      1 "Yes"
  /C106P   
      0 "No"
      1 "Yes"
  /C106Q   
      0 "No"
      1 "Yes"
  /C106R   
      0 "No"
      1 "Yes"
  /C106Y   
      0 "No"
      1 "Yes, none"
  /CF106A  
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF106K  
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF106XA 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF106XB 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF106XC 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF106XD 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF106XE 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF106XF 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /CF106XG 
      0 "Activity not routinely done"
      1 "Observed"
      2 "Reported, not seen"
      8 "Don't know"
  /C107A   
      0 "No"
      1 "Yes"
  /C107B   
      0 "No"
      1 "Yes"
  /C107C   
      0 "No"
      1 "Yes"
  /C107D   
      0 "No"
      1 "Yes"
  /C107E   
      0 "No"
      1 "Yes"
  /C107F   
      0 "No"
      1 "Yes"
  /C107P   
      0 "No"
      1 "Yes"
  /C107Q   
      0 "No"
      1 "Yes"
  /C107Y1  
      0 "No"
      1 "Yes, no iron prophylaxis"
  /C107Y2  
      0 "No"
      1 "Yes, no tetanus toxoid"
  /C107Y3  
      0 "No"
      1 "Yes, no deworming"
  /C108    
      0 "No"
      1 "Yes"
  /C110    
      0 "No"
      1 "Yes"
  /C111    
      0 "No"
      1 "Yes"
  /C111A   
      0 "No"
      1 "Yes"
  /C111B   
      0 "No"
      1 "Yes"
  /C111C   
      0 "No"
      1 "Yes"
  /C111E   
      0 "No"
      1 "Yes"
  /C113    
      0 "No"
      1 "Yes"
  /C114    
      0 "No"
      1 "Yes"
  /C115    
      0 "No"
      1 "Yes"
  /C116A   
      0 "No"
      1 "Yes"
      2 "No health card used"
  /C116    
      0 "No"
      1 "Yes"
      2 "No health card used"
      8 "Don't know"
  /C117    
     98 "Don't know"
  /C117F   
      0 "Inconsistent by more than 2 weeks"
      1 "Same number of weeks"
      2 "Consistent within 2 weeks"
  /C118    
      1 "Client sent home"
      2 "Client referred to lab or provider at same facility"
      3 "Client admitted to same facility"
      4 "Client referred to other facility"
  /C119A   
      0 "No"
      1 "Asked and performed"
      2 "Performed only"
      3 "Asked and referred"
      4 "Referred only"
      5 "Asked only"
  /C119B   
      0 "No"
      1 "Asked and performed"
      2 "Performed only"
      3 "Asked and referred"
      4 "Referred only"
      5 "Asked only"
  /C119C   
      0 "No"
      1 "Asked and performed"
      2 "Performed only"
      3 "Asked and referred"
      4 "Referred only"
      5 "Asked only"
  /C119D   
      0 "No"
      1 "Asked and performed"
      2 "Performed only"
      3 "Asked and referred"
      4 "Referred only"
      5 "Asked only"
  /C119Y   
      0 "No, did ask, refer or perform"
      1 "Yes, did not ask, refer, perform"
  /C120A   
      0 "No"
      1 "Yes"
  /C120B   
      0 "No"
      1 "Yes"
  /C120C   
      0 "No"
      1 "Yes"
  /C120D   
      0 "No"
      1 "Yes"
  /C120E   
      0 "No"
      1 "Yes"
  /C120Y   
      0 "No"
      1 "Yes, none"
  /C121A   
      0 "No"
      1 "Yes"
  /C121B   
      0 "No"
      1 "Yes"
  /C121C   
      0 "No"
      1 "Yes"
  /C121D   
      0 "No"
      1 "Yes"
  /C121E   
      0 "No"
      1 "Yes"
  /C121F   
      0 "No"
      1 "Yes"
  /C121G   
      0 "No"
      1 "Yes"
  /C121H   
      0 "No"
      1 "Yes"
  /C121I   
      0 "No"
      1 "Yes"
  /C121Y   
      0 "No"
      1 "Yes, none"
  /C122A   
      0 "No"
      1 "Yes"
  /C122B   
      0 "No"
      1 "Yes"
  /C122C   
      0 "No"
      1 "Yes"
  /C122D   
      0 "No"
      1 "Yes"
  /C122Y   
      0 "No"
      1 "Yes, no newborn/postpartum recommendations given"
  /C150    
      0 "No card/book used"
      1 "Yes, card seen"
      2 "Yes, card kept with facility"
  /C151    
      0 "No record"
      1 "Yes, 1 time"
      2 "Yes, 2 times"
      3 "Yes, 3 or more times"
      8 "Don't know"
  /C152    
     95 "No card available"
  /C154    
      0 "No"
      1 "Yes"
  /C155A   
      5 "More than 4 visits"
  /C156    
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /C158    
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /C159    
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /C160A   
      0 "No"
      1 "Yes"
  /C160B   
      0 "No"
      1 "Yes"
  /C160C   
      0 "No"
      1 "Yes"
  /C160X   
      0 "No"
      1 "Yes"
  /C160Z   
      0 "No"
      1 "Yes"
  /C161    
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /C166    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /C166A   
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /C167A   
      0 "No"
      1 "Yes"
  /C167B   
      0 "No"
      1 "Yes"
  /C167C   
      0 "No"
      1 "Yes"
  /C167D   
      0 "No"
      1 "Yes"
  /C167E   
      0 "No"
      1 "Yes"
  /C167F   
      0 "No"
      1 "Yes"
  /C167G   
      0 "No"
      1 "Yes"
  /C167X   
      0 "No"
      1 "Yes"
  /C167Z   
      0 "No"
      1 "Yes"
  /C168    
      0 "No"
      1 "Yes, enough"
      2 "Yes, but not enough"
  /C169    
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /C170A   
      0 "No"
      1 "Yes"
  /C170B   
      0 "No"
      1 "Yes"
  /C170C   
      0 "No"
      1 "Yes"
  /C170D   
      0 "No"
      1 "Yes"
  /C170E   
      0 "No"
      1 "Yes"
  /C170F   
      0 "No"
      1 "Yes"
  /C170G   
      0 "No"
      1 "Yes"
  /C170H   
      0 "No"
      1 "Yes"
  /C170I   
      0 "No"
      1 "Yes"
  /C170X   
      0 "No"
      1 "Yes"
  /C170Z   
      0 "No"
      1 "Yes"
  /C171A   
      0 "No"
      1 "Yes"
  /C171B   
      0 "No"
      1 "Yes"
  /C171C   
      0 "No"
      1 "Yes"
  /C171X   
      0 "No"
      1 "Yes"
  /C171Y   
      0 "No"
      1 "Yes"
  /C172A   
      0 "No"
      1 "Yes"
  /C172B   
      0 "No"
      1 "Yes"
  /C172C   
      0 "No"
      1 "Yes"
  /C172D   
      0 "No"
      1 "Yes"
  /C172Y   
      0 "No"
      1 "Yes"
  /C173    
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /C174    
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /C175    
      4 "4-6 months"
      6 "6 months"
     96 "Other"
     98 "Don't know"
  /C176    
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /C177    
      1 "This facility"
      2 "At other health facility"
      3 "At home"
      4 "At TBA home"
      6 "Other location"
      8 "Don't know/not decided"
  /C178    
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /C179    
      0 "No indication of doses"
  /C180    
      0 "No"
      1 "Yes, see C161 for timing of provision"
      8 "Don't know"
  /C181    
      0 "No"
      1 "Yes"
  /C182    
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /C183    
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /C184    
      0 "No"
      1 "Yes, this and previous visit"
      2 "Yes, only this visit"
      3 "Yes, only previous visit"
      8 "Don't know"
  /SOA110Y 
      0 "No"
      1 "Yes, none"
  /SOA115Y 
      0 "No"
      1 "Yes, none"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\HT7A\HTAN7AFLSR.sav'.
